### ISSUE TITLE
Reading MP4 files or M4a files

### ISSUE THREAD

**Issue by karanmartian** [Zeugma440/atldotnet#10]
Hi I want to be able to use this library to read M4a files from Mp4 files. Basically I am extracting the video portion separately for video processing and want to sync and play the extracted m4a portion from the mp4 file. Can you give an example of how to read a piece of audio frame from m4a and use it?

**Comment by Zeugma440** [comment]
Hello @karanmartian and thanks for your interest in ATL.NET

Unfortunately, this library is aimed at manipulating metadata (i.e. tags, chapters), not the audio data itself.


For this usage, you can try the following libraries :

- ffmpeg# (https://github.com/vladjerca/FFMpegSharp)

- L-Smash (https://github.com/l-smash/l-smash + http://avisynth.nl/index.php/LSMASHSource)

- MP4v2 (https://github.com/pcwalton/mp4v2)
