### ISSUE TITLE
Recognize .oga file as a valid format.

### ISSUE THREAD

**Issue by antoniozh** [Zeugma440/atldotnet#100]
## The problem

When I try to instantiate a Track with an .oga file, the properties don't load properly. However, when I rename it to .ogg, it works.
I think .oga is a valid file extension for the format, since I get it from Telegram in that extension. 
https://fileinfo.com/extension/oga

## Environment

ATL.NET 3.22.0
.NET 452

## Code To Reproduce Issue [ Good To Have ]

Track track = new Track(".\audio.oga");
Console.Write(track.SampleRate);

**Comment by Zeugma440** [comment]
Fair enough. Didn't know about the OGA format, to be honest.

I'll take care about it. As a workaround, you can load the `Track` using a `Stream` and the mime-type `audio/ogg`

**Comment by antoniozh** [comment]
I renamed it to .ogg with File.Rename, but will remove that line when you patch it, thanks for your great work!

**Comment by Zeugma440** [comment]
Fixed in today's v3.23
