### ISSUE TITLE
Using a file name referenced with URL instead of on local machine.

### ISSUE THREAD

**Issue by codePenny** [Zeugma440/atldotnet#11]
## The problem

I'd like to incorporate ATL as a utility to get the duration of a track.
It works successfully with a file on my local machine (eg C:/temp/MP3/test.mp3) but not with any files hosted on a web server (example using Web Server for Chrome http://192.168.0.7:8888/temp/MP3/test.mp3).
Is there any way to use your library where the path/filename is simply referenced with a URL?

## Code Sample

string fileName = "http://192.168.0.7:8888/temp/MP3/test.mp3";
Track theTrack = new Track(fileName);
var trackDuration = theTrack.Duration;

**Comment by Zeugma440** [comment]
Hello @codePenny,


First of all, thanks for your interest in ATL.NET.

For now, the library is centered around its core features, i.e. metadata reading and writing on local files.

I do not intend to add proper networking support in the near future. Doing it properly with performance in mind would mean managing a "download pipe" that would run in parallel to temporary file reading; that means a lot of new code to create and test.

For now I recommend you implement your own download methods. Start here for a basic sample code : https://stackoverflow.com/questions/307688/how-to-download-a-file-from-a-url-in-c


Best regards,
-Z440
