### ISSUE TITLE
Support for some modern/unofficial Id3v2 Tags.

### ISSUE THREAD

**Issue by DividedSE** [Zeugma440/atldotnet#111]
TSO2(Artist Sort - string), 
TSOC(Composer Sort -string), 
TCMP(Compilation - stores 1 if song is a part of a compilation or remover the tag if not) 
This is some Unoffical Id3 Tags used by some modern apps like itunes & Musicbrainz also currently recognised by ID3.Org. ATL can read them from native fields but writes them in TXXX/TSO2 instead of native TSO2 field
It is a easy solution as I did just added "TSO2", "TSOC" & "TCMP" in ID3v2.cs -> standardFrames_v24 list
but it is pain to do it everytime with new commit.

**Comment by Zeugma440** [comment]
Done for the next release

**Comment by DividedSE** [comment]
Thanks for quick Addition. Tested Working.
