### ISSUE TITLE
Support for some more Common File properties in TechnicalInformation

### ISSUE THREAD

**Issue by DividedSE** [Zeugma440/atldotnet#112]
Just being more lazy or not(As I already done 3/4 & could not figure out the 4th one) would be good to have build in atl itself.
1)File Created -> System.IO.File.GetCreationTime
2)File Modified -> System.IO.File.GetLastWriteTime
3)File Accesed -> System.IO.File.GetLastAccesedTime
4) File Permission -> ??? ( as "-rw-rw-rw")
5) or anything else (check exiftool(exiftool.org) - which can shows but atl currently not)

**Comment by Zeugma440** [comment]
ATL actually did this in its earlier versions, but I eventually realized two things about these pieces of information :
- They do not add any value to the library, as it just encapsulates .NET features
- Querying these fields requires extra OS calls that dramatically reduce mass reading speed (think about people who use ATL to scan their entire music library)

=> Best way to have that on your app would be to create a custom class that encapsulates (or inherits from) `Track`, and implements extra fields that are valued using `System.IO.FileInfo`
