### ISSUE TITLE
DISP chunk in WAV file

### ISSUE THREAD

**Issue by grego892** [Zeugma440/atldotnet#116]
Would it be possible to support the DISP chunk?  I believe is not part of the INFO chunk but possibly part of the root or WAVE.

I'm trying to support some files from work and no C# library seems to be able to find it.

![image](https://user-images.githubusercontent.com/16366927/133949169-9cb038e2-ef84-49d3-a261-c3f6873f445e.png)

https://drive.google.com/file/d/1Umr7EI-GF0zBtk6m_SmBg9HNqigxU3Mq/view?usp=sharing

Thank you very much.  If there's anything I can do, just ask.

**Comment by Zeugma440** [comment]
Well certainly. I'll keep you updated.

PS : thanks for the sample !

**Comment by Zeugma440** [comment]
I've just pushed an update to `master` that should do the trick.

The `disp` chunks are now visible inside `Track.AdditionalFields`.

NB : When `disp[x].type` is anything else than `CF_TEXT`, the corresponding `disp[x].value` is base-64 encoded.


Let me know if it works for you ! 😄

**Comment by grego892** [comment]
Awesome, thank you.  Newbie question...  I see the updated code on the .zip I downloaded, but how do I add that to my project?  I have only added and updated through Nuget.  Nuget shows it was updated 17 days ago.

**Comment by Zeugma440** [comment]
Oh I see... I'll publish a new release to NuGet in 12-ish hours then 👌

**Comment by Zeugma440** [comment]
I've just published v3.25 on NuGet.

Let me know if it works for you 😉

**Comment by grego892** [comment]
Works great.

Thank you so much for your help.  I’ve been hunting down a solution for months.  And I leaned stuff in this process too !!

Greg Davis
***@***.***

________________________________

**Comment by Zeugma440** [comment]
You're very welcome.

Don't hesitate to submit another issue if you ever need anything else. The RIFF format is extremely rich, and I haven't implemented everything yet.
