### ISSUE TITLE
Read from byte array or stream

### ISSUE THREAD

**Issue by sepehr1014** [Zeugma440/atldotnet#12]
It would be great if we could pass `byte[]` or `Stream` to the constructor of `Track`.

**Comment by Zeugma440** [comment]
Hello @sepehr1014 


First of all, thank you for your interest in ATL.net !

I would love to improve the library to fit your needs, but I fear you'll have to be a little more specific :

- What would these parameters be used for ? Reading ? Writing ? Which information ?
- I suppose you plan to use them to store binary data. What would be the format of this data ?

The best would be to explain what you intend to do with my library, fonctionally speaking. Based on your objectives, we'll have a discussion about how that can be integrated.


Thanks in advance for your feedback,

Best regards,

~Z440

**Comment by sepehr1014** [comment]
Hi,

Thank you for this great project! We have an API that receives files (byte array or stream format) and we want to do some validation checks before saving the file on disk. For example we want to check if the file headers are properly set and if the duration is lower than the maximum. BTW the files are OGG with OPUS codec.

Regards,
Sepehr

**Comment by Zeugma440** [comment]
Hi,

Thanks for the explanation, it's much clearer now !

Being able to handle in-memory data directly into Track would definitely be an interesting feature. I'm not a big fan of byte arrays, so I'll consider using a Stream.

However, as you probably saw, we're talking about changes that will affect **many** classes. That won't be an easy one, and it might take some time to get it right and clean. I'll be working on it and keep you informed !


All the best,
~Z440

**Comment by sepehr1014** [comment]
@Zeugma440 
Seems to be working great.

Thank you

**Comment by Zeugma440** [comment]
Will be included in next release
