### ISSUE TITLE
Long fields are ignored

### ISSUE THREAD

**Issue by Pedrokostam** [Zeugma440/atldotnet#120]
## The problem

It appears that long tags (more than 500 bytes) are treated as a picture. Since the name does not match IDs for pictures, that tag gets ignored. 

## Environment

Version 3.25. Problem appeared both in the downloaded nuget package in another project and in the downloaded project from GitHub.
 
## Details

I had problems with one flac file containing an embedded cuesheet (tag: cusheet). No matter what, the tag did not show in the file (not in AdditionalFields or anywhere else). I ran some tests and it turns out, that the cuesheet was too long (966 bytes). This caused to be classified as a large field, treated as a picture and then ignored due to its ID not matching any picture ID. 

I tested it on a flac file with native tags. it appears that any file can be used to replicate the issue as long as the size is greater or equal than 500 bytes.

Changing the limit in the read method (VorbisTag.cs, line 337) from 500 to 1500 helped with my immediate problem (the cuesheet was presented as an additional tag).

I don't know if the issue happens with different tag or audio formats.

## Code To Reproduce Issue 

A flac file with a tag field longer than 500 bytes.

**Comment by Zeugma440** [comment]
Correct. That part of the code is kinda legacy, it's cleanup time !

**Comment by Zeugma440** [comment]
Fixed in today's v4.00 (be sure to read new requirements)
