### ISSUE TITLE
ATL.AudioData.IO.FileSurgeon.RewriteZones  Takes a really long time

### ISSUE THREAD

**Issue by JKamsker** [Zeugma440/atldotnet#122]
## The problem
rack.Save() call takes 5 minutes

I am editing the metadata of an m4b audiobook (12h long).
Because there are 75k zones in my file, the loop through region.Zones takes appearantly a considerable amount of time.

Is there any way i could circumvent this issue?

## Environment

* ATL version (or git revision) that exhibits the issue: Current main
* OS/version used to run ATL: Windows

## Details

If necessary, describe the problem you have been experiencing in more detail.

Don't forget to include ATL.Logging.Log and/or console output

**Comment by Zeugma440** [comment]
FYI, AaxAudioConverter, which has contributed a lot to testing audiobooks, has set a 2MB I/O buffer size.

https://github.com/audiamus/AaxAudioConverter/blob/d0e975dc3ee18c8fac4602c29c4854de9055f55f/src/AaxAudioConverterLib/TagAndFileNamingHelper.cs#L839

**Comment by JKamsker** [comment]
Even 50MB buffers wont bring a whole lot - still 2 minutes per file :/

**Comment by Zeugma440** [comment]
I'm gonna have to take a closer look. Is that the file you sent on your other issue ?

If not, could you send a download link to that 12-hours long file ?

Thanks~

**Comment by JKamsker** [comment]
Have sent you an email

**Comment by Zeugma440** [comment]
Not for myself : same issue as #98

**Comment by Zeugma440** [comment]
Good news : I've located an optimization that kills processing time from 1min+ to 10 seconds on my side.

Please update your code to get the latest commit : e065faf5493e492bfc520b0f292cd5497f2ab851 and keep me informed

**Comment by JKamsker** [comment]
Insane! Yea thats hell of a lot faster! 


I have one issue now: Vlc isn't able to read the chapter data anymore: 
![image](https://user-images.githubusercontent.com/11245306/148682484-8a7e06b1-7290-491f-bc48-1a05566061b7.png)

But ffmpeg can read it:
![image](https://user-images.githubusercontent.com/11245306/148682530-96514b86-4bd0-4f30-a601-4b78275d3954.png)

Seems like the library cuts off some fractions of a millisecond of each chapter, otherwise i have no idea :/

**Comment by JKamsker** [comment]
OT: Although  it doesnt help much,  you could look up the zones only once, that would make execution time a bit faster (maybe 2ms :P)
![image](https://user-images.githubusercontent.com/11245306/148683069-de5104bb-07c6-4668-aa37-ae09db84abd3.png)

**Comment by Zeugma440** [comment]
Regarding the issue with chapters, ATL writes Quiktime _and_ Nero chapters by default. However, your original file only has Quicktime chapters.

I advise you to call `Settings.MP4_createNeroChapters = false;` before you process the file. It will ensure only Quicktime chapters are added. I just checked and it fixes the issue with VLC.

**Comment by JKamsker** [comment]
Oh thanks, that did the job 😅

**Comment by Zeugma440** [comment]
Included in today's v4.02
