### ISSUE TITLE
Embedded Picture doesn't get saved

### ISSUE THREAD

**Issue by JKamsker** [Zeugma440/atldotnet#126]
## The problem

The embedded picture doesn't get saved

## Environment

* ATL version (or git revision) that exhibits the issue: 4.3.0
* Last ATL version that did not exhibit the issue (if applicable): 4.2.0 (I guess)
* OS/version used to run ATL: Windows

## Details

Happens on the audiobook i sent you for https://github.com/Zeugma440/atldotnet/issues/125

How to reproduce:
load & save the file

**Comment by JKamsker** [comment]
Saving is appearantly working. Just reading it does not work

**Comment by Zeugma440** [comment]
Could you please post the code you're using so that I can reproduce that problem ?

Thanks~

**Comment by JKamsker** [comment]
Not on my pc but its really just loading the audiofile with new Track("path")

The picture wont be loaded in correctly

**Comment by Zeugma440** [comment]
I'm asking you because basic instructions work, even on that file

```cs
Settings.FileBufferSize = 2 * 1024 * 1024;

// Instanciate file
Track theTrack = new Track(filePath);

// Set image as front picture
byte[] data = File.ReadAllBytes(@"D:\temp\mp3\windowsIcon\folder.jpg");
PictureInfo newPicture = PictureInfo.fromBinaryData(data, PictureInfo.PIC_TYPE.Front);
theTrack.EmbeddedPictures.Add(newPicture);

// Save modifications on disk
theTrack.Save();

// Reload saved file to be sure all data is reset and reloaded for the purpose of this test
theTrack = new Track(filePath, progress);

// Display the number of embedded pictures
Console.WriteLine(">>> NB PICS : " + theTrack.EmbeddedPictures.Count); // <- output says 1
```

**Comment by JKamsker** [comment]
Oh sorry, my bad!
I switched the decrypter which didn't copy over the image. Vlc still showed me the cached image for some reason. Thats why i thought the lib was faulty 😅
