### ISSUE TITLE
Title == FilenameWithoutExtension

### ISSUE THREAD

**Issue by nlogozzo** [Zeugma440/atldotnet#129]
For some reason, if the `Title` property is not set on a tag the library returns the filename without the extension for the `Title` property of a `Track` object. This is bad design, as I am creating a tagging application, similar to MP3Tag, and the user may think that the Title property is set when in reality it's not. Why doesn't `Track.Title` return an empty string like the rest of the properties when it is not actually set in the file's metadata?

Using z440.atl.core V4.3.0

**Comment by Zeugma440** [comment]
You can toggle this behaviour with `ATL.Settings.UseFileNameWhenNoTitle = false;`

**Comment by nlogozzo** [comment]
Oh didn't know that. Thanks!
