### ISSUE TITLE
Unable to read MP3 metadata in .Net Standard

### ISSUE THREAD

**Issue by mattjopete** [Zeugma440/atldotnet#13]
## The problem

I am unable to read metadata from MP3 files using the  latest atl Nuget package.  
## Environment

* ATL version (or git revision) that exhibits the issue:
* Last ATL version that did not exhibit the issue (if applicable):
* OS/version used to run ATL

I'm using 2.42 from nuget in a .Net Standard 2.0 class library project being called by a UWP project I am working on.  When I pulled down this project locally it did work for me using the same test files.  I am running the latest version of Windows 10.  

## Details

If necessary, describe the problem you have been experiencing in more detail.

Don't forget to include ATL.Logging.Log and/or console output

## Code To Reproduce Issue [ Good To Have ]
My project is here: [https://github.com/mattjopete/chaptifier](https://github.com/mattjopete/chaptifier)

ATLMetadataService.cs
`public MetadataModel Read(string filePath)`
`{`
    `Track track = new Track(filePath);`
    `return track.ToMetadataModel();`
`}`

MainPage.xaml.cs
`private void ReadMetadata(StorageFile file)`
`{`
    `var metadata = MetadataService.Read(file.Path);`
`}`

TrackExtensions.cs
`public static MetadataModel ToMetadataModel(this Track track)`
`{`
    `return new MetadataModel`
    `{`
         `Title = track.Title,`
          `ShowNotes = track.Description,`
           `Chapters = track.Chapters.ToChapterModel()`
     `};`
 `}`

ChapterExtensions.cs
`public static IEnumerable<Models.ChapterModel> ToChapterModel(this IEnumerable<ChapterInfo> chapters)`
`{`
    `var chapterCollection = new List<Models.ChapterModel>();`
     `foreach(var chapter in chapters)`
     `{`
         `chapterCollection.Add(new Models.ChapterModel`
         `{`
             `Title = chapter.Title,`
              `StartTime = chapter.StartTime,`
              `EndTime = chapter.EndTime,`
              `Picture = Image.FromStream(new MemoryStream(chapter.Picture.PictureData))`
           `});`
       `}`
    `return chapterCollection;`
`}`

**Comment by Zeugma440** [comment]
Hi @mattjopete,


First of all, thanks for your interest in ATL.NET !

Right now I see no reason why ATL would be compiling, but not working as a nuGet library.

Let's start with the obvious stuff (I'll be damned if I don't ask) :
- Have you checked output console for any message or exception ?
- Have you activated the ATL logging system ? If not, the easiest way to go is :

1/ Copy/paste `ConsoleLogger.cs` from the `ATL.benchmark` project to your project
2/ At initialization time, call `ConsoleLogger log = new ConsoleLogger();`
3/ That's it ! Console output now logs ATL activity, which should hopefully help us see what's going wrong


Thanks in advance for the feedback

Cheers,
~Z440

**Comment by mattjopete** [comment]
I've been doing a bit more digging on this and enabling the ATL logging just reaffirmed what I found on my own. The exception being thrown is 

> Exception thrown: 'System.UnauthorizedAccessException' in System.Private.CoreLib.dll

Testing outside of the ATL library shows that I basically cannot open a file stream outside of the project directory unless I do something like this.
`StorageFile file =  await picker.PickSingleFileAsync();`
`var stream = await file.OpenAsync(FileAccessMode.ReadWrite);`

**Comment by mattjopete** [comment]
Since I already have the stream from putting the file into an audio player, I might be able to use the other enhancement you are working on to get around this issue.  I just need to figure out how to get the mimeType but that shouldn't be too hard using the file extension.

**Comment by Zeugma440** [comment]
Awesome. The new constructor for `Track` would indeed do the work.

Don't hesitate to use it right now; it is working and awaiting approval from the OP of the other issue.

Concerning the MIME-type, the library could allow the file extension to be passed instead of the MIME-type. That would definitely be easier for people like you who already know their file extension.

For instance, to read an mp3 file with a `Stream` as input, the 2nd argument of the constructor would be either `audio/mp3` or `.mp3`. How about that ?

**Comment by Zeugma440** [comment]
That's done anyways. You can either initiate a Track by calling

`Track t = new Track(yourStream, "audio/mp3");` or `Track t = new Track(yourStream, ".mp3");`

I'm pushing that to nuGet today. Please let me know if everything's fine on your side.

**Comment by Zeugma440** [comment]
Almost a month without any news. Let's consider it solved ! If not, please prove me wrong by reopening this issue.

**Comment by mattjopete** [comment]
This new method works great for reading chapter data.  Thank you

**Comment by mattjopete** [comment]
I do have one question.   How can I read image data in the chapters? It seems like when the Track is created it should be reading the embedded pictures instead of ignoring them.  Maybe an overload that lets users decide if they want to read the image data from chapters?

**Comment by Zeugma440** [comment]
There is an undocumented behaviour that loads pictures into chapters when accessing the `Track.EmbeddedPictures` property. Just call that property and your chapters will have their images loaded !

For a practical example, see the `TagIO_RW_ID3v2_Chapters_Existing` method of the `ID3v2.cs` unit test file (it uses `AudioDataManager` instead of `Track`, but the overall behaviour is exactly the same)

NB : Only images from ID3v2 chapters are currently supported by ATL. I hope that fits your needs.

**Comment by mattjopete** [comment]
That did it for me.  Thanks.  I somehow missed that calling that repopulated the chapter image info.

**Comment by Zeugma440** [comment]
It was far from obvious anyway. Might add a specific parameter to the contructor so make that more intuitive.
