### ISSUE TITLE
Development Issue: Failing unit tests on macOS - Something messed up with paths?

### ISSUE THREAD

**Issue by sandreas** [Zeugma440/atldotnet#131]
## The problem
Hey there, 

I forked the repo for preparing PRs and tried to run the unit tests first. Unfortunately, some of them failed (only in `/ATL.test/Playlist/`), 

At this line:
https://github.com/Zeugma440/atldotnet/blob/fe5c295420cd11c6cafe4eefd53b9252baacb9e1/ATL.test/Playlist/ASXIO.cs#L25

the debugger shows the following value for `s` (Path):

```
/Users/<myusername>/Projects/atldotnet/ATL.test/Resources/_Playlists/\\users\<myusername>\Projects\atldotnet\ATL.test\Resources\FLAC\empty.flac
```

So something is wrong with the path generation.

## Environment

* git `master`
* `macOS 10.15.7`
* `JetBrains Rider` as IDE

Is this my fault?

Other strange things I found:
- Theres a bogus symlink `ATL.nuspec` in my project
- On Linux when using `dotnet --version: 6.0.201`, some project parts complain to be `4.8` and cannot be run

**Comment by Zeugma440** [comment]
Interesting. Both CI and my dev device run Windows and complete all tests successfuly. I wonder if that issue is related to macOS.

**Comment by sandreas** [comment]
Ok, I'll try it on windows and check, if I can fix it - otherwise I'll ignore it for now. Thx for the quick feedback.

**Comment by Zeugma440** [comment]
btw, I hope you're not working on ogg. I'm in the middle of a major rewrite.

**Comment by Zeugma440** [comment]
Looks like your issue is on `PlaylistIO.decodeLocation`, lines 258 to 261.

I think `System.IO.Path.IsPathRooted` is returning `false` whereas it definitely should return `true`.

Could you debug line 257 and 258 and tell me the value of `href` on both lines ?

https://github.com/Zeugma440/atldotnet/blob/fe5c295420cd11c6cafe4eefd53b9252baacb9e1/ATL/Playlist/PlaylistIO.cs#L257

**Comment by sandreas** [comment]
> btw, I hope you're not working on ogg. I'm in the middle of a major rewrite.

Nope, currently I'm just experimenting  with improving some of the existing classes supporting switch expressions, LINQ while trying to understand code, tests and so on. E.g.:

```c#
        public String Title
        {
            get
            {
                String title = "";
                foreach (IMetaDataIO reader in metaReaders)
                {
                    title = reader.Title;
                    if (title != "") break;
                }
                return title;
            }
        }
```
to
```c#
        public string Title => metaReaders.FirstOrDefault(r => r.Title != "")?.Title ?? "";
```

I would love to have `nullable` in the project properties, but like I said, it will take some time to make well thought PRs.


> Could you debug line 257 and 258 and tell me the value of href on both lines ?

I'll try to fix it and make a PR - will take some time, in the next days I may be busy.

**Comment by sandreas** [comment]
Short update: The Problem seems to be in `TestUtils.CopyFileAndReplace`... it creates `playlist_test.asx` with invalid contents (four slashes). I'm on it.

```xml
<ASX VERSION = "3.0">
	<TITLE>Title</TITLE>
	<ENTRY>
		<REF HREF = "file:////Users/sandreas/Projects/atldotnet/ATL.test/Resources/FLAC/empty.flac" />
	</ENTRY>
        <!-- ... -->
</ASX>
```

**Comment by Zeugma440** [comment]
Thanks a bunch ! Looks fine, altough I'm not super keen on loosely-typed variable declarations (`var`). Reminds me too much of the living hell that is VB 😅

**Comment by sandreas** [comment]
> Thanks a bunch ! Looks fine, altough I'm not super keen on loosely-typed variable declarations (var). Reminds me too much of the living hell that is VB 😅

You're welcome! If you don't like `var` that much, I'll use the full declarations in the next PRs. I like `var` because it saves me time on writing and refactoring stuff and because JetBrains leaves a hint that this should be refactored...

If there is anything I could help you with let me know, I think that I now understand the code better.

**Comment by Zeugma440** [comment]
> If there is anything I could help you with let me know, I think that I now understand the code better.

Well, maybe you could add a couple missing fields as you described in #121 ?
