### ISSUE TITLE
save()  will be rewrite the mp4 file 's all data  to a file.it is not edit the mp4 .

### ISSUE THREAD

**Issue by interiv** [Zeugma440/atldotnet#136]
## The problem

using OpenCvSharp;

foreach (var item in Directory.GetFiles(@"C:\Users\inter\Desktop\3年级数学秋季 龚小宝\", "*.mp4"))
{
    var v = VideoCapture.FromFile(item);
    var img=new Mat();
    v.Read(img);
  //  img.SaveImage(item.Replace(".mp4", ".jpg"));

  //  var imgFile = item.Replace(".mp4", ".jpg");

  var bytes=  img.ToBytes();
    //以byte[]读取图片
  //  var bytes=System.IO.File.ReadAllBytes(imgFile);

    var t = new ATL.Track(item);

    var pic = new ATL.PictureInfo(ATL.PictureInfo.fromBinaryData(bytes));
    pic.PicType = ATL.PictureInfo.PIC_TYPE.Front;
    pic.NativeFormat = Commons.ImageFormat.Png;
    t.EmbeddedPictures.Clear();
    t.EmbeddedPictures.Add(pic);
    t.Save();
    //----------------------------------
    //save will be rewrite a file 's all data.it is not edit it.

}

Cv2.DestroyAllWindows();

**Comment by interiv** [comment]
use my code ,edit some big mp4 files ,you will know .save them is use many times

你可以比较一下如下代码, 用这个库,操作修改封面 covr 非常快.

不用把文件全部重新写到硬盘上一次.只是修改了一小部分.

`import io

from mutagen.mp4 import MP4, MP4Cover

from PIL import Image
import cv2
import glob
import sys

argv = sys.argv
list = []
# 如果argv不为空,并且由mp4结尾，则加入列表
if len(argv) > 1:
    if argv[1].endswith('.mp4'):
        list.append(argv[1])
    else:
        list = glob.glob(argv + R"\*.mp4")
else:
    print("1,请输入mp4文件名作为参数,如:" + argv[0] + " test.mp4 \n")
    print("2,请输入mp4所在文件夹路径作为参数,如:" + argv[0] + " d:\\目录 \n")
    sys.exit(0)

#这个函数是直接把图片读取到内存中，然后转换成二进制,写入到mp4文件中做封面
def addCover(filename, cover):
    audio = MP4(filename)
    data = open(cover, 'rb').read()
    covr = []
    if cover.endswith('png'):
        covr.append(MP4Cover(data, MP4Cover.FORMAT_PNG))
    else:
        covr.append(MP4Cover(data, MP4Cover.FORMAT_JPEG))
    audio['covr'] = covr
    audio.save()
    print(filename + " 内嵌图片：" + cover + "。")


#这个是直接把bytes写入到mp4文件中做封面
def addCover2(filename, data):
    audio = MP4(filename)
    data = data
    covr = []
    covr.append(MP4Cover(data, MP4Cover.FORMAT_JPEG))

    audio['covr'] = covr
    audio.save()

#循环遍历文件夹下的mp4文件
for i in list:
    img = cv2.VideoCapture(i)
    _, data = img.read()
    data2 = io.BytesIO()
    #图片转tytes,然后写入到mp4文件中
    Image.fromarray(data, 'RGB').save(data2, format="JPEG")
    addCover2(i, data2)
`

**Comment by interiv** [comment]
your code .
it will take a lot time

**Comment by interiv** [comment]
[修改mp4封面.log](https://github.com/Zeugma440/atldotnet/files/8653663/mp4.log)

take a look this py file

**Comment by interiv** [comment]
其实你可以参考一下 那个python 库的源代码.同样的一个文件,他的速度确实很快.他那个应该是只是修改了一下文件,只是保存了修改的部分.并不是整个文件重新写入磁盘的.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Zeugma440/atldotnet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月10日(星期二) 凌晨2:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Zeugma440/atldotnet] save()  will be rewrite the mp4 file 's all data  to a file.it is not edit the mp4 . (Issue #136)





 
Ah, I get it. Technically speaking, MP4 is a complex format that sometimes requires more than just adding a chunk of data in the middle of the file.
 
Did you read this ? https://github.com/Zeugma440/atldotnet/wiki/4.-FAQ-(Frequently-Asked-Questions)#FAQM.5
 
If neither of these two solutions work, could you send me the MP4 file you're working with ?

**Comment by Zeugma440** [comment]
Could you please make the effort of posting a translated reply ?

Other people may be interested by what we're talking about.

Thanks for your understanding.

**Comment by Zeugma440** [comment]
No reply from the OP for 30 days => closed
