### ISSUE TITLE
Garbled code System.Text.GB18030Encoding

### ISSUE THREAD

**Issue by melinyi** [Zeugma440/atldotnet#138]
Hi, I found a garbled encoding format when I parsed the cue file

ATL.CatalogDataReaders.CatalogDataReaderFactory.GetInstance().GetCatalogDataReader();

![image](https://user-images.githubusercontent.com/83648656/169052753-1c6f4aad-ec26-4dc9-a255-6016a7286dc4.png)

**Comment by melinyi** [comment]
PERFORMER "周華健"
TITLE "最後圓舞曲"
FILE "CDImage.ape" WAVE
  TRACK 01 AUDIO
    TITLE "最後圓舞曲"
    PERFORMER "周華健"
    FLAGS DCP
    INDEX 00 00:00:00
    INDEX 01 00:00:01
  TRACK 02 AUDIO
    TITLE "平凡的感覺"
    PERFORMER "周華健"
    FLAGS DCP
    INDEX 01 05:56:62
  TRACK 03 AUDIO
    TITLE "結"
    PERFORMER "周華健"
    FLAGS DCP
    INDEX 01 09:49:42
  TRACK 04 AUDIO
    TITLE "鐘聲"
    PERFORMER "周華健"
    FLAGS DCP
    INDEX 01 13:53:13
  TRACK 05 AUDIO
    TITLE "蛻"
    PERFORMER "周華健"
    FLAGS DCP
    INDEX 01 17:28:03
  TRACK 06 AUDIO
    TITLE "短歌(紀念已逝的約翰.藍儂)"
    PERFORMER "周華健"
    FLAGS DCP
    INDEX 01 21:37:49
  TRACK 07 AUDIO
    TITLE "雨中的溫馨"
    PERFORMER "周華健"
    FLAGS DCP
    INDEX 01 25:50:65
  TRACK 08 AUDIO
    TITLE "夜深人靜"
    PERFORMER "周華健"
    FLAGS DCP
    INDEX 01 30:24:02
  TRACK 09 AUDIO
    TITLE "夢裏的中國(三部曲) 沈思/入眠/驚醒"
    PERFORMER "周華健"
    FLAGS DCP
    INDEX 01 34:09:54

**Comment by Zeugma440** [comment]
That's super interesting, thanks for your feedback.

Could you please upload the original cue file in a ZIP archive ?  I'd need to analyze it directly. Thanks.

**Comment by melinyi** [comment]
OK，I've already uploaded the file

**Comment by Zeugma440** [comment]
As the CUE format specs don't define or restrict to any encoding, the library will have to _guess_ it.

I was planning on using the .NET port of Ude (https://github.com/yinyue200/ude) to do that, as it supports GB18030 and is entirely written in C#.

**Comment by Zeugma440** [comment]
Done for next release

**Comment by Zeugma440** [comment]
Available in today's v4.06.
