### ISSUE TITLE
Add a PotPlayer playlist

### ISSUE THREAD

**Issue by melinyi** [Zeugma440/atldotnet#140]
tag info

Hearder：
       DAUMPLAYLIST
       topindex = 0 
       saveplaypos = 0  //enable Save Postion 0 or 1
       playname  = i\*file* // last play  i\*file\* 
       playtime = 0 //Playback Progress (ms)

Body：
          i\*file\* Url  or FilePath
          i\*title\* Title Name
          i\*duration2\*1000  //duration (ms)
          i\*start\*1000  //last play postion(ms) ,need Hearder saveplaypos=1
          i\*played\*1  //isPlayed  Was over
    

file content

DAUMPLAYLIST
topindex=0
saveplaypos=1
url or filePath 2
0
1\*file\*url or filePath 1
1\*title\*Title 1
1\*duration2\*500
1\*start\*100
1\*played\*1
2\*file\*url or filePath 2
2\*title\*Title 2
2\*duration2\*500
2\*played\*1
3\*file\*url or filePath 3
3\*title\*Title 3
3\*duration2\*500
3\*played\*1
4\*file\*url or filePath 4
4\*title\*Title 4
4\*duration2\*500
4\*start\*150
4\*played\*1
5\*file*url or filePath 5
5\*title\*Title 5
5\*duration2\*500
5\*start\*300
5\*played\*1

**Comment by melinyi** [comment]
my code [Dlp.cs](https://github.com/melinyi/PlayListGenerateLib-Shared/blob/main/Dlp.cs)

**Comment by Zeugma440** [comment]
Alright, thanks for the suggestion !

**Comment by Zeugma440** [comment]
Done for next release

**Comment by Zeugma440** [comment]
Available in today's v4.06.
