### ISSUE TITLE
BUG  Whether the file is occupied is not judged when saving

### ISSUE THREAD

**Issue by melinyi** [Zeugma440/atldotnet#141]
It doesn't seem to judge whether the music file is occupied when saving the music information。

When I modify the information of the music being played, there is no indication of any abnormality, and the music of the player becomes noise And then no response

In TagLibSharp will prompts you to throw an exception

**Comment by melinyi** [comment]
Player ： https://github.com/unosquare/ffmediaelement

**Comment by Zeugma440** [comment]
Done for next release.

Thanks for bringing this up - I've been misinterpreting the `FileShare` parameter when opening files.

**Comment by Zeugma440** [comment]
Available in today's v4.06.
