### ISSUE TITLE
Thank you for your awesome library!

### ISSUE THREAD

**Issue by sandreas** [Zeugma440/atldotnet#146]
I just wanted to say thank you for your hard work. Maybe this is not gonna help you, but I thought it would be nice to know, that it is being used in one of my actual projects:

https://github.com/sandreas/tone

It is an open source, cross platform tagging tool for audio files and the first early state version `0.0.1` was published today.

Keep up the good work - if you did read this, you can close this issue ;)

**Comment by Zeugma440** [comment]
Thank you man 😄   And congrats for that first release !

If you want to leave a lasting feedback, you may use [Discussions](https://github.com/Zeugma440/atldotnet/discussions)
