### ISSUE TITLE
MP4 tagging for `movement` - wrong endianness?

### ISSUE THREAD

**Issue by sandreas** [Zeugma440/atldotnet#150]
## The problem

Using the `AdditionalFields` in Track for `MP4` files to tag the value for `©mvi` (***Movement***, [usually stores the audiobook part index of a series as int16s](https://exiftool.org/TagNames/QuickTime.html)) shows strange results in iTunes, if the provided number is > 127. 

Here are some values and the result in iTunes:

```
1 => 1
5 => 5
127 => 127
128 => 65408
255 => 65535
256 => 1
257 => 257
258 => 513
288 => 8193
```

Other tagging utilities also behave strange, for `146` the `exiftool` shows `-110`. 

Switching the *endianness* of numbers seems to solve this problem. For quick testing here is a JavaScript snippet, that can directly be tested in any browser:

```js
var num = 146;
var swapped = (num>>8) | (num<<8);
console.log(swapped); // 37376
```

Setting `AdditionalFields["©mvi"] = "37376";` works and shows the correct value `146` in iTunes.

Is this a bug or a misinterpretation of the specs from apple / others?

The following issues currently occur on `©mvi`:
- Using values > 127 result in wrong displayed values in some other utilities (see above)
- `0` as string value is not stored (`AdditionalFields["©mvi"] = "0";` - `0` is often used for prequels or first parts of audio books)
- Non-integer-like string values (e.g. `2.1` or `1.5` or `hello`)  result in an exception, because `int.Parse...` fails (see https://github.com/sandreas/tone/blob/30dc753c6f99ee91537e1cbc36f360c565409f10/tone/Metadata/MetadataTrack.cs#L315)

**Comment by sandreas** [comment]
First I wanna thank you for being so responsive and cooperative, this really motivating and makes me love your project even more. I learned a lot from our discussions :-)

> This will be fixed on next release.

Awesome, thank you. I'm not sure, but would negative values also be possible? int16s means signed, doesn't it? 

> Not possible right now as 0 is used as a convention for "nonexistent" integer values.

Ok, maybe this was a false report. Could you point me to a part of the code, where that is checked?

- `0 `  is stored somehow (0[space]), although not a valid integer, which seems a bit strange, I wonder what happens in the binary ;-)
- `00` is also stored
- `000` is also stored
- `0001` is also stored
- `-1` throws an exception, although it is a valid integer

I have to investigate this again.

> Well, you did provide an invalid value where an int was expected. What's the behaviour you'd expect here ?

This is more like a thing to put up for discussion. `AdditionalFields` in `Track` is `<string, string>` (not `<string, object?>` what I would have expected) and does not have any restrictions or validation mechanisms... Nullable would maybe solve the problem with `0` not beeing available for `©mvi`, because `null` could be used as a convention for "nonexistent" whatever values.

The question is, if invalid or null values should be ignored silently, throw an exception or provide a callback method to handle them (for flexibility). I don't know what is to your liking. Currently, this is not a real problem to me personally, because I already can validate and ignore invalid values. It is just a little Code Smell.

**Comment by Zeugma440** [comment]
> First I wanna thank you for being so responsive and cooperative, this really motivating and makes me love your project even more. I learned a lot from our discussions :-)

You're very welcome :)  I've also learned a lot from the use cases you've been describing. MP4/M4A is a remarkable container - simple in its structure yet very versatile in its uses.


> I'm not sure, but would negative values also be possible? int16s means signed, doesn't it?

Yes it does... which is another issue I need to fix as well, as ATL assumes all integers using type code `21` are unsigned, while they actually aren't (see [Apple specs](https://developer.apple.com/library/archive/documentation/QuickTime/QTFF/Metadata/Metadata.html#//apple_ref/doc/uid/TP40000939-CH1-SW35))

Btw, I wonder how a movement number /index would end up being negative. When used to describe a prequel ?


> atldotnet seems to write the 0 fine.

I've answered a bit too fast on that one, sorry. As `AdditionalFields` stores values as `string`, and the nonexistent value for strings is `""`, `"0"`  is considered valid, and saved accordingly. `0` as a nonexistent value was an old convention used with `int` values before `Track` uses nullable fields for non-`string` values.


> AdditionalFields in Track is <string, string> (not <string, object?> what I would have expected)

Granted. That could become the next step to making ATL a little smarter. I won't do that right now, but I'm gonna keep the idea alive in case it helps solving other issues.


> The question is, if invalid or null values should be ignored silently, throw an exception or provide a callback method to handle them (for flexibility). I don't know what is to your liking.

So far, the library has been designed to facilitate large scale operations (i.e. cataloging, mass-renaming...), i.e. processing thousands of files without worrying about the whole thing crashing down at the first invalid value/file.

As such, exceptions have always been :
- catched internally
- logged using ATL.Log (see https://github.com/Zeugma440/atldotnet/wiki/2.-Software-Architecture#logging)

For consistency's sake, I guess I'm gonna do the same here (mute the exception, skip that field and log the issue using `warning` level).

**Comment by sandreas** [comment]
> Yes it does... which is another issue I need to fix as well, as ATL assumes all integers using type code 21 are unsigned, while they actually aren't (see [Apple specs](https://developer.apple.com/library/archive/documentation/QuickTime/QTFF/Metadata/Metadata.html#//apple_ref/doc/uid/TP40000939-CH1-SW35))

Great, thank you :-)

> Btw, I wonder how a movement number /index would end up being negative. When used to describe a prequel ?
> ...
> So far, the library has been designed to facilitate large scale operations (i.e. cataloging, mass-renaming...), by allowing to process thousands of files without worrying about the whole thing crashing down at the first invalid value/file.

Yeah I thought that. Audio book metadata is kind of weird in any possible way. I'm from germany, so there is even more weirdness after wrong translations, renaming complete series over time, changing genre or switching to other narrators or even authors in between. Usually I tend to order my audio books like this:
```
/<genre>/<authors>/<series>/<movement> - <title>.m4b
/<genre>/<authors>/<title>/<title>.m4b
```
In some audio books with more than 150 parts, the AUTHORS switch over time. This is really annoying, because audio book series are separated over more than one subfolder.  I used `mp4v2` in the past, but thanks to atldotnet this is not necessary any more... I thought:  I'm gonna make my own audio metadata tool, with blackjack and hookers ;-) Now, since [tone](https://github.com/sandreas/tone) is out and capable of tagging by path name, renaming series is no more a problem:

```
# tags all my audiobooks with genre, authors, movement-name, movement and title from path name
tone tag --path-pattern="audiobooks/%g/%a/%s/%p - %n.m4b" --path-pattern="audiobooks/%g/%a/%z/%n.m4b" audiobooks/ 
```

I personally solved the NON-INTEGER movement situation by defining a Property `Part`, a custom `mp4` tag `----:com.pilabor.tone:PART` as string providing a fallback to `Movement`, which works pretty well:
https://github.com/sandreas/tone/blob/bd975efdcf161151a36da6f54e7293dae61ca0fe/tone/Metadata/MetadataTrack.cs#L67
https://github.com/sandreas/tone/blob/bd975efdcf161151a36da6f54e7293dae61ca0fe/tone/Metadata/MetadataTrack.cs#L153

I think we are on the same wavelength about most things and I look forward to the next release. 

***There is one more thing:***
Do you prevent modifying files on `Track.Save`, if the metadata has not changed? (Is there a *dirty* flag in `Track`?). If not, this would make mass processing even faster in my case.

**Comment by sandreas** [comment]
> Okay, all done for integer conversions and logging instead of crashing. Will be available on next release.

Mmh, so far it did not work with the new release (4.0.7), same errors. I'll reinvestigate this and if the problem persists I'll reopen the ticket, ok?

**Comment by Zeugma440** [comment]
Sure. 
Please be specific about what's wrong if you do so.

**Comment by sandreas** [comment]
> Mmh, so far it did not work with the new release (4.0.7), same errors. I'll reinvestigate this and if the problem persists I'll reopen the ticket, ok?

False alarm, it seems to work. Was a bit unsure, because READING the wrong endian value resulted in value "not changed", although the value in the file is 65419 and the read value is 139...
What ever that is.
