### ISSUE TITLE
mp4 description tag

### ISSUE THREAD

**Issue by thscott** [Zeugma440/atldotnet#153]
Should the mp4 description tag `@des` introduced in 04fcecd actually be `©des`?

The latter is what I've encountered before in files, and is also documented by exiftool [here](https://exiftool.org/TagNames/QuickTime.html#ItemList).

**Comment by Zeugma440** [comment]
Oops <.<

Thanks for pointing to that. I'll get it fixed this week-end.

**Comment by Zeugma440** [comment]
Fixed in today's v4.08
