### ISSUE TITLE
Saving the Tag is squishing Exceptions and reporting no Issue

### ISSUE THREAD

**Issue by CooPzZ** [Zeugma440/atldotnet#159]
## The problem

I was playing around the ATL Library on editing tags for M4Bs and with the properties editor in windows explorer and randomly changed the Parental Guardian field.
![image](https://user-images.githubusercontent.com/3201497/180703650-d52a3412-db94-46df-9214-f812837ade87.png)

## Environment

* 4.9.0.0
* Windows 10.

## Details

Then when updating the tags using ATL after I had changed Parental Guardian field, it was failing to save the tag (with no exceptions) and found while debugging that an exception was being squished.  The error was on WM/ParentalRating is too long and cannot be written. refer to Pics
![image](https://user-images.githubusercontent.com/3201497/180703544-a537ab1c-1b9c-4438-aea9-9d845cf82fdd.png)
![image](https://user-images.githubusercontent.com/3201497/180704177-57faded5-a0bd-4419-829e-289d380cf19e.png)
As the result flag is defaulting to true, and the exception is caused inside the Write - you also think that it was successful as it can't change to false.

I'm ok with it not really supporting the tag - I'm just not sure if the exception should be squished or not, however as it failed to save the Tag but I had no idea why, some sort of message needs to be set?

## Code To Reproduce Issue

Simple update to a tag with the "Parental Guardian" field set and save.

**Comment by Zeugma440** [comment]
Hey there ! Still on another project for now, but I've tagged both issues for processing.

I'll get back to you soon. Thanks for your understanding.

**Comment by Zeugma440** [comment]
Thanks to your report, I realized non-standard fields weren't properly supported in MP4/M4A. I've improved that and wrote a memo along the way : https://github.com/Zeugma440/atldotnet/wiki/Focus-on-non-standard-fields

Could you grab the latest commit from `main` and confirm everything works fine on your end ? 

Thanks~

**Comment by CooPzZ** [comment]
That seemed to help - on playing around with the fields - I note Publisher doesn't match with the ATL publisher, 
I was also getting a simular issue to what I think it was doing the other issue I've logged.
Cheers.

**Comment by Zeugma440** [comment]
Nice, thanks for the feedback.

So the initial issue is fixed and now we have to investigate the Publisher field ? Are you talking about the one filled by Windows File Explorer ?

**Comment by CooPzZ** [comment]
Yes and No, only if you want the ATL.Track.Publisher to be mapped to the Windows explorer one too. 
I say it in this way as I'm not fully sure of all the intentions of the Wrapper Track class yet.
Otherwise you are probably fine to close this issue.

**Comment by Zeugma440** [comment]
If iTunes and Windows use the same field, it will be remapped. If not, iTunes takes precedence.

Track is the "user-friendly" go-to class you should use for basic operations. Advanced operations should use lower level classes.

Fields such as Publisher are mapped at the lowest level of the library. From there on, information"bubbles up" to Track.

**Comment by CooPzZ** [comment]
Thanks - this comment could be useful in some form to add to the header comment of the Track class for future understanding into the intentions - and to have your reason clear not to deviate from it, well not to far. 8)

**Comment by Zeugma440** [comment]
I've just confirmed that Windows File Explorer saves the Publisher field in M4B's with its very own `WM/Publisher` field code, inside its very own `Xtra` atom.

I suspect Microsoft does the same lazy trick with any audio format deemed too complex to dive into. This deserves a Github issue on its own. For now, you may find these pieces of information using `AdditionalFields`.

Last but not least, as for the initial issue, the fix will be published in the next release of ATL.

**Comment by Zeugma440** [comment]
Released in today's v4.10
