### ISSUE TITLE
ID3 : frames in UTF-8 are not compliant with ID3 v2.3 

### ISSUE THREAD

**Issue by Ja-mi** [Zeugma440/atldotnet#16]
## The problem

ID3v2.3 frames written by atldotnet in UTF-8 are not compliant with ID3v2.3 standard.
As a consequence, unicode character are not correctly displayed in players like foobar2000 or windows file explorer (see screenshot below).

## Environment

* ATL version (or git revision) that exhibits the issue: z440.atl.core.2.5.0.nupkg
* Last ATL version that did not exhibit the issue (if applicable):  ?
* OS/version used to run ATL  : Windows 7 and Powershell 5.1

## Details

ID3 v2.3 standard states :
"All Unicode strings use 16-bit unicode 2.0 (ISO/IEC 10646-1:1993, UCS-2). Unicode strings must begin with the Unicode BOM ($FF FE or $FE FF) to identify the byte order.
(...)
Frames that allow different types of text encoding have a text encoding description byte directly after the frame size. If ISO-8859-1 is used this byte should be $00, if Unicode is used it should be $01."

cf. http://id3.org/id3v2.3.0#ID3v2_frame_overview

## Code To Reproduce Issue [ Good To Have ]

Import-Module .\net30\ATL.dll

[string]    $fileName = "test.mp3"
[ATL.Track] $theTrack = New-Object ATL.Track $fileName
$theTrack.Title = "Titre accentué par ATL"
$theTrack.Save()

![utf error foobar](https://user-images.githubusercontent.com/6505880/46411017-f9462100-c71a-11e8-8361-5379491fef6d.png)

![win explorer error](https://user-images.githubusercontent.com/6505880/46412206-20522200-c71e-11e8-8418-8897f1a111bb.png)

**Comment by Zeugma440** [comment]
Hello @Ja-mi 


First and foremost, thank you for your interest in ATL.NET !

ATL has been designed to comply with the ID3v2.4 standard only, hence the use of UTF-8 strings. I'm quite surprised to read that ID3v2.3 headers have been actually written by ATL.

I'll try and reproduce the issue and keep you informed.


Best regards,
~Z440

**Comment by Zeugma440** [comment]
Maybe you could provide me with the resulting file (the one you tried to read with foobar2000) so that I examine it ?

**Comment by Zeugma440** [comment]
Unfortunately, I haven't been able to reproduce this issue.

Could you send me the edited file, please ?

**Comment by Ja-mi** [comment]
Thank for your support.

You are right, ID3 tags written are v2.4.
I have not noticed that before you told me. I incorrectly assumed ATL writes ID3v2.2, 2.3 or 2.4 depending on original tag version.

Knowing that, I made some additional tests and found that it is a powershell bug indeed and it is not an ATL issue.
When the powershell script file misses an UTF-8 Byte-Order Mark, Powershell interpreter does not provide correct strings to ATL.

I provide anyway the small mp3 test file and scripts anyway.
[Reproducing the issue.zip](https://github.com/Zeugma440/atldotnet/files/2452973/Reproducing.the.issue.zip)

**Comment by Zeugma440** [comment]
Supporting v2.4 only is a position that has not caused any issue so far. I do not plan to add support for v2.2  / v2.3 writing unless someone provides me a good reason to do so.

Thanks for investigating anyway. Is there something I can do for you, or can we consider this issue solved ?

**Comment by Ja-mi** [comment]
Yes, issue solved !

**Comment by Zeugma440** [comment]
@Ja-mi for your information, ATL is now able to write ID3v2.3 frames by setting `Settings.ID3v2_tagSubVersion = 3` before saving your `Track`

The feature will be published very soon to NuGet as v2.8
