### ISSUE TITLE
Async support - Custom BinaryWriter

### ISSUE THREAD

**Issue by Zeugma440** [Zeugma440/atldotnet#162]
Try writing a custom, async-compatible BinaryWriter with the same API as the standard one

**Comment by CooPzZ** [comment]
In case you missed it - someone had done it in the thread you referenced, although I don't know if it will work and has what you'll need.
https://github.com/ronnieoverby/AsyncBinaryReaderWriter

**Comment by Zeugma440** [comment]
Yup, I've seen it (5 years old, unanswered issues, no NuGet artifact...)

I got more than enough in `StrramUtils` to make my own, tbh. If I do go that way, I'll have to benchmark a couple variants to see which one performs better.

Right now I'm reducing the library's dependency to `BinaryWriter` by replacing it with `Stream` when possible. Results are _very_ encouraging.

**Comment by Zeugma440** [comment]
After refactoring, `Stream` is available where we need it most, i.e. when file is being resized.

`BinaryWriter` is only used locally when needed to write bytes where they belong.

=> Writing a custom, `async`-compatible `BinaryWriter` is no longer required to implement `async` support.
