### ISSUE TITLE
Tagging m4b is changing the timebase

### ISSUE THREAD

**Issue by sandreas** [Zeugma440/atldotnet#166]
## The problem

If I use `Track` to tag an `m4b` file, this changes the chapters somehow. This issue was reported originally by @advplyr for my project `tone`, [see here for details](https://github.com/sandreas/tone/issues/32).

The following fields are changed:
- chapter timebase
- chapter times (this is really bad, because it shifts chapter times!)
- the release date?

## Environment

* ATL 4.11
* Ubuntu 18.04 LTS

## Code To Reproduce Issue

Download [the file](https://raw.githubusercontent.com/advplyr/node-tone/master/samples/TimebaseSample.m4b) 

Run this code

```c#
        var source = "TimebaseSample.m4b";
        var destination = "TimebaseSample_tbchanged.m4b";
        if (File.Exists(destination))
        {
            File.Delete(destination);
        }
        File.Copy(source, destination);
        var t = new Track(destination);
        t.Title = "Hello world";
        t.Save();
```

Compare `TimebaseSample.m4b` and `TimebaseSample_tbchanged.m4b` via:

```bash
ffprobe -i TimebaseSample.m4b -show_chapters -print_format json
ffprobe -i TimebaseSample_tbchanged.m4b -show_chapters -print_format json
```

Diff:
```diff
12c12,13
< Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'TimebaseSample.m4b':
---
> [mov,mp4,m4a,3gp,3g2,mj2 @ 0x655efc0] Referenced QT chapter track not found
> Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'TimebaseSample_tbchanged.m4b':
17c18
<     title           : Armageddon
---
>     title           : Hello world
22,23d22
<     date            : 2019
<     encoder         : Lavf58.73.100
32d30
<     compilation     : 0
33a32,34
>     date            : 2019-01-01
>     encoder         : Lavf58.73.100
>     compilation     : 0
36c37
<     Chapter #0:0: start 0.000000, end 14.043000
---
>     Chapter #0:0: start 0.000000, end 14.043016
39c40
<     Chapter #0:1: start 14.043000, end 393.113000
---
>     Chapter #0:1: start 14.043016, end 393.113016
42c43
<     Chapter #0:2: start 393.113000, end 420.000000
---
>     Chapter #0:2: start 393.113016, end 420.000000
49c50
<   Stream #0:1[0x2](eng): Data: bin_data (text / 0x74786574), 0 kb/s
---
>   Stream #0:1[0x2](und): Data: bin_data (text / 0x74786574), 0 kb/s (default)
51c52,53
<       handler_name    : SubtitleHandler
---
>       creation_time   : 2022-10-17T01:35:07.000000Z
>       handler_name    : Chapter titles
57c59
<             "time_base": "1/1000",
---
>             "time_base": "1/44100",
60,61c62,63
<             "end": 14043,
<             "end_time": "14.043000",
---
>             "end": 619297,
>             "end_time": "14.043016",
68,72c70,74
<             "time_base": "1/1000",
<             "start": 14043,
<             "start_time": "14.043000",
<             "end": 393113,
<             "end_time": "393.113000",
---
>             "time_base": "1/44100",
>             "start": 619297,
>             "start_time": "14.043016",
>             "end": 17336284,
>             "end_time": "393.113016",
79,82c81,84
<             "time_base": "1/1000",
<             "start": 393113,
<             "start_time": "393.113000",
<             "end": 420000,
---
>             "time_base": "1/44100",
>             "start": 17336284,
>             "start_time": "393.113016",
>             "end": 18522000,
```

**Comment by Zeugma440** [comment]
Thanks for reporting.

It's the first time someone uses a file that has a different timescale than the usual 44100 _and_ cares about milliseconds 😄

I'll fix that ASAP and let you know

**Comment by sandreas** [comment]
> It's the first time someone uses a file that has a different timescale than the usual 44100 and cares about milliseconds smile

I'm sorry to be a nitpicker and really grateful that you respect that :-) I think the improvements made to my apps since I found your library made up a whole community of nitpickers trying to achieve perfection... 

> I'll fix that ASAP and let you know

Awesome. I think I'll work more into your library soon and try to help where I can to save your time for the really important stuff ;-)

**Comment by Zeugma440** [comment]
The fix is available in today's v4.13

**Comment by sandreas** [comment]
> The fix is available in today's v4.13

Cool, thanks. If you missed it: I published a "proposal" for an AdvancedTrack API in our discussion. Take your time...

**Comment by Zeugma440** [comment]
Yup, I've received the alert about that one.

I may not have much time to invest on ATL in the coming weeks. I'll keep that in mind, however !

**Comment by sandreas** [comment]
> I may not have much time to invest on ATL in the coming weeks. I'll keep that in mind, however !

Yeah my time is also limited in the coming weeks, so nevermind. There are also issues with nearly every of my open source projects I have to care about and a home server upgrade :-) Cross your fingers that i survive this lol
