### ISSUE TITLE
Track.Description no longer works on mp3 files

### ISSUE THREAD

**Issue by CooPzZ** [Zeugma440/atldotnet#168]
## The problem

Description is no longer available or able to save on mp3 file using Track.

## Environment

* ATL version (or git revision) that exhibits the issue: 4.12

## Details

- No Errors
- Going back to 4.11 it works fine.

**Comment by Zeugma440** [comment]
That one was in the [changelog of v4.12](https://github.com/Zeugma440/atldotnet/releases/tag/4.12)

You can either use `Track.Group` to map `TIT1` back, or use the brand new `Track.LongDescription` that maps to `TDES`

**Comment by CooPzZ** [comment]
Does that mean you are going to drop the Track.Description? 
it currently does nothing for mp3, does it for other file formats?

I also don't see TDES in the ID3 spec?

**Comment by Zeugma440** [comment]
`Track.Description` won't be dropped as it is still mapped on other formats. I can write a quick synthesis if you need it.

> I also don't see TDES in the ID3 spec?

That one is not part of the official standard. It has been added by iTunes to support their need for a "podcast description" field.

It has been suggested in #121, referring to these resources :
- https://github.com/judwhite/IdSharp/pull/1
- https://docs.mp3tag.de/mapping/
- https://wiki.hydrogenaud.io/index.php?title=Tag_Mapping

**Comment by CooPzZ** [comment]
Thanks Zeugma - fair point, and happy with your choice, no need for further information. 

For some thinking time: Like me, I don't know how long you had mapped Description to TIT1, and whether it was right or not and then suddenly not doing anything is weird. My bad is I didn't notice/comprehend in the release and assumed it'd still work as intended, hence spent some time trying to work out if there was an issue.

I understand creating a generic interface for all file types and application mapping is not possible to cover all scenarios.  I'm sure you understand that a change like this can affect many things down the line.  ie: to upgrade now I need to do a code change to support and potentially change all the files with meta that had used this mapping to another.

Cheers.

**Comment by Zeugma440** [comment]
I'm sorry I couldn't maintain retrocompatibility for that one.

I'll be vigilant as to make as few of these decisions as possible.
