### ISSUE TITLE
Playlist reader incorrectly returns URLs as absolute paths

### ISSUE THREAD

**Issue by Aionir** [Zeugma440/atldotnet#174]
When loading a playlist with `GetPlaylistIO`, if the file item is actually a URL, it returns an invalid path/url:

Example:
Loading a playlist: c:\users\someuser\someplaylist.pls

Playlist contents:
```
[playlist]
NumberOfEntries=1
File1=http://uk3.internet-radio.com:8405/live

```
`GetPlaylistIO` will correctly return 1 file, however the output will be:
`c:\users\someuser\http://uk3.internet-radio.com:8405/live
`

When it should just return:
`http://uk3.internet-radio.com:8405/live
`

**Comment by Zeugma440** [comment]
The fix is available on today's v4.14
