### ISSUE TITLE
DTS - error in determining the number of channels?

### ISSUE THREAD

**Issue by Miner-2021** [Zeugma440/atldotnet#177]
## The problem

in the test dts 5 channels are defined, but mediainfo writes that 6. Please check.

**Comment by Zeugma440** [comment]
Hey there,

Thanks a lot for your feedback. It seems the DTS implementation doesn't take a couple things into consideration, among these being the presence of the LFE channel, which explains your issue.

The fix will be available soon. Stay tuned~
