### ISSUE TITLE
Audio format auto-detection

### ISSUE THREAD

**Issue by cocoon** [Zeugma440/atldotnet#178]
## The problem

I just discovered that an m4a-file that has no extension is not processed correctly and no tags could be read.

## Environment

* ATL version (or git revision) that exhibits the issue: 4.17.0 (22.12.2022)
* Last ATL version that did not exhibit the issue (if applicable): na
* OS/version used to run ATL: Windows 11

## Details

Would be great if the lib could try to quick detect the file type with some internal known file headers and maybe as an optional feature to use a third party lib to detect the file type.

Internal header database to keep file size and dependencies low and optional with additional lib.

**Comment by Zeugma440** [comment]
For now, the only way to handle a file without extension is to load it using `Track(Stream stream, string mimeType)`, giving it a MIME-type.

There's no audio format auto-detection, though I can see the value of such a feature. It would require quite a bit of an overhaul to acheive that properly. Keeping that issue to remind me of that.

**Comment by Zeugma440** [comment]
Available in today's v4.21
