### ISSUE TITLE
Channels (mono/stereo) is missing?

### ISSUE THREAD

**Issue by StefH** [Zeugma440/atldotnet#18]
When using `var track = new Track(stream, extension);`, the track does not have info on the number of audio channels?

**Comment by Zeugma440** [comment]
Hello @StefH and thanks for your interest in ATL.NET

That's right, the field does not exist yet... because nobody ever asked for it.

I'll add support for audio channels detection in march.

**Comment by StefH** [comment]
Cool !

Please keep me informed.

**Comment by Zeugma440** [comment]
@StefH what you asked is ready to be used on master branch.

Please check the new `ChannelsArrangement` attribute in `IAudioDataIO` and `Track` and tell me if it works well for your files.

e.g. `int nbChannels = track.ChannelsArrangement.NbChannels;`

If so, I'll push that new update to NuGet.

**Comment by StefH** [comment]
It works perfect for my files, so please release a new NuGet.

**Comment by Zeugma440** [comment]
That's done. [Version 2.6](https://github.com/Zeugma440/atldotnet/releases/tag/v2.6) has just been uploaded to NuGet and is in their validation pipeline atm.

**Comment by StefH** [comment]
Thanks !
I'm using your code in this project : https://github.com/StefH/WebDAV-AudioPlayer

**Comment by Zeugma440** [comment]
Great, and thanks for mentioning ATL.NET on your homepage :-)

Don't hesitate to open other issue if you have new needs. As you've seen, the lib is in a "passive" development phase, but I keep an close eye on it !
