### ISSUE TITLE
Track.Publisher MP3 vs MP4 

### ISSUE THREAD

**Issue by audiamus** [Zeugma440/atldotnet#183]
## The problem

`ATL.Track.Publisher` writes a tag that is correctly recognized when written to MP4 (.m4b, .m4a) but not when written to MP3.

## Environment

* ATL version (or git revision) that exhibits the issue: 4.20
* Last ATL version that did not exhibit the issue (if applicable): 4.4
* OS/version used to run ATL: Any Windows

## Details

Sorry to bother you again, but doing more tests after building against 4.20 I think I detected another tiny issue:

With 4.20, writing `ATL.Track.Publisher`, I get this correctly as "Publisher" with the proper content in MP4 (.m4b, .m4a), but as "pub" in .MP3, apparently more of a custom tag. All analysis according to MediaInfo, MPC-HC and VLC. VLC leaves the "Publisher" field blank for MP3.

With older 4.4, it was more or less the other way round, "Publisher" with the proper content in MP3, but nothing for MP4 (MediaInfo, MPC-HC, VLC) 

I guess "Publisher" is not that standardized but as it was working with MP3 before and now is working with MP4 I presume there might be a way to make it work with both MP3 and MP4 (and possibly others).

## Code To Reproduce Issue [ Good To Have ]

_(Always)_

**Comment by Zeugma440** [comment]
Hi again :)

Are you sure about this ? Code review doesn't reveal any such change between v4.4 and v4.20 :

- ID3v2.2 has been using the `TPB` standard field
- ID3v2.3 and ID3v2.4 have been using the `TPUB` standard field

Writing on an empty MP3 using v4.20 also uses the above fields. MediaInfo, foobar2000 and VLC properly recognize it as the "Publisher" (also called "Editor") field.

If that field is persisted as `pub`, there must be an issue on your side 🤔

**Comment by audiamus** [comment]
You are right, I got my bearings wrong, the issue is with MP4 where I see that "pub" field. ATL 4.4 and 4.20 produce the same "Publisher" fields with MP3 (set to ID3v2.4 when writing ATL.Track). Does this mean that MP4 meta does not have an equivalent for "Publisher"?

**Comment by Zeugma440** [comment]
I don't know what to say... ATL has been tagging MP4s with the `©pub` field for a long time. All the reference I've gathered say that is the correct field to store Publisher metadata. I have no idea why it isn't mapped by the tools we're using.

MediaInfo even seems to ignore it entirely : https://github.com/MediaArea/MediaInfoLib/blob/45d46f7389e6a9db8cebd6a1a98b76d46652e0a8/Source/MediaInfo/Multiple/File_Mpeg4.cpp#L2929

I even reverted the project back to v4.4 to make sure, and I confirm it tags MP4s the same way.

**Comment by audiamus** [comment]
An observation, not sure if of any help:

- MPC-HC and MediaInfo show no sign of any tag related to "Publisher" when the m4b in question is written with my older AAX Audio Converter 1.17.1, linked with ATL 4.4.
- MPC-HC and MediaInfo show "pub" with the given Publisher content when the m4b is written with new AAX Audio Converter 1.18.1, linked with ATL 4.20 and also if downgraded to ATL 4.4.

That's a bit strange because I did not change any code in the area where I host ATL, but I am using a newer version of FFmpeg now, which provides the input file. Nonetheless, all meta should be empty. To cross-check, I explicitly write "TEST" to `Track.Publisher` and it appears as such in MPC-HC and Media-Info: 
`pub                                      : TEST`

**Comment by Zeugma440** [comment]
Do Apple software behave differently?

How can I be of any further help on that one?

**Comment by audiamus** [comment]
> Do Apple software behave differently?

I just tried iTunes. It shows even less meta data.

> How can I be of any further help on that one?

You probably can't. So let's assume, at least for the time being, that a "Publisher" tag is not standardized for the MP4 container.
