### ISSUE TITLE
Audio files bigger than 2G don't work

### ISSUE THREAD

**Issue by artofnois** [Zeugma440/atldotnet#185]
If you read files  sized with mor than 2G, ATL don't read the metadata.
My audio files are 32bit 96k, so file size bigger than 2G are used very often.

**Comment by Zeugma440** [comment]
Hi and thanks for your feedback. That 2G limit isn't by design and might be caused by a bug.

What kind of file are you reading ? Is there an error appearing somewhere in the console ?

**Comment by artofnois** [comment]
I have made a c# Visual console example so you can test it, an 2 wave files.
"https://drive.google.com/file/d/19ExqpVdSgGODqaTXMrP1eFjTGsZh2yF5/view?usp=sharing"
The file named "Largo.wav" (Long over 2G) is wich I have problems (don't read metadata)
The file named "Corto.wav" (Short one < 2G) is de same audio file but truncated a region of the audio file.  Here I can read audio metadata.
For my Application I use TablibSharp 4.20 because 4.23 delay a lots to read >2G and finally  don't any metadata

Other programas I have like Soundminer o Wavelab can read the metadata of both

**Comment by Zeugma440** [comment]
For starters, "Corto" has an additional ID3v1 tag that "Largo" doesn't have, which is probably why it works better.

Now for the actual issue on "Largo" : contrary to "Corto", "Largo" has a `RF64` header which wasn't supported until now by ATL.

Support is available on today's v4.24

**Comment by artofnois** [comment]
Hi again. I updated to 4.24 and then read the files ok.

But in a few files I have noticed that some metadada are missing compared to the metadata that appears in Wavelab.

For example:

In wavelab,  a file with 3.9G show these metadata in ixml (total number: 15 only in iXML )

 



 

 

The same file via Trak library, get only 12 additionalfields.

 



 

 

Jaime Blanco Ruiz

 

 

De: Zeugma440 ***@***.***> 
Enviado el: domingo, 19 de marzo de 2023 15:03
Para: Zeugma440/atldotnet ***@***.***>
CC: artofnois ***@***.***>; Author ***@***.***>
Asunto: Re: [Zeugma440/atldotnet] Audio files bigger than 2G don't work (Issue #185)

 

For starters, "Corto" has an additional ID3v1 tag that "Largo" doesn't have, which is probably why it works better.

Now for the actual issue on "Largo" : contrary to "Corto", "Largo" has a RF64 header which wasn't supported until now by ATL.

Support is available on today's v4.24
