### ISSUE TITLE
Reading Wav files lost some Metadata BEXT

### ISSUE THREAD

**Issue by artofnois** [Zeugma440/atldotnet#187]
Hi again:
I have tried several files at the same time with wavelab and the label "bext.description" never is present in AdditionalFields as you can
see here:
 
![imagen](https://user-images.githubusercontent.com/444517/227007747-1e6bf3b5-eed2-449b-acfe-24f8d242c166.png)

and that is what I see at Wavelab
![imagen](https://user-images.githubusercontent.com/444517/227008832-68e70dcc-b46d-4998-813f-b1f6b9d4157e.png)
an that is on Adobe Audition:

![imagen](https://user-images.githubusercontent.com/444517/227009415-bc779ebc-31a1-45f7-acbf-70e882d749e3.png)

If you need and audio example, let me know.
I think other tags are also lost. i'm looking for examples.

**Comment by Zeugma440** [comment]
Bext.Description is mapped to the `Track.Description` standard field.

Let me know if you find any other unmapped value.

**Comment by artofnois** [comment]
But that make metadata incompatible with standard metadata, don't?
I mean. When reading, it does not come in its bext.* zone. When saving, if I do not do the mapping Track.Description ->bext. Description, the other programs will not find this tag or at least not updated. Or when saving it remaps it again? I haven't used recording yet...

**Comment by Zeugma440** [comment]
It should remap it again, don't worry.

I haven't included it in the bext.* zone to avoid having two different places to update the very same field, that's why.

**Comment by artofnois** [comment]
Here we go,again:
A wave file.
That is what Wavelab say:
![imagen](https://user-images.githubusercontent.com/444517/229307557-e1979682-80ce-4430-8464-94350c50fe2e.png)

that is what ATL read;
![imagen](https://user-images.githubusercontent.com/444517/229307634-51ce734a-02e6-4279-b4e5-213e62e7823a.png)

Only 11 aditional fields and all of then are bext.

**Comment by Zeugma440** [comment]
That's an problem with iXML, not with BEXT. Could you please open a new issue and upload the file?

Thanks~
