### ISSUE TITLE
Saving a file, always get a boolean false value

### ISSUE THREAD

**Issue by artofnois** [Zeugma440/atldotnet#188]
Hello. 
Now, I'm doiong in my app the saving thing.... 
I always get an error on saving, so I have made a simple trial on Console APP:

![imagen](https://user-images.githubusercontent.com/444517/227790729-fdbbeb93-4f10-4787-b936-421f199a2248.png)

The line with 
"Console.WriteLine("Description: {0}", t1.AdditionalFields["ixml.TRACK_LIST.TRACK[1].USER.DESCRIPTION"].ToString() );"
is to confirm the read of Track is correct and the file metadata are correct.

And the console display show:

![imagen](https://user-images.githubusercontent.com/444517/227790879-6f14945a-9830-4e15-9a7e-974f95290133.png)

Version of ATL is the last 2.24. 
I compile for 64 bits, .net Framework 4.8.1

What I am doing wrong?

**Comment by Zeugma440** [comment]
You're not doing anything wrong - your file has something that is not supported yet by ATL (i.e. multi-purpose LIST chunks).

I'm working on it and will provide a new build in the following days.

**Comment by artofnois** [comment]
My intention is to create my own set of tags to classify my own files. But currently I have not yet added my set of tags (they will all start with "ixml.AON.*".
That was my first trial to dump all my tags from my program to audio files.
But those who currently have my files are put by the editors through which they have passed: Wavelab, Soundminer  and maybe Audition.

**Comment by Zeugma440** [comment]
Today's v4.26 has a fix for your issue.

> My intention is to create my own set of tags to classify my own files. But currently I have not yet added my set of tags (they will all start with "ixml.AON.*")

You can do that by doing 

```cs
Track track = new Track(filePath);
track.AdditionalFields.Add("ixml.AON.test", "this is a test");
track.Save();
```

It will be persisted that way in the iXML chunk :
```
<BWFXML>
...
  <AON>
    <test>this is a test</test>
  </AON>
</BWFXML>
````

**Comment by artofnois** [comment]
Thanks a lot.
I finally have save my metadata to tha audio files.

**Comment by Zeugma440** [comment]
You're welcome. Thanks for taking the time to report feedback, that really helped the library.

Let me know if you need anything else.
