### ISSUE TITLE
DSD "additional field

### ISSUE THREAD

**Issue by leglubert** [Zeugma440/atldotnet#19]
## The problem

ATL does not seem to read the additional tags on the *.dsf files
"DISCTOTAL"
"TRACKTOTAL" 

## Environment

* ATL version : 2.6
* OS/version used to run ATL : Windows 10

## Details
described in problem, I add that for *.flac, there is no problem 

## Code To Reproduce Issue [ Good To Have ]

aPropertiesList += "Disk : " + tagFile.DiscNumber + "/" + tagFile.AdditionalFields["DISCTOTAL"] + Environment.NewLine;

If you want a dsf files, just tell me

Every files is tagged with TagScanner

**Comment by Zeugma440** [comment]
Hi @leglubert and thanks for the report !

Are you sure the field you're looking for has that exact name on both FLAC and DSD ?

There's a possibility TagScanner used 
* FLAC's native tagging format (Vorbis), using the fields "DISCTOTAL" and "TRACKTOTAL"
* ID3v2 for DSD, with ID3v2's own way of representing totals by putting "/xx" behind the track / disc number, i.e. ("2/12" in TRCK field and "1**/2**" in TPOS field)

_________

To be sure about that, I'd like to take a look at one of the tagged files that doesn't work for you. Could you please provide a mega/google drive/dropbox/... link ?

Don"t hesitate to send a PM if you don't want your link to appear in the issue.

**Comment by Zeugma440** [comment]
By looking at your issue, I also realize ATL could provide new fields to give standard access to these two properties. It shouldn't be up to the user to "guess" which field goes where, especially for such common information.

**Comment by leglubert** [comment]
Hello,
Try with this file
http://81.28.193.98:7000/share.cgi?ssid=0J59Ssw

**Comment by Zeugma440** [comment]
Thanks for the file.
Looks like yesterday's guess was right on spot because that's exactly what happened.

I'll add a new field to `Track` to help you get what you need. I'll keep you informed.

**Comment by leglubert** [comment]
Great, thanks in advance.

**Comment by leglubert** [comment]
Side effect:
As the two TAG (DISCTOTAL/TRACKTOTAL), are not managed, they are deleted when "Save" if they exist.....

**Comment by leglubert** [comment]
:-)
some news, now with FLAC Files @atl 2.7

Traks : From 01/01 after save 1/1 (preserved without zero)
Year : From 2000 try to unpdate to 1955 after save nothing changed

Amitiés
Lionel

**Comment by Zeugma440** [comment]
Taking some time because I'm rewriting several unit tests and creating new ones... hold on ;-)

**Comment by leglubert** [comment]
no worries, happy to participate in the evolution of this great library

Amitiés
Lionel

**Comment by Zeugma440** [comment]
Reported issues concerning disctotal / tracktotal should be fixed on master branch

Now working on year & date issues

**Comment by leglubert** [comment]
disctotal / tracktotal on FLAC / DSF, OK

:-)

Amitiés
Lionel

**Comment by leglubert** [comment]
static bool UseLeadingZeroes = true; 
static bool OverrideExistingLeadingZeroesFormat = true;

Track:
Working on FLAC [1/1 -> 01/01]
but not in DSD [1/1 -> 1/1]

Amitiés
Lionel

**Comment by leglubert** [comment]
Rev : 719

Track:
Working on FLAC [1/1 -> 01/01]
Working on  DSD [1/1 -> 01/01]

Amitiés
Lionel

**Comment by Zeugma440** [comment]
Great !
