### ISSUE TITLE
WAV/RF64 : Unreachable iXML chunk

### ISSUE THREAD

**Issue by artofnois** [Zeugma440/atldotnet#191]
Follow-up from #187

**Comment by Zeugma440** [comment]
Got it, thanks!
I'll keep you informed

**Comment by Zeugma440** [comment]
PS : If sending files through GitHub is a problem to you, you may send them to me directly at [my Github username] (at) {not-cold} mail DOT COM

**Comment by Zeugma440** [comment]
The file you sent doesn't properly follow the RF64 specifications, as the size of the `data` chunk is supposed to be `0xFFFFFFFF` but is `0x00FFFFFF` instead.

I've written an acceptable workaround to make it work.

Before I publish it, I've noticed that file also has XMP metadata. Do you need to read/write it by any chance ?

**Comment by artofnois** [comment]
All the files I have >2G are originaly recorder as a sequence of several 2G  in teh recorder and then in cumputed appended to get only 1 file in Wavelab.
At this moment I have no save (yet) metadata in real files but copies for making my program to work.
So for me is important to read metadata becaus til now I user Soundminer to record several metadada . But I don't know where they put every metadata.
When my program will be finished, all my metadata will be in ixml.AON.*
I noticed making trials with save that several files where corrupted when saving my metadata ( from 3050 files in my library I get corrupted about 25-30  but all of then was the biggest ones... )

**Comment by Zeugma440** [comment]
> So for me is important to read metadata becaus til now I user Soundminer to record several metadada . But I don't know where they put every metadata.

I'm gonna publish the fixed version very soon. I hope it will allow you to read all you ned.

> I noticed making trials with save that several files where corrupted when saving my metadata ( from 3050 files in my library I get corrupted about 25-30 but all of then was the biggest ones... )

That's a real concern. Don't hesitate to send me those (on my e-mail address if you don't like publishing links on GitHub) if they still fail after the new update.

**Comment by Zeugma440** [comment]
This issue has been fixed in today's v4.28

**Comment by artofnois** [comment]
Ok, thanks.
I will try at this moment.

**Comment by artofnois** [comment]
Finally I got all the waves files with my tags.
That work OK.
Fine work!!!!
