### ISSUE TITLE
Saving metadata somtimes corrupt file ( 15 over 3052 files )

### ISSUE THREAD

**Issue by artofnois** [Zeugma440/atldotnet#192]
One of then is the same I send you the last day.
Today, saving file I get a  OK buf after that cannot read the metadata and the wavelab say "Corrupted file"
![imagen](https://user-images.githubusercontent.com/444517/229918326-fce48862-5b13-429f-a992-42d061cf2bf4.png)

and the Audition say:
![imagen](https://user-images.githubusercontent.com/444517/229900556-7d64b9cb-bd11-4754-8c2b-62c92acaca8d.png)
there are over 100M of data that is not audio data.

I can send you  all of then , but the are largest than 2G

**Comment by Zeugma440** [comment]
You were right, there were a couple issues with rewriting very large files, some specific to WAV files, some others global to the entire library. Thanks for your precious feedback.

The fix is available in today's v4.29.

**Comment by artofnois** [comment]
I updated. now the program is working to read de original tags and translate to my space ixml.AON. and then save in the file.


I notitced a delay reading tags. First release I use (maybe .24 ) reading all 5023 files was about 300seconds.. 
today the taime is about 750 seconds.
This morning with the previous release .28 writing all the 5023 files took over 6.700secons.
But now I can read ALL the tags (I think )

**Comment by Zeugma440** [comment]
Glad to hear the problem's solved!

Regarding the difference in reading speed between v4.24 and v4.29 : v4.24 didn't handle most of your files properly and ended up failing on many of them... which is generally faster than reading them entirely 😁  Comparing the performance of a process that fails (fast) to deliver expected results and a process that does deliver them is quite pointless imo.

Plus 750 seconds for 5023 files that are individually several hundred MBs long doesn't sound _that_ bad to me. That's less than a quarter second per file.

**Comment by artofnois** [comment]
What  I  wanted to say (sorry for my english), is that is that although it takes twice as long than at begining,  for me the important thing is that I do not lose tags and not to get the audio is damaged (which is the only thing I can not recover).
750 seconds for 3052 files are very good ratio.
I'm more concerned for saving time (over 10 times than reading) but I know saving is saving.
Again here, the only thing I worry about is to damage the audio file.

Now I'm making a new copy from the 3052 files to another HD to make the completed trial:
Read first form original files the original tags an generate a BBDD with the information, then to save the BBDD information in the files with the new tags for may namespace ixml.AON.* and then empty BBDD, and recover form my new tags from files.
From today I have 10 days without work, so I will make a lot of trials before the final countdown....

**Comment by artofnois** [comment]
Hi again.
The trial went very well.
All the files read and save metadata.
No error on save this time. An apparently... at this moment, no corrupt file.

**Comment by Zeugma440** [comment]
Glad to hear that~ 😄
