### ISSUE TITLE
MP3 - Reading Track getting stuck and never returning

### ISSUE THREAD

**Issue by jasoveen** [Zeugma440/atldotnet#194]
## The problem

When calling new Track() with a MP3 file the call is never returning and will hang forever.

## Environment

* ATL version (or git revision) that exhibits the issue: 4.11
* Last ATL version that did not exhibit the issue (if applicable): 4.10
* OS/version used to run ATL: Windows 10 x64

## Details

The MP3 file appears to be malformed and just seems to contain ID3 MetaData and no frames  (MP3 are created by a third-party application which normally creates valid MP3 files) so I would expect Track to return an error.

Issue started in version 4.11, using 4.10 Track() does return correctly with most of the MetaData from the MP3 file.
The following error is in the console when using 4.10
11:25:14:406	Index was outside the bounds of the array.
11:25:14:406	   at ATL.BufferedBinaryReader.ReadByte()
11:25:14:406	   at ATL.AudioData.IO.MPEGaudio.findFrame(BufferedBinaryReader source, VBRData& oVBR, SizeInfo sizeInfo)
11:25:14:406	   at ATL.AudioData.IO.MPEGaudio.Read(BinaryReader source, SizeInfo sizeInfo, ReadTagParams readTagParams)
11:25:14:406	   at ATL.AudioData.AudioDataManager.read(BinaryReader source, ReadTagParams readTagParams)
11:25:14:406	   at ATL.AudioData.AudioDataManager.ReadFromFile(Boolean readEmbeddedPictures, Boolean readAllMetaFrames)

With 4.11 or newer no error is returned and Track() just hangs.

I have attached a ZIP that contains the failing MP3 file.

## Code To Reproduce Issue [ Good To Have ]

 Track CallTrack = new Track(CallFilePath);

[Bad MP3 file.zip](https://github.com/Zeugma440/atldotnet/files/11407910/Bad.MP3.file.zip)

**Comment by Zeugma440** [comment]
Thanks for the detailed report ! I'll give it a look as soon as I can (currently busy with another project).

**Comment by Zeugma440** [comment]
Got it fixed for next release.

Please keep in mind that, as the file doesn't have any MPEG header, ATL will ignore it entirely as well as the metadata embedded inside.

**Comment by Zeugma440** [comment]
Fix is available on today's v4.32
