### ISSUE TITLE
Fresh Wav readed from a recorder and saved with ATL get error on save.

### ISSUE THREAD

**Issue by artofnois** [Zeugma440/atldotnet#195]
Hi Again.
Til today I allways use old files witch edited o managed in Soundminer.
This week, I began to use new and fresh files from my recorder. I have not use other programs... 
Edited with my program the tags and today I tried a massive "Embbed metadata to file". 
I get an error on every file.
So, I tried get one file open with ATL and save only .

        static void Main(string[] args)
        {
            Track t1 = new Track(@"C:\_PRuAudio\P\Monte Laturce - Cruz - 230430_011_Tr1_2.WAV");
            Console.WriteLine("----------------------------------");
            bool resultado = t1.Save();

            Console.WriteLine("----------------------------------");
            Console.WriteLine("Resultado: {0}", resultado );
        }

And I always get the same error. So for the ATL library, this file have a problem.

Secone try: Read the file with soundminer with no changes, save and then tried with my program: No problem. All is OK.

I think is some parameter that ATL need to work, but recorder don't fill when recording. (I have change my program because recorder don't fill metadata : Duration, samplerate, etc. So I had to use NAudio library to complete it)

The example file:
https://drive.google.com/file/d/17Ly1XnrGa0_sXKGWAFXydNjQgEvtpHPF/view?usp=share_link
when download file say me to delete.
(Used version ATL  4.31)

**Comment by Zeugma440** [comment]
Thanks for the detailed report ! I'll give it a look as soon as I can (currently busy with another project).

**Comment by Zeugma440** [comment]
Fixed for next release

**Comment by artofnois** [comment]
Thanks a loteWhat was the problem?Jaime Blanco

**Comment by Zeugma440** [comment]
Something I created to clean IXML chunks up had a bug. Nothing wrong on your side 😄

**Comment by Zeugma440** [comment]
Fix is available on today's v4.32

**Comment by artofnois** [comment]
I update the version. Now all is  OK.
Thanks

**Comment by Zeugma440** [comment]
You're welcome ;)
