### ISSUE TITLE
Possibly incorrect summary comment in Track.cs

### ISSUE THREAD

**Issue by d3jv** [Zeugma440/atldotnet#197]
Shouldn't this say it contains chapters instead of "Any other metadata field"?

https://github.com/Zeugma440/atldotnet/blob/920fbf2827d6f2de9f9223b960ea5da51673e49c/ATL/Entities/Track.cs#L216

**Comment by Zeugma440** [comment]
You're completely right, that's an unfortunate copy/paste from another field 😅 

It will be fixed for next release. Thanks~

**Comment by Zeugma440** [comment]
Fix is available on today's v4.34
