### ISSUE TITLE
wav editing questions

### ISSUE THREAD

**Issue by mikeatdjp** [Zeugma440/atldotnet#199]
## The problem

I have a wav file with an id3 tag and I use ATL to add a Description.  I expected the Description to be added to the existing tag but instead I found it was added in a bext tag at the end of the file (which isn't what i expected but might be acceptable, except-), and after something like 40k padding bytes.  My IFF Chunk Parser doesn't ignore these padding bytes and it looks like the file now has 5000 or so chunks when it should have only five or six.

## Environment

* ATL version (or git revision) that exhibits the issue: it appears to have happened sometime after 4.7, as soon as 4.12.
* Last ATL version that did not exhibit the issue (if applicable):  4.7
* OS/version used to run ATL  Windows 10, .net core 3.1 app.

## Details

If necessary, describe the problem you have been experiencing in more detail.
It appears maybe the padding was supposed to offset the last existing tag, but it started at the end of the tag and not at the beginning?  I don't know.

Don't forget to include ATL.Logging.Log and/or console output

## Code To Reproduce Issue [ Good To Have ]

            var track = new Track(edittedFilename);
            track.Description = "SOME NEW DESCRIPTION";
            track.Save();

**Comment by mikeatdjp** [comment]
[CD Track 01.zip](https://github.com/Zeugma440/atldotnet/files/11501881/CD.Track.01.zip)

Here is the file i used for this.

**Comment by Zeugma440** [comment]
Thanks for your feedback 👍 

> I expected the Description to be added to the existing tag but instead I found it was added in a bext tag at the end of the file 

I think part of your answer is in issue #168 : `Track.Description` doesn't have any mapping in ID3v2, and has one in BEXT, which explains what you're getting.

> and after something like 40k padding bytes

Well, that was unexpected 😅 Turned out I forgot to consider the "magic one-byte padding" in the loop condition when reading WAV chunks. That's fixed now. 

I'm waiting for your feedback in #200 before publishing a new release.

**Comment by Zeugma440** [comment]
Fix is available on today's v4.34
