### ISSUE TITLE
Update TAG Year

### ISSUE THREAD

**Issue by leglubert** [Zeugma440/atldotnet#20]
## The problem

I don't know if I'm making a mistake, I'm trying to update the TAG "Year"

in this way:

-----------------------------
Track trackFile = new Track(sTrackFile);
if (folderYear != trackFile.Year)
{
     trackFile.Year = folderYear;
     trackFile.Save();
}
------------------------------

the TAG in memory updates correctly, but after the "Save", the value returns to the previous value!

## Environment

* ATL 2.6
* OS/version Window 10
* Visual Studio 2017

## Code To Reproduce Issue [ Good To Have ]

-----------------------------
Track trackFile = new Track(sTrackFile);
if (folderYear != trackFile.Year)
{
     trackFile.Year = folderYear;
     trackFile.Save();
}
------------------------------

Amitiés
Lionel

**Comment by Zeugma440** [comment]
Your code is fine. It looks like Year is not saved properly for a couple formats such as FLAC and TwinVQ.

I'm in the process of fixing this. Stay tuned.

**Comment by leglubert** [comment]
Thanks...

is not only "not saved", is deleted if you change another TAG

Amitiés
Lionel

**Comment by Zeugma440** [comment]
Yeah, the date metadata mappings are not done correctly for these files, so there are a couple side effects...

**Comment by leglubert** [comment]
that's why I lost all the "year" tags of my files :-) :-) :-)

**Comment by leglubert** [comment]
:-)
some news, now with DSD Files @ATL 2.7

Traks : From 01/01 after save 1/1 (preserved without zero)
Year : From 2000 after save 2000;1959 (Added !)

Amitiés
Lionel

PS: I'll check with the *.flac

**Comment by Zeugma440** [comment]
Thanks for the report! 

I'm quite puzzled by that 1959 thing. Could you send the original file (before tagging)?

**Comment by Zeugma440** [comment]
Today's work should fix the issues with `Year` on Vorbis, ID3v2 and TwinVQ (if someone ever uses that one)

Could you please validate the fix on your side with the latest commits from master branch ?

If all's fine, the current version will be uploaded to NuGet.

Thanks again for your help !

**Comment by leglubert** [comment]
Ok,
Revision 725

MP3 : OK (Multilple pass)
FLAC : OK (Multilple pass)
DSF : OK (Multilple pass)

Thanks, great job :+1: 

Amitiés
Lionel

just one remark:
I didn't calculate exactly, but it seems relatively slow...
(file stored on an SSD disk)

**Comment by Zeugma440** [comment]
Awesome. Thanks for your promptness !

Regarding performance, the fact that you're editing very large files whose metadata is at the beginning of the file clearly contributes to that. But that's no excuse; many people use lossless nowadays.

So far I've worked on optimizing read speed and memory footprint. As you just guessed, I did not do much to optimize write speed so far. I suppose I'll start working on the optimization of FLAC-Vorbis and ID3v2 for DSD for the next release :-)

**Comment by leglubert** [comment]
Great !

Amitiés
Lionel

**Comment by leglubert** [comment]
please note, the read speed is OK, the write speed (4 to 8 s, per file)

File stored on NAS Qnap TS-853a / 1Gb network

**Comment by Zeugma440** [comment]
Thanks for the info. I assume these delays are for the average DSD file (roughly 100-300 MB) ?

How about the average FLAC (~50-100MB) and the average MP3 (~4-8MB) ?

**Comment by leglubert** [comment]
Action : Change Year from null to 4digits
FLAC:
42 Files, 1.03Gb (Network Drive on QNAP TS-853a)
5:23 (323s)  ~7s per file
FLAC:
42 Files, 1.03Gb (Local Drive SSD)
0:47 (47s)  ~1.1s per file

PS:
Filecopy HDD->NAS  ~110Mbs

**Comment by Zeugma440** [comment]
@leglubert After close inspection, ATL happens to spend _a lot of time_ moving bytes around at write time. It eventually does the job fine, with a lot of unnecessary steps.

One of the important pieces of optimization has been documented in #24

**Comment by Zeugma440** [comment]
FYI, #24 has been implemented and pushed into master branch. You should see nice improvements to writing speeds, especially for FLAC files.

In your case, I recommend using ATL with `Settings.EnablePadding = true` to add padding on files that don't have it yet.

**Comment by Zeugma440** [comment]
@leglubert
