### ISSUE TITLE
Writing is not supported for OGG with embedded FLAC

### ISSUE THREAD

**Issue by fsobolev** [Zeugma440/atldotnet#206]
## The problem

README states that writing to OGG with embedded FLAC is supported when it's actually not.

## Environment

* ATL version (or git revision) that exhibits the issue: **4.34.0**
* Last ATL version that did not exhibit the issue (if applicable): unknown
* OS/version used to run ATL: Fedora 38

## Details

```
Writing is not supported yet for embedded FLAC
   at ATL.AudioData.IO.Ogg.Write(Stream s, TagData tag, Action`1 writeProgress)
   at ATL.AudioData.AudioDataManager.UpdateTagInFile(TagData theTag, TagType tagType, ProgressManager writeProgress)
```

## Code To Reproduce Issue [ Good To Have ]

```
$ dotnet new console
$ dotnet add package z440.atl.core --version 4.34.0
```

Program.cs
```
using ATL;
using System;

public class Program
{
	private static void Main(string[] args)
	{
		var track = new Track(args[0]);
		Console.WriteLine(track.Title);
		track.Title = "TEST";
		track.Save();
		Console.WriteLine(track.Title);
	}
}
```

If the opened file is OGG with embedded FLAC, the error mentioned above will appear and the data will not be written to the file.

**Comment by Zeugma440** [comment]
Alright, obviously, the readme is incorrect, but I guess that's not what you _really_ meant ;)

I'll see what I can do.

**Comment by Zeugma440** [comment]
Fixed for next update ✅

**Comment by Zeugma440** [comment]
Available on today's v4.35  \o/

Please close the issue if you confirm the fix on your side~

**Comment by nlogozzo** [comment]
Fixed on my system!!

@fsobolev will close when he confirms the fix on his side as well :)

**Comment by fsobolev** [comment]
Works as expected now, thanks :)
