### ISSUE TITLE
Feature Request: BPM (Beats Per Minute) Field

### ISSUE THREAD

**Issue by nlogozzo** [Zeugma440/atldotnet#209]
BPM is a highly useful field, especially for DJs. It's supported by all major tag types. Of course we could write it with aditional fields however it's saved under different names per tag type. I'd suggest looking at taglib sharp for each tag type and get the name used. I'd be happy to get you the list of names...it just won't be till later :)

**Comment by Zeugma440** [comment]
Sure thing - I'll look at the specs myself, don't worry.

**Comment by Zeugma440** [comment]
Ready for next release ✅

**Comment by nlogozzo** [comment]
Let me.know when you release I'll test and confirm ASAP :)

**Comment by Zeugma440** [comment]
Available on today's v4.36. Please close the issue if the feature works as expected~

Btw, I'm considering jumping from .NET4.8 to .NET6. As Tagger uses .NET7, I guess it shouldn't be an issue for you

**Comment by nlogozzo** [comment]
> As Tagger uses .NET7, I guess it shouldn't be an issue for you

Yes our apps will always use the latest .NET version, so feel free to upgrade :)

**Comment by nlogozzo** [comment]
![image](https://github.com/Zeugma440/atldotnet/assets/17648453/5d60b46c-fe56-4dfe-8b93-8a0742947fed)

works!
