### ISSUE TITLE
[CLARIFICATION] Usage _ Code Snippets :: "Writing chapters in a tag" GetDataReader(string path) method is deprecated

### ISSUE THREAD

**Issue by tarrats** [Zeugma440/atldotnet#21]
## The problem

"Writing chapters in a tag" code snippet should probably reflect the updated method GetFromPath. At some point after ATL v4.2 the `GetDataReader(string path)` method used for writing chapter information into a file got deprecated and--most likely--changed to `GetFromPath(string path)
`
## Environment

* ATL version (or git revision) that exhibits the issue: 2.7
* Last ATL version that did not exhibit the issue (if applicable): 2.4
* OS/version used to run ATL: Windows 10 x64, v1803, build 17134.648

## Details

My old implementation using ATL v4.2 called for the `GetDataReader(string path)` method as per the code snippet example.  When I built ATL v4.7 the following building error was found:

`Error	CS1061	'AudioDataIOFactory' does not contain a definition for 'GetDataReader' and no extension method 'GetDataReader' accepting a first argument of type 'AudioDataIOFactory' could be found (are you missing a using directive or an assembly reference?)`

Parsing ATL solution under AudioDataIOFactory showed that the method `GetFromPath(string path)` is now used to prepare a file for writing chapter information.  After building, and a quick regression testing, my implementation worked as expected

## Code To Reproduce Issue

```
private string removeChapters(string filePath)
{
	AudioDataManager theFile = new AudioDataManager(AudioDataIOFactory.GetInstance().GetDataReader(filePath));
            
	ATL.TagData theTag = new ATL.TagData();
	theTag.Chapters = new System.Collections.Generic.List<ATL.ChapterInfo>();

	theFile.UpdateTagInFile(theTag, MetaDataIOFactory.TAG_ID3V2);

	sConsole = "Removed all chapters... ";

	return sConsole;
}
```

**Comment by Zeugma440** [comment]
Hello @tarrats and thanks for your feedback !

You're completely right, I did update  https://github.com/Zeugma440/atldotnet/blob/master/ATL.test/CodeSnippets/CodeSnippets.cs but not the wiki itself.

That's now done.

By the way, you can also add chapters using the `Track` class, without using the low-level cogs and wheels. I'm gonna add another snippet for that.

**Comment by tarrats** [comment]
You rock!  Thanks so much!
