### ISSUE TITLE
Pictures not showing in Spotify

### ISSUE THREAD

**Issue by nlogozzo** [Zeugma440/atldotnet#210]
Hi,

We received [this issue for Tagger](https://github.com/NickvisionApps/Tagger/issues/230) in which embedded pictures are not being show in Spotify (if you didn't know, yes Spotify client can play local files...I learned that too).

We set pictures in Tagger via the following code:
```csharp
track.EmbeddedPictures.Add(PictureInfo.fromBinaryData(FrontAlbumArt, PictureInfo.PIC_TYPE.Front));
track.EmbeddedPictures.Add(PictureInfo.fromBinaryData(BackAlbumArt, PictureInfo.PIC_TYPE.Back));
```
where `FrontAlbumArt` and `BackAlbumArt` are `byte[]` of `jpg` images.

I tried changing the `PIC_TYPE` to `Generic` but that also didn't work.

--

Spotify only provides [these requirements on cover art](https://support.spotify.com/us/artists/article/cover-art-requirements/)...the only thing  I'm thinking is that this is not happening and thus not showing in Spotify:

> Encoded with an sRGB color space, 24bits per pixel, with color profiles applied directly
Don’t upscale images. We also don’t support embedded color profiles and orientation metadata.

Can you in the library encode added pictures in sRGB space with 24bits per pixel with profiles applied directly? Is that even possible?

**Comment by Zeugma440** [comment]
Hey Nick 😄 

The code you posted looks fine. I'd bet the issue is within the requirements you underlined.

> TIFF, PNG, or JPG format using lossless encoding
> At least 640px wide and tall
> 1:1 aspect ratio
> Encoded with an sRGB color space, 24bits per pixel, with color profiles applied directly

ATL is not (and won't be) an image processing library, so all of these requirements should be checked _before_ you embed the picture into the MP3.

Maybe create a "Is my picture Spotify-ready?" feature that analyzes the submitted cover and fires a warning if these requirements aren't met?

**Comment by nlogozzo** [comment]
> Maybe create a "Is my picture Spotify-ready?" feature that analyzes the submitted cover and fires a warning if these requirements aren't met?

Yes I guess I'll have to eventually do something like this

Sounds good...thanks :)

**Comment by nlogozzo** [comment]
Reopening as it turns out it has nothing to do with image manipulation...I believe it might be the way ATL stores pictures...

Using the program [EarTag](https://gitlab.gnome.org/World/eartag) (python based) that uses [mutagen](https://github.com/quodlibet/mutagen) stores the album art without an image modification and it shows in Spotify no problem.

I first believed it was because I was saving art with Front/Back PicType but even using Generic it still doesn't show...

**Comment by Zeugma440** [comment]
> Using the program [EarTag](https://gitlab.gnome.org/World/eartag) (python based) that uses [mutagen](https://github.com/quodlibet/mutagen) stores the album art without an image modification and it shows in Spotify no problem.

Could you upload such a tagged file ? I'm not sure I want to install EarTag and its pre-requisites to edit one single file.

**Comment by nlogozzo** [comment]
> Could you upload such a tagged file ? I'm not sure I want to install EarTag and its pre-requisites to edit one single file.
Nvm, most of my files are displayed properly in Spotify.

No worries here they are anyway just in case they are of use. They are the same exact file just one has album art added from eartag and one has album art added from Tagger:

EarTag: [EarTag.zip](https://github.com/Zeugma440/atldotnet/files/12423238/EarTag.zip)
Tagger: [Tagger.zip](https://github.com/Zeugma440/atldotnet/files/12423241/Tagger.zip)

*Note let's not have this block the release of the lyrics fixes. This isn't that important as the lyrics fixes that I need for Tagger's release tomorrow*

**Comment by Zeugma440** [comment]
A few things I noticed when testing :
1/ The EarTag file you provided doesn't work either on Spotify (installed v1.2.18.999.g9b38fc27)
2/ Forcing ATL to write ID3v2.3 tags (`Settings.ID3v2_tagSubVersion = 3`) works
3/ There's a way to make it work with ID3v2.4 too, as MP3 - currently investigating that lead

**Comment by Zeugma440** [comment]
Got it!

You should use the new flag `Settings.ID3v2_writePictureDataLengthIndicator = false` for the picture to show in Spotify.

**Comment by nlogozzo** [comment]
> Got it!
> 
> You should use the new flag `Settings.ID3v2_writePictureDataLengthIndicator = false` for the picture to show in Spotify.

Thank you! Can't wait to try it :)

**Comment by nlogozzo** [comment]
> Got it!
> 
> You should use the new flag `Settings.ID3v2_writePictureDataLengthIndicator = false` for the picture to show in Spotify.

Is there any issue if I keep this flag always false...i.e. should I only have it false if the user wants it to work on Spotify? Or does it not matter?

**Comment by Zeugma440** [comment]
Available on today's v5.04

> Is there any issue if I keep this flag always false...i.e. should I only have it false if the user wants it to work on Spotify? Or does it not matter?

According to the specs, it's an optional flag, so I think you can keep it forced to `false`. As for myself, that field has been there for a while. I think I added it to have more metadata available, but I don't remember it _needing_ to be there for any reason.

**Comment by nlogozzo** [comment]
ok sounds good...thanks so much for everything!!

**Comment by nlogozzo** [comment]
Can confirm it works now!!
![image](https://github.com/Zeugma440/atldotnet/assets/17648453/f7db6c77-a533-4c27-941a-cb3dec83b54c)
