### ISSUE TITLE
Lyrics Issues

### ISSUE THREAD

**Issue by nlogozzo** [Zeugma440/atldotnet#212]
### Hello again :)

So Tagger recently implemented Lyrics support. Below is how we have it implemented in our [`MusicFile`](https://github.com/NickvisionApps/Tagger/blob/main/NickvisionTagger.Shared/Models/MusicFile.cs) class:
<details>
  <summary>**Implementation**</summary>

  ```csharp
  public class MusicFile 
  {
      /// <summary>
      /// The language code of the lyrics of the music file
      /// </summary>
      public string LyricsLanguageCode { get; set; }
      /// <summary>
      /// The description of the lyrics of the music file
      /// </summary>
      public string LyricsDescription { get; set; }
      /// <summary>
      /// The unsynchronized lyrics of the music file
      /// </summary>
      public string UnsynchronizedLyrics { get; set; }
      /// <summary>
      /// The set of synchronized lyrics
      /// </summary>
      public Dictionary<int, string> SynchronizedLyrics { get; set; }
  
      public void LoadTagFromDisk()
      {
          ...
          LyricsLanguageCode = track.Lyrics.LanguageCode;
          LyricsDescription = track.Lyrics.Description;
          UnsynchronizedLyrics = track.Lyrics.UnsynchronizedLyrics;
          foreach (var phase in track.Lyrics.SynchronizedLyrics.OrderBy(x => x.TimestampMs))
          {
              SynchronizedLyrics.Add(phase.TimestampMs, phase.Text);
          }
          ...
      }
  
      public void SaveTagToDisk()
      {
          ...
          track.Lyrics = new LyricsInfo()
          {
              LanguageCode = LyricsLanguageCode,
              Description = LyricsDescription,
              UnsynchronizedLyrics = UnsynchronizedLyrics,
              SynchronizedLyrics = new List<LyricsInfo.LyricsPhrase>()
          };
          foreach (var pair in SynchronizedLyrics)
          {
              track.Lyrics.SynchronizedLyrics.Add(new LyricsInfo.LyricsPhrase(pair.Key, pair.Value));
          }
          track.Save();
          ...
      }
  }
  ```
</details>

Pretty simple :) ... But we received this report on the feature from @SpicyWasab, a user of `flac` and `mp3` files with lyrics: https://github.com/NickvisionApps/Tagger/issues/225#issuecomment-1674776910 . It's a big report so I won't paste it all here, but sounds like some `atldotnet` parsing issues of synchronized lyrics in [LRC format](https://en.wikipedia.org/wiki/LRC_(file_format)) (the standard for synced lyrics).

### Here are some issues pointed out:
- Other applications like NTag and Ex Falso store synchronized lyrics in a field called `LYRICS` in LRC format and when `atldotnet` reads it, it's in `UnsyncrhonizedLyrics`
- Sometimes lyrics just don't show for the `flac` files (neither in unsynced or synced).

*Again you can read full details in that issues link*

### Here is a zip file of mp3 and flac files with lyrics for you to investigate: https://drive.proton.me/urls/KKKTXFCW3W#1tCqnQ0mqZhd 
(*sorry for the link but github only let's me upload 25MB and this is 80 😅*)

### Some more information about these files:
- `.flac` files:
    - `Annihilate.flac` is the buggy one where the lyrics aren't even displayed in Tagger, even though they are in other softwares.
        - Error from `atldotnet` when reading this file: 
        ```
        ERROR: Error reading from the audio source (Invalid data found when processing input)
        ERROR: Not enough audio data
       ``` 
    - `better than i am.flac` is the one where the lyrics are displayed as unsyncrhonized (even though they are syncrhonized with provided timestamps in LRC format)
- `Bones.mp3` : Lyrics again displayed as unsyncrhonized even though synced in LRC format

atldotnet V4.36.0

**Comment by Zeugma440** [comment]
Right now, the library doesn't parse LRC blocks of text into synchronized lyrics, but that can be solved easily 😉

Thanks for providing the samples!

I'll look into it as soon as I'm back from vacation.

**Comment by Zeugma440** [comment]
1st issue solved : the lyrics in `Annihilate.flac` couldn't be read because the file is tagged with both ID3v2 and Vorbis and ATL had a bug until now.

**Comment by nlogozzo** [comment]
> 1st issue solved : the lyrics in `Annihilate.flac` couldn't be read because the file is tagged with both ID3v2 and Vorbis and ATL had a bug until now.

Great to hear!! :)

**Comment by Zeugma440** [comment]
Fix is available on today's v5.00

**Comment by nlogozzo** [comment]
Beautiful! Thank you...will update Tagger later today :)

**Comment by Zeugma440** [comment]
No problem !

Please note that the `offset` LRC metadata has no effect on the timestamps. You'll have to handle it yourself for now.

We can work on something better if you need it ofc 😉

**Comment by nlogozzo** [comment]
Just tested the update on Tagger, seems to be read correctly under synchronized tags!!

One issue though, `Annihilate.flac` is still logging:
```
ERROR: Error reading from the audio source (Invalid data found when processing input)
ERROR: Not enough audio data
```
when the file is loaded, BUT the lyrics are read correctly.

**Comment by nlogozzo** [comment]
> > No problem !
> > Please note that the `offset` LRC metadata has no effect on the timestamps. You'll have to handle it yourself for now.
> > We can work on something better if you need it ofc wink
> 
> I didn't even know `offset` was a thing hahaha...but from what I quickly ready it's just an overall addition or subtraction to all the timestamps, no? Can't you just iterate over all the timestamps and apply the offset if there is one?

Unless `offset` is more for music players then I can just add a field to our lyrics editor to provide an offset values and leave the timestamps the way they are....same as the LRC format itself

**Comment by Zeugma440** [comment]
> It's just an overall addition or subtraction to all the timestamps, no? Can't you just iterate over all the timestamps and apply the offset if there is one?

That would be a solution, but altering the raw timestamps might be confusing for users

> Unless offset is more for music players then I can just add a field to our lyrics editor to provide an offset values and leave the timestamps the way they are....same as the LRC format itself

That sounds more appropriate imho

> Just tested the update on Tagger, seems to be read correctly under synchronized tags!!

Yay  \o/

> One issue though, Annihilate.flac is still logging [...]

ATL doesn't log these messages. I guess you should look into the other libraries you've integrated.

**Comment by nlogozzo** [comment]
> ATL doesn't log these messages. I guess you should look into the other libraries you've integrated.

Hmm it's just ATL we are using 😅 but I'll take a look

**Comment by nlogozzo** [comment]
> > ATL doesn't log these messages. I guess you should look into the other libraries you've integrated.
> 
> Hmm it's just ATL we are using 😅 but I'll take a look

Nvm I forgot chromaprint hahah
