### ISSUE TITLE
WAV - Padding removed after adding tags

### ISSUE THREAD

**Issue by mathiascode** [Zeugma440/atldotnet#213]
## The problem

I have a WAV file without ID3 tags, where a padding byte is added after the audio data due an odd-sized chunk length. ATL incorrectly removes the padding when adding tags.

## Environment

* ATL version (or git revision) that exhibits the issue: 4.36
* Last ATL version that did not exhibit the issue (if applicable): -
* OS/version used to run ATL: Fedora Silverblue 38

## Details

Original file (untitled.wav):

![](https://github.com/Zeugma440/atldotnet/assets/8754153/49e9f92f-1682-426e-ac9b-b0dca345d5f5)

File with tags, created by [TagLib](https://taglib.org/) (untitled_tag_taglib.wav):

![](https://github.com/Zeugma440/atldotnet/assets/8754153/0430a61a-3bdb-4f99-b298-c207f7047913)

File with tags, created by ATL (untitled_tag_atl.wav):

![](https://github.com/Zeugma440/atldotnet/assets/8754153/e99185d2-7419-4eb5-beaa-2d92747a0aa7)

[files.zip](https://github.com/Zeugma440/atldotnet/files/12342741/files.zip)

**Comment by mathiascode** [comment]
I'm not sure if AIFF suffers from the same issue, but it might be worth verifying.

**Comment by Zeugma440** [comment]
Thanks for your feedback and for providing sample files 😄 

> I have a WAV file without ID3 tags, where a padding byte is added after the audio data due an odd-sized chunk length. ATL incorrectly removes the padding when adding tags.

Correct. ATL creates the ID3 chunk at the wrong position, overwriting the last byte of the audio chunk. That's been fixed for next release.


> I'm not sure if AIFF suffers from the same issue, but it might be worth verifying.

I just checked - AIFF doesn't need fixing 👌

**Comment by mathiascode** [comment]
Thanks for the quick fix! I wish these padded chunks weren't a thing, but it's too late for that. :)

**Comment by Zeugma440** [comment]
Fix is available in today's v5.01
