### ISSUE TITLE
WebP Image Detection

### ISSUE THREAD

**Issue by fsobolev** [Zeugma440/atldotnet#214]
## The problem

Hi! I wasn't sure how to properly name the issue, so let me explain: there are no issues with reading and writing webp covers themselves in music files. The problem is that if a cover is a webp image, ATL doesn't know about its format. In Tagger we allow to export album art from music file, and when doing this the app gets mimetype of the image from ATL, and this mimetype is set in a file chooser. But for webp images it's `image/*`, so the user doesn't know what is the format of the image. It would be nice if we could get `image/webp` from ATL for webp images.

## Environment

* ATL version (or git revision) that exhibits the issue: 4.36.0
* Last ATL version that did not exhibit the issue (if applicable):
* OS/version used to run ATL: Fedora 38

## Code To Reproduce Issue [ Good To Have ]

https://github.com/NickvisionApps/Tagger/blob/main/NickvisionTagger.Shared/Controllers/MainWindowController.cs#L863

**Comment by Zeugma440** [comment]
Sure, no problem

**Comment by Zeugma440** [comment]
Done for next release : cca311f6caf1dca26e41ed9bdb41dd4482e27230

**Comment by nlogozzo** [comment]
Thanks!! Could we see it today? 👀

**Comment by Zeugma440** [comment]
Fix is available in today's v5.01

**Comment by nlogozzo** [comment]
> Fix is available in today's v5.01

Thank you!!!
