### ISSUE TITLE
[ENHANCEMENT] New Setting for saving the file's ID3v2 tags in ID3v2.3

### ISSUE THREAD

**Issue by tarrats** [Zeugma440/atldotnet#22]
## The problem

By Design, ID3v2 tags are saved in v2.4. While this is the expected behaviour, and even issue #16 briefly ignited the discussion, my only take on having support for v2.3 would be for cosmetic purposes.

1. In Windows (see environment below) whenever ATL updates an audio file like MP3 after embedding an image via metadata, the resulting MP3 file's metadata is saved in ID3v2.4.  The icon for this file fails to show the image in Windows Explorer view; however, when explicitly converted to ID3v2.3 (using SW like Mp3tag) the resulting updated file does show the embedded image in all Windows Explorer views.

2. Currently, ATL Chapter implementation fails to show chapters in at least two podcast grabber apps: Apple Podcast, and Overcast.  Even when the ID3v2 Chapter Frame Addendum explicitly supports both v2.3 and v2.4, a commercial software for Chapter support for the Mac, only supports v2.3.  ¿Maybe podcast grabbers don't like v2.4 yet?  Until further investigation I cannot make the case for Chapter support and ID2v2.3, but I wanted to at least put it on the table

## Environment

* ATL version (or git revision) that exhibits the issue: **2.7**
* Last ATL version that did not exhibit the issue (if applicable): **N/A**
* OS/version used to run ATL: **Windows 10 x64, v1803, build 17134.648**

## Details

It would be super nice to have a setting like:

`public static bool ID3v2_alwaysSaveUsingID3v2.3 = false;`

explicitly **false** by default, and only when set to true will the resulting updated ID3v2 be saved in ID3v2.3, otherwise ID3v2.4 like it is today by design.

## Code To Reproduce Issue
```
ATL.Track theTrack = new ATL.Track("C:\podcast.mp3");
string sCoverPath = "C:\picture.jpg";
            
ATL.PictureInfo newPicture = new ATL.PictureInfo(Commons.ImageFormat.Jpeg, ATL.PictureInfo.PIC_TYPE.CD);
newPicture.PictureData = System.IO.File.ReadAllBytes(sCoverPath);

// check if there's an existing cover image
if (!(theTrack.EmbeddedPictures.Count == 0)){
	theTrack.EmbeddedPictures.RemoveAt(0);
}

theTrack.EmbeddedPictures.Add(newPicture);
theTrack.Save();
```

**Comment by Zeugma440** [comment]
Thanks for the detailed feedback !

I knew this day would happen. There are indeed pieces of software that are too lazy to support ID3v2.4, especially embedded software.

I'll be working on that and keep you updated in the next weeks.

**Comment by tarrats** [comment]
Thanks so much again, you rock @Zeugma440 !!!

**Comment by Zeugma440** [comment]
Support for writing in ID3v2.3 format is now available in the master branch.

To enable it, use `Settings.ID3v2_tagSubVersion = 3` (default = 4) before saving your `Track`

Please let me know if that solves your issues.

Cheers~

**Comment by tarrats** [comment]
I'll test it out from the branch and will let you know thanks!

**Comment by tarrats** [comment]
Works like a charm!  After explicitly changing the new setting to 3 before building the DLL and updating ID3v2 information using ATL I can attest the resulting file is indeed ID3v2.3 and as such, the resulting Windows Explorer view icon is immediately updated and rendered with the appropriate embedded picture!

**Comment by tarrats** [comment]
However; after reggression testing each Chapter node isn't saving the expected data:

```
     AudioDataManager theFile = new AudioDataManager(AudioDataIOFactory.GetInstance().GetFromPath("thefile.mp3"));

     ATL.TagData theTag = new ATL.TagData();
     theTag.Chapters = new System.Collections.Generic.List<ATL.ChapterInfo>();
     ATL.ChapterInfo thisChapter = new ATL.ChapterInfo();
    
     thisChapter.UniqueID = "chp0";
     thisChapter.Title = "First Chapter";
     thisChapter.StartTime =0;
     thisChapter.EndTime = 12000;
     thisChapter.StartOffset = 4294967295;
     thisChapter.EndOffset = 4294967295;
     thisChapter.Picture = null;
     thisChapter.Url = "chapter url\0http://github.com/";

     theTag.Chapters.Add(thisChapter);

     // Persists the chapters
     theFile.UpdateTagInFile(theTag, MetaDataIOFactory.TAG_ID3V2);
```
Expected in ID3v2.Chapters[0] values:

```
     EndOffset: 4294967295 uint
     EndTime: 12000 uint
     Picture: null ATL.PictureInfo
     StartOffset: 4294967295 uint
     StartTime: 0 uint
     Subtitle: "" string
     Title: "First Chapter" string
     UniqueID: "chp0" string
     Url: "chapter url\0http://github.com/" string
     UseOffset: false bool
```
Actual ID3v2.Chapters[0] values:
     
```
     EndOffset: 4294923337 uint
     EndTime: 786497535 uint
     Picture: null ATL.PictureInfo
     StartOffset: 4294967295 uint
     StartTime: 0 uint
     Subtitle: "" string
     Title: "" string
     UniqueID: "灨0" string
     Url: "" string
     UseOffset: false bool
```
Which means that, at the very least, **EndOffset**, **EndTime**, and **UniqueID**, have been changed from their original values (note that **UniqueID** shows a chinese character) and **Title** and **Url** have been NULLed from their original values.

**Comment by Zeugma440** [comment]
My apologies. I did include a regression test for basic fields, but not for chapters.

The issue has been fixed (see latest commit).

**Comment by tarrats** [comment]
Verified fix and new enhanced functionality, the output file is indeed ID3v2.3 and as such, the resulting Windows Explorer view icon is immediately updated and rendered with the appropriate embedded picture when one is added through ATL.  Thank you so much!

**Comment by Zeugma440** [comment]
My pleasure
