### ISSUE TITLE
Lyrics Language Code and Description Not Saving

### ISSUE THREAD

**Issue by nlogozzo** [Zeugma440/atldotnet#220]
Hello again :)

It seems that `LyricsInfo.LanguageCode` and `LyricsInfo.Description` don't always save correctly.
Here's a file for testing with blank unsync and sync:  (Removed)

If I do:
```csharp
var track = new Track(Path)
track.Lyrics.LanguageCode = "eng";
track.Save();
```
and then reload (`track = new Track(Path)`) the file, the LanguageCode was not saved.

If I do:
```csharp
var track = new Track(Path)
track.Lyrics.Description = "xyz";
track.Save();
```
and then reload (`track = new Track(Path)`) the file, the Description was not saved.

If I do:
```csharp
var track = new Track(Path)
track.Lyrics.LanguageCode = "eng";
track.Lyrics.Description = "xyz";
track.Lyrics.UnsynchronizedLyrics = "asd";
track.Save();
```
and then reload (`track = new Track(Path)`) the file, the language code and description are saved correctly. But shouldn't they still save without setting UnsyncrhonizedLyrics as they can also apply to SynchronizedLyrics?

**Comment by Zeugma440** [comment]
I simply assumed setting a description or a language code without setting the lyrics themselves is pointless. Plus in ID3v2, language code and description cannot float in outer space - they need to be linked to other metadata.

> But shouldn't they still save without setting UnsyncrhonizedLyrics as they can also apply to SynchronizedLyrics?

Of course - in that case, setting `SynchronizedLyrics` will save these fields too

**Comment by nlogozzo** [comment]
Ah ok yeah that makes sense. All good then.

**Comment by nlogozzo** [comment]
Good to release #219 then :)

**Comment by Zeugma440** [comment]
> Yeah I get it...this one though I'd like now because it prevented me from seeing sync lyrics changes in Tagger ... but in the future I'm ok with waiting...just that I plan to release Tagger stable on Friday as well.

Then could we wait until thursday to make sure you won't have any other issue in the meantime?

> I truly appreciate all the work you've done and working closely with us to get all this fixed and out 

My pleasure! All that you've found and suggested is now available for all ATL users, which is a genuine win-win situation 😄

**Comment by nlogozzo** [comment]
> Then could we wait until thursday to make sure you won't have any other issue in the meantime?

Sure :)
