### ISSUE TITLE
Unable to load picture from OPUS

### ISSUE THREAD

**Issue by nlogozzo** [Zeugma440/atldotnet#225]
Hello again, 

We have this opus file here: (Removed) that has an embedded picture.

However, ATL does not load it into the Pictures list but instead it seems to be stored in a custom property named `metadata_block_picture` that contains the bytes for it.

**Comment by Zeugma440** [comment]
Well, that's a bug, as ATL expects `metadata_block_picture` to be written with capital letters 😅 

The fix will be available for next release

**Comment by nlogozzo** [comment]
Could we see release by Thursday/Friday for updating in Tagger?

*Tagger usually releases stables every Friday just an FYI :)*

**Comment by Zeugma440** [comment]
Yup, should be up tomorrow. Can't guarantee that everytime though, it depends on many things on my end ;)

**Comment by nlogozzo** [comment]
> Yup, should be up tomorrow. Can't guarantee that everytime though, it depends on many things on my end ;)

No worries. As always thanks for everything!!

**Comment by Zeugma440** [comment]
Available on today's v5.06
