### ISSUE TITLE
ATL chapter implementation not displaying in Apple Podcasts and other podcast grabbers

### ISSUE THREAD

**Issue by tarrats** [Zeugma440/atldotnet#23]
## The problem

While ATL does an amazing job of writing chapters in the correct CTOC frame in ID3v2 as per the [Chapter Frame Addendum](http://id3.org/id3v2-chapters-1.0), now that the **Apple Podcasts** app has Chapter support, it's a good test environment for ATL Chapter implementation; however, contrary to other podcasts that use a commercial chapter implementation, ATL Chapter implementation doesn't seem to show at all in **Apple Podcasts**, and only partially shows in other podcast grabbers like **Overcast**.

## Environment

* ATL version (or git revision) that exhibits the issue: **2.7**
* Last ATL version that did not exhibit the issue (if applicable): **N/A**
* OS/version used to run ATL: **Windows 10 x64, v1803, build 17134.648**

## Details

After inspection of the CTOC frame under Additional Fields for both implementations, the only notable difference is the lack of the ACKNOWLEDGE ACK (u0006) character, and the lack of the TIT2 sub-frame, which includes the START OF HEADING SOH (u0001) code, the UTF-16 BYTE ORDER MARK BOM (ÿþ)

commercial implementation:

```
{[CTOC, toc
CTOC
toc\0\u0003\u0006chp0\0chp1\0chp2\0chp3\0chp4\0chp5\0TIT2\0\0\0%\0\0\u0001ÿþT\0a\0b\0l\0e\0 \0o\0f\0 \0C\0o\0n\0t\0e\0n\0t\0s
```

ATL implementation:

```
{[CTOC, toc
CTOC
toc\0\u0003\u0003chp0\0chp1\0chp2
```
Note that for the commercial implementation after the UTF-16 BOM the string "Table of Contents" is concatenated

## Steps To Reproduce Issue (images attached)

1. In Apple Podcasts iOS search the **Ruminate** podcast
2. Once located, play episode 13 "Crumpets On Your Tea Towel", this specific episode contains a commercial chapters implementation 
3. Scroll down and notice that under the Chapters section in the iOS app, there is a clickable Chapter list.  Once clicked the podcast will be skipped to the beginning of each chapter.
4. In Apple Podcasts iOS, search the **El Chilanyorker** podcast
5. Once located, play any episode, all episodes in this specific podcast contain an ATL Chapter implementation

Result:

6. Scroll down and notice that there is no Chapters section in the iOS app, ergo no chapter list, and no clickable items.

Expected:

- The ATL Chapter implementation podcast should show the Chapter sections, a Chapter list, and chapter clickable items in the Apple Podcasts App 

Note:

In the [Overcast ](https://overcast.fm/) podcast grabber the same behavior happens, with a little exception: even when a Chapter section isn't rendered, the Chapter titles do appear; however, there's no way to navigate between them.

Thanks so much!

**Comment by tarrats** [comment]
![4adc047f-a2a1-4f57-9bfb-46b0218fd6b7](https://user-images.githubusercontent.com/36057367/54904483-0c110580-4eb5-11e9-9916-99a31b1dec57.jpg)
![91a1c3ad-0b8e-4029-9ca0-81be64fafdcf](https://user-images.githubusercontent.com/36057367/54904512-1e8b3f00-4eb5-11e9-94e1-71c167be9674.jpg)
![8457ed3b-e1ff-4453-b199-51bd3e955a05](https://user-images.githubusercontent.com/36057367/54904532-277c1080-4eb5-11e9-861c-aac9938722f8.jpg)
![50232424-970d-437e-bcc7-a250a48c311c](https://user-images.githubusercontent.com/36057367/54904544-2a770100-4eb5-11e9-86b0-ac599eb35350.jpg)
![334b3e3f-901e-4ecc-9722-8ecb79431129](https://user-images.githubusercontent.com/36057367/54904563-32cf3c00-4eb5-11e9-96e6-4235187d4b93.jpg)
![36f506c1-3089-4b9f-9372-d451b47082b7](https://user-images.githubusercontent.com/36057367/54904568-36fb5980-4eb5-11e9-931b-3ffd399affe3.jpg)
![5e315b20-41be-4545-895a-89d3bd11ac6c](https://user-images.githubusercontent.com/36057367/54904590-47133900-4eb5-11e9-9a8a-e51e5077750a.jpg)
![7a4b92af-749a-4b2e-9e4e-ec539003dd6c](https://user-images.githubusercontent.com/36057367/54904615-54c8be80-4eb5-11e9-8aa8-c91fc2e2c5e5.jpg)

**Comment by Zeugma440** [comment]
Thanks a lot for that detailed investigation work.

I'll take a look and keep you updated.

**Comment by tarrats** [comment]
Thanks again for all your time and effort!

**Comment by Zeugma440** [comment]
TIT2 is actually the title tag, which is recommended by the standard (not mandatory, but alas, it seems Apple has just made it so).

As a workaround, have you tried setting a title for each of your chapters, even an empty one ?  That might just sove your problem.

Please let me know :-)

**Comment by tarrats** [comment]
Good news is, there are podcasts that render the chapter section and display individual chapters--in at least Apple Podcast App and Overcast podcast grabber--without the use of the TIT2 sub-frame.  So my initial assumption was incorrect, and there's evidence that TIT2 is not needed for chapters to show (reflecting that in the title).

That being said, I'll try to replicate the value of the CTOC frame in case there's some 'magical' character, or encoding thing that does the magic:

[different CTOC frames.txt](https://github.com/Zeugma440/atldotnet/files/3006014/different.CTOC.frames.txt)

I believe it might have something to do with the character prepending the first "chp0", so I'll try and mess around with ID3v2.cs and let you know if I require guidence or if I could pull it off.  Thanks!

**Comment by Zeugma440** [comment]
Thanks for the update ! Unfortunately I don't have any Apple device here, so I can't use these readers to test.

Regarding the sample frames you submitted, the characters just before the first "chp0" is the frame count : 3 if there are 3 chapters, 6 if there are 6 chapters...

I'm not sure the CTOC frame alone is to be blamed. The issue might be somewhere else, including the fact that some readers aren't ready for ID3v2.4, as you said in the other issue.

Would it be possible to have these files dropped somewhere so that I can grab and examine them more closely ?

**Comment by Zeugma440** [comment]
In addition to ID3v2.3 support, I've added the TIT2 optional subframe to CTOC frames, in case that makes a difference.

Please let me know if it works better for you. If not, I'll take a close look to one or two of the podcasts  you mentioned (found two of them MP3's on the web, so you don't need to send them anymore).

**Comment by tarrats** [comment]
Thank you so much! I haven't shared the files since I'm debugging a behaviour that might be a culprit, but will let you know of my findings in a couple of hours.  Thanks again!

**Comment by tarrats** [comment]
A regression noted in issue #22 hasn't allowed me to publish the podcast and try the new functionality with the TIT2 sub-frame; however I did notice a weird character, or lack thereof, before the chapter enumeration in the ATL.Track.AdditionalFields.CTOC (see attached file)

[AdditionalFields.CTOC.txt](https://github.com/Zeugma440/atldotnet/files/3011341/AdditionalFields.CTOC.txt)

I can't believe I didn't see this before, but it seems that the behaviour I'm seeing goes back at least since ATL v2.4.  The TXT file  is comprised of mp3 files with Chapters based on ATL v2.4, v2.7 and the current master fork the oldest one going back almost a year, but notice that in every instance prior to **chp0** which is the FIRST CHAPTERID in every file, there is no NULL character "\0". but rather the following characters: "(", ",", "&", ")" and the paragraph separators "u001d" and "u001c".

Probably nothing serious, but definitely something not quite consistent.

**Comment by Zeugma440** [comment]
I think the issue might be the presence of a text encoding byte and BOMs before every "Element ID".

The spec seems to imply that all "Element ID" frames have to be encoded with ISO-8859-1, and thus don't need any encoding byte nor any BOM.

I'll compare that to the podcasts you pointed to and do more testing.

**Comment by tarrats** [comment]
After coming up with a new file using the new ATL implementation, I can attest it now adds the TIT2 sub-frame, and publishing the podcast still no chapters are displayed in the Apple Podcasts iOS app.

Here is a link that includes a collection of working podcasts and one--not displayin in chapters in Apple Podcastd--that uses the ATL Chapter implemtation: 

[Podcast Test Files](https://we.tl/t-9kZY3fM4uZ)

Thanks!

**Comment by Zeugma440** [comment]
Alright ! The encoding byte I suspected was indeed absent from the files you provided => I removed it definitely.

Now the only difference between ATL implementation and the samples you sent are :
  - The TIT2 subframe of the table of contents (most of them actually don't have it)
  - Two extra zeroes at the end of the CHAP tags (=string null terminator that is in the spec anyway; I really doubt this can be a blocker)

Could you please fetch the latest commit and try once again ?  I feel we're almost there...

If that still doesn't work, I'll remove the extra zeroes and the TIT2 subframe to write 100% identical chapter tags.

**Comment by tarrats** [comment]
I can verify--with such excitement that unfortunately can't be put into words--that the latest commit can successfully render the Chapter section and list each Chapter in the ID3v2 Chapter array in the iOS Apple Podcast App and in Overcast podcast grabber!!!!!!!!!!

The caveat: the fix was tested explicitly using the ID3v2.3 setting (issue #22).  So we're definitely there!  Thanks so much for the brilliant implementation.  I'll be logging separate issues just for completion purposes on some minor enhancements and teenie tiny regression.  KUDOS MAXIMUS!

**Comment by tarrats** [comment]
![iOSAPApp1](https://user-images.githubusercontent.com/36057367/55135504-36a3ce00-5102-11e9-9d54-7f7cf3b6ceb8.jpeg)
![iOSAPApp2](https://user-images.githubusercontent.com/36057367/55135509-386d9180-5102-11e9-958b-0d89744dede9.jpeg)
![iOSOvercastApp1](https://user-images.githubusercontent.com/36057367/55135515-3c99af00-5102-11e9-9579-23354b3cfabe.jpeg)
![iOSOvercastApp2](https://user-images.githubusercontent.com/36057367/55135517-3efc0900-5102-11e9-8c3d-21447be0b481.jpeg)

**Comment by tarrats** [comment]
BTW, and do not quote me on this one but, I believe this might be the first successful Windows-based Chapter implementation for MP3 files!

**Comment by tarrats** [comment]
Funny thing though, analizing the raw CTOC value both the latest version compared to the same file with the old version look identical (save for the new TIT2 subframe of course):

```
"toc\0\u0003)chp0\0chp1\0chp2\0chp3\0chp4\0chp5...
"toc\0\u0003)chp0\0chp1\0chp2\0chp3\0chp4\0chp5...
```

But the byte prior to the first Chapter UniqueID is not NULLED (\0) and in this instance has a closing paren.  Probably not important now,, but just for documenting purposes.

**Comment by Zeugma440** [comment]
Awesome. It warms my heart to see that I'm not the only one to be moved to such lengths by audio metadata  ;-)

As for the CTOC frame, I'll give you a detailed answer later.

**Comment by Zeugma440** [comment]
Concerning the frames you reported, I'm not sure using a character representation is the best way to analyze the contents of data such as ID3 header, which is _binary data_ (as opposed to _text data_ such as XML).

For instance, `\a` is quite hard to understand at first sight, whereas its numeric representation `7` speaks by itself.

To make a long story short, I'd like to advise you to view such files with an hexadecimal editor rather than what you're currently using. I'm using [FrHed](http://frhed.sourceforge.net/en/) for Windows, it's free, it can open ridiculously large files and has all the essential features.

Here's a screenshot of how the CTOC header looks like from my side
![hexEditor](https://user-images.githubusercontent.com/29414549/55190759-c6985500-51a0-11e9-8444-6d7ab7ad71f2.png)

On the left : numeric values of each byte (in hex format)
On the right : character representation of each byte

**Comment by Zeugma440** [comment]
Closing the issue because it's fixed, but we can still go on chatting
