### ISSUE TITLE
Cannot update wav metadata tags (riff_info) on windows 11

### ISSUE THREAD

**Issue by andurshakur** [Zeugma440/atldotnet#238]
I am using version 5.12 of ATL on windows 11 and i am trying to update artist, title and album of a large number of tracks.
It works very smoothly for flac files when using the code below but wav files does not get updated
There are no exceptions raised 
i use the following code:

```
private static void SetTrackMusicProperties(ref Model.Track track)
{
    try
    {
        ATL.Track trackProperties = new ATL.Track(track.Drive + track.Location);
        trackProperties.Artist = track.Artist;
        trackProperties.Title = track.Title;
        trackProperties.Album = track.Artist;
        trackProperties.Save();        
    }
    catch (Exception e)
    {

        throw;
    }
}
```

**Comment by nlogozzo** [comment]
Could you upload the wav file here or provide a link to it?

**Comment by andurshakur** [comment]
i cannot upload wav files here but an example can be grabbed from here:

https://mega.nz/file/1YNUjCYJ#-8e0SeiuRM4aOEARYTSZi7LZY-6vpD-2LmWTTXUGk2o

it happens with all my wave files

**Comment by Zeugma440** [comment]
I have no issue when tagging the WAV file you provided.

Have you tried enabling the ATL logger by calling `new ConsoleLogger()`?

**Comment by andurshakur** [comment]
great news! then i just need to sort out what my local issue is

i cant seem to find any logging options in atl itself
in the debug window i do see this exception: Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
however it doesnt  get caught in my try/catch and not 100% sure its related

**Comment by andurshakur** [comment]
ok so apparently FileInfo DOES lock files until disposed
so got a step further but it still doesnt seem to tag as expected
i get this output now:


========================================
Found 1 regions
#0 : 4->74659580(71,2 MB) IsBufferable = True
========================================
------------ REGION 0
------ ZONE id3 @74659580
Allocating 0 B
newTagSize : 0 B

DONE
========================================
Found 1 regions
#0 : 4->74659580(71,2 MB) IsBufferable = True
========================================
------------ REGION 0
Buffering 71,2 MB
------ ZONE bext@74659580
Allocating 0 B
newTagSize : 0 B
------ ZONE cue @74659580
Allocating 0 B
newTagSize : 0 B
------ ZONE disp.0@74659580
Allocating 0 B
newTagSize : 0 B
------ ZONE iXML@74659580
Allocating 0 B
newTagSize : 0 B
------ ZONE LIST.adtl@74659580
Allocating 0 B
newTagSize : 0 B
------ ZONE LIST.INFO@74659580
Allocating 0 B
newTagSize : 0 B
------ ZONE smpl@74659580
Allocating 0 B
newTagSize : 0 B

DONE

**Comment by andurshakur** [comment]
ok it actually works as expected now so the culprit was FileInfo!
thank you very much for a great library and for your time! <3

**Comment by andurshakur** [comment]
"fun" sidenote is that apparently FileInfo does release filelocks on flac files before disposing of the fileinfo object (since it worked fine with all flac files from the beginning)
