### ISSUE TITLE
MP3 Title contains extra character starting in 5.04

### ISSUE THREAD

**Issue by seankearney** [Zeugma440/atldotnet#242]
## The problem

The MP3's title field contains a trailing `'` whereas v4.33 didn't return this. [Mp3Tag](https://www.mp3tag.de/en/index.html) & Windows Media Player don't show this character either. The tag editor by @nlogozzo (leveraging ATL) shows the character.

![image](https://github.com/Zeugma440/atldotnet/assets/864524/c8d874d5-060e-4b1a-a147-504aa9efcdf7)

## Environment

* The issue started with [🏷️ 5.04](https://github.com/Zeugma440/atldotnet/releases/tag/5.04) @ commit https://github.com/Zeugma440/atldotnet/commit/0bc4513c9e8a52cd1b442446c143e709ff8ca8a3
* Windows 10. net8.0

## Details

I have an application currently using v4.33. In the process of updating to v5.13 we've detected a difference in one of our test files where ATL returns an extra character in the Title field. I've isolated this change as starting with commit https://github.com/Zeugma440/atldotnet/commit/0bc4513c9e8a52cd1b442446c143e709ff8ca8a3.

## Code To Reproduce Issue [ Good To Have ]

I've emailed the sample file to @Zeugma440

**Comment by Zeugma440** [comment]
I couldn't reproduce the issue on my side with the sample track you sent me. However, that sample track is "Good Days" whereas the track on your screenshot is "Soul With a Capital S". Did you upload the wrong one by any chance?

**Comment by seankearney** [comment]
Following up via email.

**Comment by Zeugma440** [comment]
Thanks! It's been fixed for next release.

The title you saw with the `'` at the end is actually **the ID3v1 title**, which has been used as a fallback because the ID3v2 title couldn't be read.

That latter issue was caused by a regression from 2d1685b333de5778a94bd2cfdbb6e9bf9b5f3207 where ID3v2 parsing stopped prematurely because of a malformed Comment field. Those are now properly ignored.

**Comment by Zeugma440** [comment]
The fix is available in today's v5.14~

Please close the issue if you confirm it.

**Comment by seankearney** [comment]
Looks great! Closing. Thank you!!!
