### ISSUE TITLE
Add support ENCODEDBY

### ISSUE THREAD

**Issue by Agagamand** [Zeugma440/atldotnet#245]
This tag is present in ID3v2: https://docs.mp3tag.de/mapping/
This tag automatically adds qaac.exe when converting to .m4a. It shows this program: https://github.com/Martchus/tageditor/

**Comment by Zeugma440** [comment]
Done! Support will be available in next release.

**Comment by Agagamand** [comment]
Maybe at the same time add the ENCODERSETTINGS tag?
I would use it.

**Comment by Zeugma440** [comment]
A few comments:

1/ ENCODEDBY should be used to store the name of someone or an organization who did the encoding. If you're looking to store the name of the software used to encode, you'd need the ENCODER metadata.

2/ WWWAUDIOSOURCE only exists in ID3v2 and thus is not standard among multiple tagging formats. I won't implement it as a property into `IMetadata` and you'll have to manage it using `AdditionalFields`

**Comment by Agagamand** [comment]
> 1/ ENCODEDBY should be used to store the name of someone or an organization who did the encoding. If you're looking to store the name of the software used to encode, you'd need the ENCODER metadata.

Thank you for the information. I really want to save the name of the software used to encode

> WWWAUDIOSOURCE only exists in ID3v2

And ASF/Windows Media: https://docs.mp3tag.de/mapping/

But I do not insist on adding these tags, since in most cases I myself use the ape (for .tak) and mp4 (for AAC) tags.

**Comment by Agagamand** [comment]
I found an interesting table: https://wiki.hydrogenaud.io/index.php?title=Tag_Mapping

Consider adding tags: CatalogNumber, RecordingDate

**Comment by Zeugma440** [comment]
> I found an interesting table: https://wiki.hydrogenaud.io/index.php?title=Tag_Mapping

That's my reference, actually 👍 

> Consider adding tags: CatalogNumber, RecordingDate

err... do you _really_ need all of these or do you enjoy making me jump into a different hoop every six hour?

**Comment by Agagamand** [comment]
> do you _really_ need all of these

Yes. I have only listed what I will use.
I add all known information about the track and album to the tags. The listed tags will not be enough for me, but I haven’t found any more standard tags that suit me.

**Comment by Zeugma440** [comment]
All's available on today's v5.16

Please close the issue if you're okay with the changes

**Comment by Zeugma440** [comment]
A few extra comments regarding what you asked for :
- **Recording date** has been available since the beginning : `Track.Year` and `Track.Date`
- As you can see in https://wiki.hydrogenaud.io/index.php?title=Tag_Mapping, **Encoder settings** share the same field as **Encoder** in ID3v2. I decided just to provide `Track.Encoder` to keep things simple
