### ISSUE TITLE
get image

### ISSUE THREAD

**Issue by kadirguloglu** [Zeugma440/atldotnet#246]
## The problem

How can I get any duration I want in video files as an image? For example, I want to get 00:13 seconds of the file as an image.

**Comment by Zeugma440** [comment]
Hi there,

First of all, the "A" in "ATL" means "Audio". If you read the welcome page, you'll see that the library doesn't handle video formats but audio formats.

Even if it did, ATL will only give you the duration in seconds or milliseconds. You'll have to convert it to an image yourself using a 3rd party library.

I'm closing that issue as off-topic.
