### ISSUE TITLE
wav file duration is not determined

### ISSUE THREAD

**Issue by cadavrezzz** [Zeugma440/atldotnet#248]
## The problem

wav file duration is not determined

## Environment

* ATL version 5.17.0
* OS/version Win10 x64
[Sound_21143_Pink_Noise.zip](https://github.com/Zeugma440/atldotnet/files/14095393/Sound_21143_Pink_Noise.zip)

**Comment by Zeugma440** [comment]
Thanks for the file. It had a tiny `DISP` chunk that ATL failed to skip because of a wrong check. 

I've fixed that in today's v5.18 ✅ 

Please close the issue if it works on your side 😄

**Comment by cadavrezzz** [comment]
All ok! Works!
