### ISSUE TITLE
TIT2 CTOC subframe is missing from the Chapters implementation

### ISSUE THREAD

**Issue by tarrats** [Zeugma440/atldotnet#25]
## The problem

There seems to be no support for, or at least no way to explicitly add, the optional TIT2 CTOC subframe for ATL's Chapter implementation.

## Environment

* ATL version (or git revision) that exhibits the issue: 2.7
* Last ATL version that did not exhibit the issue (if applicable): N/A
* OS/version used to run ATL: Windows 10 x64, v1803, build 17134.648

## Details

By default, the TIT2 CTOC subframe is not present when persisting a file with at least one chapter using ATL:

```
{[CTOC, toc
CTOC
toc\0\u0003\u0003chp0\0chp1\0chp2
```

There should be a way for adding the TIT2 CTOC frame

**Comment by tarrats** [comment]
As of the latest master branch 2.8, the TIT2 CTOC subframe is concatenated after the last CHAPTERID:

```
{[CTOC, toc
CTOC
toc\0\u0003)chp0\0chp1\0chp2\0chp3\0chp4\0chp5\0TIT2\0\0\0'\0\0\u0001ÿþT\0a\0b\0l\0e\0 \0o\0f\0 \0C\0o\0n\0t\0e\0n\0t\0s
```

This issue is FIXED

**Comment by Zeugma440** [comment]
Fine :)
