### ISSUE TITLE
long .ogg file loading

### ISSUE THREAD

**Issue by Tangenten** [Zeugma440/atldotnet#250]
I'm opening a .ogg file in the following manner 
```
Track test = new Track("path\\to\\wAchievement.ogg");
```
And it takes a *very* long time for the Track to load. 13 minutes on my system.
This is the file im trying to open, it happens on other .ogg files aswell.
`https://www.dropbox.com/scl/fi/ejjl2ixxittda5c72hxpm/wAchievement.ogg?rlkey=b5coldri7kn4csyulnwzqo5dh&dl=0`
A fix or a workaround would be appreciated (:

ATL version: 5.18.0
OS: Windows 11

**Comment by Zeugma440** [comment]
There was a double issue :
- Your OGG file isn't an OGG file at all but a WAV file
- ATL failed to detect that early and tried to process it as an OGG file

That issue will be fixed on next release ✅

**Comment by Zeugma440** [comment]
Available in today's v5.19

Please close the issue if it works on your side~

**Comment by Zeugma440** [comment]
No feedback from the OP for more than 30 days => Closed
