### ISSUE TITLE
Doesn't work with .mp4

### ISSUE THREAD

**Issue by Agagamand** [Zeugma440/atldotnet#255]
I'm trying to to add tags to a .mp4 file that contains video and audio. But ATL does not do this.

The file is for example: https://workupload.com/file/ByqP86kr6dk

**Comment by nlogozzo** [comment]
ATL stands for Audio Tools Library...it supports audio-only files.

**Comment by nlogozzo** [comment]
Although video files do contain audio, their tag structures are often different than pure audio only files because the videos themselves can also be tagged

**Comment by Zeugma440** [comment]
> I'm trying to to add tags to a .mp4 file that contains video and audio. But ATL does not do this.

I've just successfuly tried adding an album and a title on your file. What doesn't work exactly?

> Although video files do contain audio, their tag structures are often different than pure audio only files because the videos themselves can also be tagged

ATL should theoretically be able to handle OGG and MP4 videos even though there's none of them on the unit tests. 
For your information :
- The OGG container does differentiate tagging between audio and video streams
- The MP4 container does not, as the `moov.udta` atom that carries metadata is independent from `moov.trak` atoms that contain stream descriptions

**Comment by Agagamand** [comment]
> What doesn't work exactly?

Try this:

```
            Track inputTrack = new(@"R:\Нужно прекращять врать.mp4");
            inputTrack.AdditionalFields["REPLAYGAIN_REFERENCE_LOUDNESS"] = $"-23 LUFS";
            inputTrack.AdditionalFields["REPLAYGAIN_ALGORITHM"] = "ITU-R BS.1770";
            inputTrack.Save();
```

**Comment by Zeugma440** [comment]
I confirm that MP3tag doesn't detect it, but MediaInfo and VLC do.

![image](https://github.com/Zeugma440/atldotnet/assets/29414549/408d6e26-7fda-4bba-b745-2fa6bdb72c72)

![image](https://github.com/Zeugma440/atldotnet/assets/29414549/d0451c7f-6e06-4985-93a1-083a25f57f87)

We're in a very specific domain there. My guess would be that the default namespace written by ATL is not the correct one.

Do you have a file where those fields are set _and_ can be read from MP3Tag?

**Comment by Agagamand** [comment]
No. But these fields can be set through MP3Tag. What namespace does it use?

I'd also like to to draw attention to the fact that the tags that [RSGain](https://github.com/complexlogic/rsgain) writes, MP3Tag sees.

**Comment by Zeugma440** [comment]
> What namespace does it use?

I wouldn't ask if I knew... and MP3tag isn't exactly a reference when it comes to writing specialized M4A/MP4 tags. I'd rather do tests with Apple apps or specific products such as RSGain.

> I'd also like to to draw attention to the fact that the tags that [RSGain](https://github.com/complexlogic/rsgain) writes, MP3Tag sees.

The RSGain readme is gigantic. Could you please provide a ready-to-run command line or a tagged file ?

**Comment by Agagamand** [comment]
`rsgain.exe custom --tagmode=i --loudness=-23 --clip-mode=n --album --max-peak=-1,0 --true-peak --opus-mode=s "Нужно прекращять врать.mp4"`

**Comment by Zeugma440** [comment]
Here's what I did :

![image](https://github.com/Zeugma440/atldotnet/assets/29414549/ca4998b4-6244-4dcc-96bf-8a321c9ca1ca)

NB : Don't mind the `????`'s; my system default charset is plain old boring Latin-1 😉 

What MP3tag sees after that are not the metadata we talked about, but the resulting ReplayGain values :

![image](https://github.com/Zeugma440/atldotnet/assets/29414549/7f3b428a-2892-4eea-abf0-83a102169f5d)

MediaInfo finds the same information :

![image](https://github.com/Zeugma440/atldotnet/assets/29414549/3b4c634b-9b52-49b8-bf73-26b292a13e36)

Are you sure you're not mistaking the input parameters for ReplayGain calculation with the output values of that calculation?

**Comment by Agagamand** [comment]
> What MP3tag sees after that are not the metadata we talked about, but the resulting ReplayGain values

Is there a difference? The input ReplayGain calculation parameters are not written to "AdditionalFields"?

**Comment by Zeugma440** [comment]
> The input ReplayGain calculation parameters are not written to "AdditionalFields"?

RSGain does not write input parameters to the target file after running that command line. Here are the insides of the resulting file :

![image](https://github.com/Zeugma440/atldotnet/assets/29414549/c7eebdc5-f33a-4f69-9364-91ac07b3def2)

You can see we have our 4 output values, but no REPLAYGAIN_REFERENCE_LOUDNESS, nor REPLAYGAIN_ALGORITHM.

Are you sure you gave me the correct command line?

***

If you want to add those _manually_ using ATL, the code you submitted earlier is the right way to go. I have no idea why MP3tag does not read them, nor do I know how to add them using MP3tag either.

**Comment by Agagamand** [comment]
Checked it out. It's probably an error in the MP3Tag.

I'm sorry for the inconvenience.


P.S.
> NB : Don't mind the `????`'s; my system default charset is plain old boring Latin-1

Activating the encoding in Windows UTF8 may help

**Comment by Zeugma440** [comment]
No problem man 👍 

> Activating the encoding in Windows UTF8 may help

Thanks. I only have that issue on some apps. As long as Windows Explorer works properly, it should be fine.
