### ISSUE TITLE
track artist has invisible spaces?

### ISSUE THREAD

**Issue by orbittwz** [Zeugma440/atldotnet#258]
Hey there!
Using ATL 4.36 here...
Reading this mp3 track and parsing the track artist and title gets me this:
ARTIST -- "Britney Spears        "
TITLE -- "Me Against The Music (Dragon M"

![image](https://github.com/Zeugma440/atldotnet/assets/45605734/905ca014-3345-442d-b1bf-0552d3648ab0)

notice the spaces using your library, counted 8 spaces...
whereas in MP3Tag, there are none, and none when copying the value and pasting it to notepad for example, zero spaces.
i was wondering if that's a bug when the ID3 is lyrics?
anyways, here is the file:

another example, this time it's both ARTIST and TITLE having spaces, whereas in MP3Tag there are none.
ARTIST -- "Britney Spears        "
TITLE -- "Me Against the Music     "

Would be nice if you check this... thanks

**Comment by Zeugma440** [comment]
Thanks for your feedback. Having the files themselves to be able to test is super useful, but uploading them on Github directly -especially copyrighted pop music- is super risky for us.

I've downloaded the files and removed the links you posted. Next time, please use a 3rd party host. 
Thanks for your understanding.

**Comment by Zeugma440** [comment]
The **first file** (`dragon_man_radio_mix)-twc`) is only tagged with an ID3v1 tag, which is its sole source of metadata.

According to the ID3v1 specifications, every field has a fixed length. When the useful size of the metadata is smaller than the field's maximum fixed length, the remaining bytes should be filled with `\0`.

On the file you submitted, the remaining bytes are not filled with `\0`'s but _with spaces_, which are read by ATL.

If you want them to disappear, you're welcome to trim them on your app's side.

![image](https://github.com/Zeugma440/atldotnet/assets/29414549/f4d16d2d-419d-41da-b06c-e79c2868e934)

---

The **second file** (`ksi`) is tagged with both ID3v1 _and_ ID3v2 tags. 
- By default, ATL uses the richest metadata provider, which is ID3v2. I read it on my side and didn't see any issue with extra trailing spaces
- I tried to read ID3v1 only, and didn't see any issue either as ID3v1 trailing bytes are filled with `\0`'s on that file

![image](https://github.com/Zeugma440/atldotnet/assets/29414549/ab58078e-b040-4a17-9203-22048d9a0d7c)

Are you sure you sent me the correct file?

**Comment by orbittwz** [comment]
![image](https://github.com/Zeugma440/atldotnet/assets/45605734/c6ebe7b0-45e2-4ca1-afb6-30959f8715f9)
Hey thanks for the info.
For KSI, I think it was the 2nd file?

**Comment by orbittwz** [comment]
https://www.mediafire.com/file/4n9zhig5n9vyl8l/02-britney_spears-me_against_the_music_(call-out_hook)-ksi.mp3/file

**Comment by Zeugma440** [comment]
Thanks. The new file you just sent is in the very same situation as the 1st file : ID3v1 tag only, with spaces as trailing bytes.

**Comment by orbittwz** [comment]
no problems, I used Trim() method on artist and title and that should solve my issue.
have a nice day!
