### ISSUE TITLE
[ENHANCEMENT] setting for explicitly adding the TIT2 CTOC subframe 

### ISSUE THREAD

**Issue by tarrats** [Zeugma440/atldotnet#26]
## The problem

Now that TIT2 CTOC subframe is added, and following the behaviour from issue #3, it might be nice--and also nice for testing purposes--to have a global setting for explicitly ADDING said subframe.

## Environment

* ATL version (or git revision) that exhibits the issue: 2.8 (master branch)
* Last ATL version that did not exhibit the issue (if applicable): N/A
* OS/version used to run ATL: Windows 10 x64, v1803, build 17134.648

## Details

Probably something along the lines of:

`public static bool ID3v2_alwaysWriteTIT2SubFrame = true;   `

It would be extra cool--again for testing or even branding purposes--to be also able to define the actual TIT2 string, as right now it's set to:

`Table of Contents`

So rather something like:

`public static char[8] ID3v2_TIT2SubFrame = 'Contents';   `

Just a thought of course

**Comment by Zeugma440** [comment]
I completely see your point. Regarding implementation, I'd rather avoid putting too many features in the ` Settings` class, as its very existence goes against best practices.

I'd rather add a `TableOfContentsTitle` property in the `ChapterInfo` class. I'll keep you updated.

**Comment by Zeugma440** [comment]
Hey there,

There's a new `Track.ChaptersTableDescription` field that allows to set the TIT2 subframe inside CTOC.

Please tell me if it works as you expect.

Cheers,

**Comment by tarrats** [comment]
It seems that as of the last master branch committ, the CTOC Additional Field cannot be listed nor read while debugging and adding a watch to ATL.Track theTrack or when using:

```
foreach (System.Collections.Generic.KeyValuePair<string, string> field in theTrack.AdditionalFields)
{
	System.Console.WriteLine("Field " + field.Key + " : value = " + field.Value);
}
```

I'll be confirming in this particular instace, but without the CTOC frame, even when ID3v2 contains all chapters, no chapter information is displayed in podcast grabbers.  Thanks!

**Comment by Zeugma440** [comment]
You are right, CTOC does not appear as an additional field anymore. It is part of the changes.

However, the files should definitely be tagged with it if `Settings.ID3v2_alwaysWriteCTOCFrame` is set to `true` (its default value).

Is it important for your app to detect CTOC presence through `AdditionalFields` ?  Or did you do it just to help me fix the library ?

**Comment by tarrats** [comment]
Not really, it was just to reggress-test, `AdditionalFields` made it quite easy to test the `toc `string; however, if there is somewhere else I can look at this string I can validate that `Track.ChaptersTableDescription` works as expected, although something tells me you already added a test case for this in the code :) so not a biggie.  Cheers!

**Comment by Zeugma440** [comment]
The designed behaviour is as follows :
- If `Settings.ID3v2_alwaysWriteCTOCFrame` is `true` and there is at least 1 chapter, the `CTOC` frame is written
- Then, if `Track.ChaptersTableDescription` is different than `""` (empty string), then the `TIT2` subframe if written

Current unit tests make sure it behaves like this.

---

As a consequence :
- Setting `Track.ChaptersTableDescription` alone without having any chapter shouldn't write any `CTOC` frame
- Setting If `Settings.ID3v2_alwaysWriteCTOCFrame` to `true` and at least 1 chapter without setting `Track.ChaptersTableDescription` shouldn't write any ` TIT2` subframe

Current unit tests aren't exactly written to verify that; I'll do the necessary.

**Comment by tarrats** [comment]
Sounds perfect.  Given the behaviour I can attest that the Chapter ipmlementation works with and without the TIT2 sub-frame.  Thanks again!

**Comment by Zeugma440** [comment]
The remaining unit tests have been set up. Closing the issue.
