### ISSUE TITLE
thisChapter.Url no longer behaves as a hyperlink

### ISSUE THREAD

**Issue by tarrats** [Zeugma440/atldotnet#27]
## The problem

Before the main branch 2.8 and all fixes, whenever in a podcast grabber supporting Chapters, if a chapter contained a well-formed hyperlink string for Url, clicking  on the chapter text acted as a valid hyperlink taking you to the desired URL.

## Environment

ATL version (or git revision) that exhibits the issue: **2.8 (main branch)**
Last ATL version that did not exhibit the issue (if applicable): **2.7**
OS/version used to run ATL: **Windows 10 x64, v1803, build 17134.648**

## Details

Following the convention for Chapter supported podcasts, the string value in the Chapter Url was of the form:

` thisChapter.Url = "chapter url\0http://github.com/";`

Which in a podcast grabber like Overcast (which supports Url) clicking the chapter gave way to the URL by clicking on it.

However, after v2.8 (main branch) the expected behaviour regressed, and no longer URL values are displayed, let alone have hyperlink functionality.

## Code To Reproduce Issue

1. Update a file with at least one chapter and the Url value != "":

```
using ATL.AudioData;

AudioDataManager theFile = new AudioDataManager(AudioDataIOFactory.GetInstance().GetFromPath(fileName));

TagData theTag = new TagData();
theTag.Chapters = new System.Collections.Generic.List<ChapterInfo>();

ChapterInfo ch = new ChapterInfo();
ch.StartTime = 0;
ch.StartOffset = 4294967295;
ch.EndTime = 12000;
ch.EndOffset = 4294967295;
ch.UniqueID = "chp0";
ch.Title = "Chapter 1";
ch.Subtitle = "";
ch.Url = "chapter url\0http://github.com/";
theTag.Chapters.Add(ch);
```
2. Publish the resulting file in a Podcast RSS
3. Use a podcast grabber like Overcast to visualize the newly updated RSS
4. Play file and attempt to click on the chapter

**Expected**
* Overcast opening the http://github.com page

**Result**
* The chapter isn't clickable, it appears in plain text hence no webpage is displayed

**Comment by tarrats** [comment]
with v2.7 the hyperlinks displayed as such and were clickable:
![54904590-47133900-4eb5-11e9-9a8a-e51e5077750a](https://user-images.githubusercontent.com/36057367/55141239-58a44d00-5110-11e9-8f53-2f97bc2115a3.jpg)

in v2.8 (main branch) they no longer appear as clickable:
![55135515-3c99af00-5102-11e9-9579-23354b3cfabe](https://user-images.githubusercontent.com/36057367/55141323-8d180900-5110-11e9-8a91-b23ad7037263.jpg)

**Comment by tarrats** [comment]
The following link contains two files, one whose URLs are behaving as expected: **Overtime-40-Alana-Louise.mp3** and the other one: **El-Chilanyorker-22.03.19.mp3** recently updated with ATL v2.8 (main branch) showing the bug regression:

[Issue #27 test files](https://we.tl/t-jUrL3R6wIW)

As always, thanks so much!

**Comment by Zeugma440** [comment]
I've made the whole thing cleaner : instead of putting a `\0` in the middle of the string, you have now to use `ChapterInfo.UrlInfo`.

Your code should now be 
`ch.Url = new ChapterInfo.UrlInfo("chapter ur","http://github.com/");` 
or even
`ch.Url = new ChapterInfo.UrlInfo("http://github.com/");`

The old `string Url` property does not work anymore.


Please tell me if that works better for you.

**Comment by tarrats** [comment]
GREAT!  I'll let you know how it goes, but usability-wise it sounds amazing.

**Comment by tarrats** [comment]
Unfortunately, the urls still aren't presented to the user as hyperlinks and hence cannot be clicked.  I have some files using the previous ATL commits where URL worked like a charm in case you'd like those to compare to the files with the latest commit.  Cheers!

**Comment by Zeugma440** [comment]
Thanks for checking !

The difference is older files use ID3v2.4 and UTF-8 encoding whereas new files use ID3v.2.3 and UTF-16 encoding. I'll do some more research and have another close look to the "Overtime" podcast sample you provided.

**Comment by tarrats** [comment]
I too thought it was something to do with encoding, just bear in mind that back when ATL saved the files using ID3v2.4 I explicitly had to update the file and demote it to ID3v2.3 for podcast publication, at which point the hyperlinks did work.

If you need a file vesrion with working hyperlinks embedded by ATL, but explicitly demoted to ID3v2.3 please let me know!

**Comment by Zeugma440** [comment]
It seems that all the files you provided that contain chapters URLs have their URL description encoded in plain ISO-8859-1.

Although the spec allows to encode that field in unicode, I have the feeling the _de facto_ norm is not to bother with fancy encodings => I've adjusted the implementation accordingly

Could you tell me if that works better for you ?

**Comment by tarrats** [comment]
It now works as expected, the Url is displayed as a hyperlink, said hyperlink is clickable, and the destination conforms with the provided Url in `UrlInfo`.

Thank you so much!

**Comment by Zeugma440** [comment]
Great :-)  I also have to thank you for your patience while solving these issues.
