### ISSUE TITLE
Syntax for writing Cart Chunk metadata?

### ISSUE THREAD

**Issue by livvy94** [Zeugma440/atldotnet#270]
## The problem

For context, I work at a radio station and have some background in programming. I'd like to create a tool that periodically scans a folder for newly created WAV files, opens them, and and adds Cart Chunk data to them based on the filename. The Cut ID is always the same as the filename - so `00006.WAV` would get a certain `Title`, `Start Date` (which is always the date I record the cut), `Outcue`, and `End Date`. 

There isn't any mention of Cart Chunk data in the [Code Snippets](https://github.com/Zeugma440/atldotnet/wiki/3.-Usage-_-Code-snippets) page, could I have an example?

I am also interested in making a different tool that works with Super Nintendo SPC700 files, which I am honestly surprised and overjoyed to see supported here. I make [SNES chiptune music](https://www.youtube.com/watch?v=11Yo1P7_LUM) in my free time!

I don't see a lot of Issues asking for help like this, so I hope I'm not asking in the wrong way. Thank you for making such a comprehensive library!

## Environment

* ATL version 5.25 (latest on NuGet)
* OS: Windows 11 64-bit

**Comment by Zeugma440** [comment]
Hi there! I'm glad you appreciate the library~

Regarding CART, there's no snippet for the moment but you can guess what to write by looking at :
- [the generic WAV snippet](https://github.com/Zeugma440/atldotnet/wiki/3.-Usage-_-Code-snippets#broadcastWave)
- [the list of supported CART fields](https://github.com/Zeugma440/atldotnet/blob/3e5dd2d2c4b3c62b6b207dd599072ed981ac6ae9/ATL.unit-test/IO/MetaData/WAV.cs#L200)

=>For instance, to store the Cut Number alone, you'd write
```cs
theTrack.AdditionalFields["cart.cutNumber"] = "123456";
theTrack.Save();
```

***

Editing SPC700 files is done using the standard fields (e.g. `Track.Title`, `Track.Artist`)...


Please let me know if you need more information!

**Comment by livvy94** [comment]
Hello! I was able to implement what I had in mind! I'm adding a few more bells and whistles and then I'm going to make a repo for what I've got after removing things that are specific to the radio station I work at/any identifying information.

One more question - is there a way to check if a Cart Chunk is present in a loaded file? I just thought I'd ask if there was a better way, right now I'm using the following:
```csharp
private bool CartChunkAlreadyExists(Track track)
{
    return track.AdditionalFields.TryGetValue("cart.title", out var _);
}
```

**Comment by Zeugma440** [comment]
Good news!!

There are internal variable to test what you describe more directly, but none is visible from the public API... and even if they would, you wouldn't get any performance gain.
What you've done is completely fine 👍

**Comment by Zeugma440** [comment]
Don't hesitate to close the issue if everything works for you~

**Comment by Zeugma440** [comment]
No answer from the OP for one month => Closed

Don't hesitate to open a new Issue or a new Discussion if you need anything~
