### ISSUE TITLE
FLAC files with artwork embedded by ATL fails flac -t

### ISSUE THREAD

**Issue by GOATS2K** [Zeugma440/atldotnet#272]
## The problem

The FLAC integrity test fails on files with artwork that is embedded by ATL.

## Environment

* ATL version (or git revision) that exhibits the issue: 5.25.0
* Last ATL version that did not exhibit the issue (if applicable): N/A
* OS/version used to run ATL: macOS Sonoma 14.5

## Details

You can reproduce this by first finding a FLAC file that passes `flac -t file.flac`.

```
➜ flac -t 01\ -\ Submorphics\ \&\ Lenzman\ -\ Echoes\ of\ November.flac

flac 1.4.3
Copyright (C) 2000-2009  Josh Coalson, 2011-2023  Xiph.Org Foundation
flac comes with ABSOLUTELY NO WARRANTY.  This is free software, and you are
welcome to redistribute it under certain conditions.  Type `flac' for details.

01 - Submorphics & Lenzman - Echoes of November.flac: ok
```

Then using ATL to embed artwork like this:
```csharp
public async Task WriteArtwork(string filePath, Stream artworkStream)
{
    var memoryStream = new MemoryStream();
    await artworkStream.CopyToAsync(memoryStream);
    
    var track = new ATL.Track(filePath);
    var pictureEmbed = PictureInfo.fromBinaryData(memoryStream.ToArray(),
        PictureInfo.PIC_TYPE.Front,
        MetaDataIOFactory.TagType.RECOMMENDED);
    
    track.EmbeddedPictures.Add(pictureEmbed);
    track.Save();
}
```

Observe that `flac -t` now fails with the following error:

```
01 - Submorphics & Lenzman - Echoes of November.flac: *** Got error code 0:FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC


01 - Submorphics & Lenzman - Echoes of November.flac: ERROR while decoding data
                                          state = FLAC__STREAM_DECODER_ABORTED
```

**Comment by Zeugma440** [comment]
Roger that. I'm gonna take care of it in a few weeks as I'm currently on holidays 😎

**Comment by GOATS2K** [comment]
Enjoy your holiday!

**Comment by Zeugma440** [comment]
Hi there~

Maybe I'm out of luck, but I just tried on two very different FLAC files, and suceeded the check after adding the cover.

Could you please send me that FLAC file you're using through a 3rd party file hosting service? My address is (my Github username) [at] (not-cold)mail [dot] com

**Comment by GOATS2K** [comment]
Did you use the latest flac version? I've found the strictness to vary a
bit between versions.

**Comment by Zeugma440** [comment]
I used the flac command line exe v1.4.3

**Comment by GOATS2K** [comment]
Okay, I'll send you the files!

**Comment by GOATS2K** [comment]
Check your email! :)

**Comment by Zeugma440** [comment]
Thanks for the files (let's call them OK file and KO file)!

- I can reproduce `flac -t` detecting the KO file as corrupted.
- I cannot reproduce your issue by embedding a cover in the OK file once.
- I _can_ reproduce your issue by embedding a cover in the OK file _twice_ 😅.

I'll fix that very soon and let you know~

PS : I noticed you're calling `Track.Save()` inside an `async` method. Did you see there's a `Track.SaveAsync()` method?

**Comment by GOATS2K** [comment]
Yes, however I recalled that SaveAsync was slower than sync Save - so I use
the sync Save method instead.

That sounds about right, I store the general metadata first and then the
artwork if it is present, so that explains why saving it twice reproduces
the issue. Thanks for figuring it out!

**Comment by Zeugma440** [comment]
Fix is done; however I have to tell you that your code will add multiple versions of the same picture to your file, as you call `track.EmbeddedPictures.Add(pictureEmbed);` on top of a file that might already have that image embedded, and FLAC specs allow for multiple front covers inside the same file.

> I recalled that SaveAsync was slower than sync Save 

That's for sure. However, as you're working on FLAC files, did you customize `Settings.FileBufferSize` to something bigger than the default, say 2MB? That one setting plays a big role in performance.

**Comment by GOATS2K** [comment]
Yep, changing buffer sizes made a huge difference in performance. Looking
forward to trying out your fix soon! :)

**Comment by Zeugma440** [comment]
You can try it with today's v5.26.

Please close the issue if it works on your side~

**Comment by GOATS2K** [comment]
Yep, that works! Thank you for the fix!
