### ISSUE TITLE
SaveTo() cannot overwrite Audio itself

### ISSUE THREAD

**Issue by Mapaler** [Zeugma440/atldotnet#273]
## The problem

If you save to the original file name with `SaveTo()`, you will get a file occupied error.
![devenv_Audi_MMI_MP3_Cover_Repair_(正在调试)_-_Microsoft_Visua_0350](https://github.com/user-attachments/assets/ad619383-e003-4756-a9fd-a76252828275)

## Environment

* ATL [5.26](https://github.com/Zeugma440/atldotnet/releases/tag/5.26)

## Details

It's a hassle for users to memorize two APIs

So I tried to use the same path to test if I could successfully modify the file, and sure enough, the file was occupied error.

Are you considering optimizing this situation? For example, when an empty path or same path with original file, redirect to `Save()`

#### Pseudocode
```js
class Track {
	SaveTo(path) {
		if (path == null || path == this.Path) {
			this.Save();
			return;
		}
		//other code
	}
}
```
> If need to be more rigorous, because there are symbolic links, you need to determine whether two files will still point to the same physical address in different paths. Of course, this is relatively rare, and it is not necessary to do it.

**Comment by Zeugma440** [comment]
You suggest doing extra filesystem checks based on...
- The given and current path 
- The given and current `Stream`
...to detect if the client app asks to save data to the same location it reads from.

These checks have very little added value regarding the main purpose of ATL, which is audio metadata manipulation. They would add a significant overhead everytime `SaveTo` is called (as file I/O tends to be expensive), which is not what the majority of users expect.

=> In my humble opinion, that's something the client app should do, not the library.

**Comment by Mapaler** [comment]
> They would add a significant overhead everytime `SaveTo` is called (as file I/O tends to be expensive).
> 
> that's something the client app should do, not the library.

I agree with that, and I'm prepared to do so in my own program.

I'm just a layman, thinking is a weakly typed, non-function-overloaded JS language. So I often run into common mistakes for newbies.

Please add a tutorial on this situation in the documentation.

**Comment by Zeugma440** [comment]
> thinking is a weakly typed, non-function-overloaded JS language. So I often run into common mistakes for newbies.

😂 No problem man, I'm in for any type of debate as long as we keep it professional

> Please add a tutorial on this situation in the documentation.

I've just added extra documentation and simple checks on the method itself : b99ac3a36a193938463313a1f1ec04780ea14e20

What else would you need?

**Comment by Mapaler** [comment]
Thank you very much.

I'm doing a simple judgment on the path in my program, which should prevent most problems.
https://github.com/Mapaler/Audi-MMI-MP3-Cover-Repair/blob/45f24e2494392328a90a0ea80dc452f676b8d8dd/Audi%20MMI%20MP3%20Cover%20Repair/Program.cs#L219

For me, C# is too much trouble compared to JS.

**Comment by Zeugma440** [comment]
That's a handy app you made there. Kudos!

> For me, C# is too much trouble compared to JS.

Frontend and backend languages do not come from the same planet, definitely. And consider yourself lucky that you didn't have to use Java 😒 🤣
