### ISSUE TITLE
NullReferenceException when creating a Track with WebM file

### ISSUE THREAD

**Issue by datvm** [Zeugma440/atldotnet#275]
## The problem

When calling `var track = new ATL.Track(stream);`, a `NullReferenceException` is thrown with the following stack trace:

```
   at ATL.AudioData.IO.MKA.get_AudioFormat()
   at ATL.AudioData.IO.MetaDataIO.get_MetadataFormats()
   at ATL.Track.Update(Boolean onlyReadEmbeddedPictures)
   at ATL.Track..ctor(Stream stream, String mimeType)
  // My calling code
```

This is the file (made by Javascript MediaRecorder API):

[recording.zip](https://github.com/user-attachments/files/16872627/recording.zip)

## Environment

* ATL version (or git revision) that exhibits the issue: 6.2.0
* Last ATL version that did not exhibit the issue (if applicable): N/A
* OS/version used to run ATL: Windows 11

## Details

UPDATE: I just noticed that by appending chunks of data from `MediaRecorder`, there is no header in the file. I guess that's why it's not working.

## Code To Reproduce Issue [ Good To Have ]

```cs
const string Path = @"C:\Users\lukev\Downloads\recording.webm";
await using var stream = File.OpenRead(Path);
var track = new Track(stream);
```

**Comment by Zeugma440** [comment]
First of all, thanks for your feedback (and for the sample file)!

Looks like the file you submitted has a combination of various things that weren't present among my test data.

I've done all the required fixes. However, as for foobar2000 and VLC, ATL can't guess the duration of your audio just by reading raw Opus data. I don't even know if it's possible to infer any useful metadata from raw Opus data 😅

**Comment by datvm** [comment]
Thank you very much! So I actually had to fix it at client-side as well and add the Duration metadata that Chrome missed. Surprisingly, iOS' output `.mp4` is also missing the duration but there is no exception thrown.

I see you are working on `SpawnDev.EBML` repo as well, I am also using it on my server to validate WebM files ahead of ATL because somehow ATL misses the Duration from these files.

**Comment by Zeugma440** [comment]
The fix is available on today's v6.03.

> I see you are working on SpawnDev.EBML repo as well, I am also using it on my server to validate WebM files ahead of ATL because somehow ATL misses the Duration from these files.

I actually dropped SpawnDev.EBML as I understood how to process EBML / Matroska with my own toolset. 

Did you say you are somehow able to grab the duration from the file you attached on this issue?

**Comment by datvm** [comment]
Thank you very much. This is how I 'fixed' the file: https://stackoverflow.com/a/67823820/653457

**Comment by Zeugma440** [comment]
Oh, you mean the technique used by [SpawnDev.EBML v1](https://github.com/LostBeard/SpawnDev.EBML/blob/24ec60ce366a16d5ed429d51efc5c772f6c19781/SpawnDev.EBML/WebM/WebMDocumentReader.cs#L221)?

I'll see if I can add that to ATL if other techniques fail.

PS : If you're okay with your initial problem, please consider closing the issue 😉

**Comment by datvm** [comment]
@Zeugma440 Thank you very much, yes this issue is resolved. In case you can somehow get the duration from a file without such header, may I ask if it's too much work if the duration from a duration-header-less MP4 (audio only) file can be acquired as well? Here is an example file produced by iOS Safari's MediaRecorder. Thank you very much.

[ios-recording.zip](https://github.com/user-attachments/files/16905190/ios-recording.zip)

**Comment by Zeugma440** [comment]
> @Zeugma440 Thank you very much, yes this issue is resolved. In case you can somehow get the duration from a file without such header, may I ask if it's too much work if the duration from a duration-header-less MP4 (audio only) file can be acquired as well? Here is an example file produced by iOS Safari's MediaRecorder. Thank you very much.

That's definitely feasible by doing pretty much the same thing, but within the MP4/M4A data structure (`stss` and its siblings playing the role of `Cluster`) 😄 

I'll ping you when I'm satisfied with the results. Thanks for the sample as always!

**Comment by Zeugma440** [comment]
That's done for that sample of yours. The interesting data was under the `moof` atom.

Could I ask you to provide me a much smaller file (<500KB) from iOS Safari's MediaRecorder so that I can add it to my unit tests? 🙏

**Comment by Zeugma440** [comment]
> Could I ask you to provide me a much smaller file

Nevermind, I managed on my own by truncating raw audio data

**Comment by Zeugma440** [comment]
> Oh, you mean the technique used by [SpawnDev.EBML v1](https://github.com/LostBeard/SpawnDev.EBML/blob/24ec60ce366a16d5ed429d51efc5c772f6c19781/SpawnDev.EBML/WebM/WebMDocumentReader.cs#L221)?
> 
> I'll see if I can add that to ATL if other techniques fail.

Done as well 😉

**Comment by datvm** [comment]
@Zeugma440 thank you very much. Here's the file you asked for:

[ios-recording-short.zip](https://github.com/user-attachments/files/16917123/ios-recording-short.zip)

Btw, in the end I had to use FFProbe/FFMpeg anyway to fix the file because I need to forward the file to another external API and the API couldn't parse it without re-encoding with FFMpeg (it's pretty fast using `-c:a copy -vn`.

**Comment by Zeugma440** [comment]
No problem. These fixes are generic and will be useful for all other clients.
