### ISSUE TITLE
Bug in get some info about file

### ISSUE THREAD

**Issue by Smiuv** [Zeugma440/atldotnet#279]
Hello, this bug is in the latest version of the library.
When loading an audio file in m4a format, all the tags are loaded correctly, but the problem in the song information such as channels (the channels are null) and the same bit rate is not clear.
And another important point is that the track time is a very large negative number like -8664646.

Thank you for your time

**Comment by Zeugma440** [comment]
Thanks fo ryour feedback. Could you please share that file using a 3rd party host?

**Comment by Smiuv** [comment]
Sure.

**Comment by Zeugma440** [comment]
I'm about to release a new version in the following days. I won't embark this fix if you don't send any file for me to diagnose.

**Comment by Smiuv** [comment]
I emailed it to you, I think you didn't check the email

**Comment by Zeugma440** [comment]
My apologies. For some reason, your e-mails got caught in the spam filter...

I got the 4 files you send. I'll get back to you soon.

**Comment by Zeugma440** [comment]
Got that one. ATL only supported one kind of fragmented MP4 (the one with one `moof` atom and multiple `trun` atoms) and not the other (the one with multiple `moof` atoms, each with one single `trun` atom).

Fix will be available for next release

**Comment by Smiuv** [comment]
Thank you, I hope I can help to improve this library.

**Comment by Zeugma440** [comment]
Fix is available in today's v6.05. Please close this issue if it works on your side~

**Comment by Smiuv** [comment]
I tried the file and it was correct from my side , thanks.
