### ISSUE TITLE
[QUESTION] How to add a picture to thisChapter.Picture?

### ISSUE THREAD

**Issue by tarrats** [Zeugma440/atldotnet#28]
## The problem

Before I go and and change my implementation, I was wondering if the following code would theoretically work for adding a picture to a specific chapter:

```
using ATL.AudioData;

AudioDataManager theFile = new AudioDataManager(AudioDataIOFactory.GetInstance().GetFromPath(fileName));

TagData theTag = new TagData();
theTag.Chapters = new System.Collections.Generic.List<ChapterInfo>();

PictureInfo newPicture = new PictureInfo(Commons.ImageFormat.Gif, PictureInfo.PIC_TYPE.CD);
newPicture.PictureData = System.IO.File.ReadAllBytes("E:/temp/_Images/pic1.gif");

ChapterInfo ch = new ChapterInfo();
ch.StartTime = 123;
ch.StartOffset = 456;
ch.EndTime = 789;
ch.EndOffset = 101112;
ch.UniqueID = "";
ch.Title = "aaa";
ch.Subtitle = "bbb";
ch.Url = "ccc\0ddd";
ch.Picture = newPicture;
theTag.Chapters.Add(ch);
```

## Environment

* ATL version (or git revision) that exhibits the issue: **2.8 (main branch)**
* Last ATL version that did not exhibit the issue (if applicable): **N/A**
* OS/version used to run ATL: **Windows 10 x64, v1803, build 17134.648**

## Details

The few instances I've find where a picture is used on specific chapters do not appear under Picture in the Chapter Array, and hence my question :(

**Comment by tarrats** [comment]
The file: Overtime-40-Alana-Louise.mp3 is a good example of a file that has at least three very different pictures that are displayed in very specific chapters: 

[Overtime-40-Alana-Loise](https://we.tl/t-jUrL3R6wIW)

Chapter 9 "Merging Hobbies With Design Work"
Chapter 11 "Thanks to Wix.com for sponsoring..."
Chapter 14 "Austin Beerworkds La Verdad"
Chapter 20 "Thanks for Listening..." (same picture as Chapter 11)

But somehow, no information under the Chapter array for "Picture" is found, for every chapter, **Picture** is NULL.

Thanks!

**Comment by Zeugma440** [comment]
Short answer is yes, that would theoretically work.

A working implementation example can be found in the unit tests, here : https://github.com/Zeugma440/atldotnet/blob/master/ATL.test/IO/MetaData/ID3v2.cs (see `private void TagIO_RW_ID3v2_Chapters()`)

That being said, chapters are supposed to be accessible through the `Track` class, which should greatly simplify the implementation on your side.

I'll update the Code Snippets section with a new working example (including pictures) to illustrate that.

**Comment by Zeugma440** [comment]
Mind you, the library has been built so that its users have the possibility to use low-level gears and cogs such as `AudioDataManager` and `TagData`. If you're comfortable with it and prefer to keep a tight control over what you process, there's no problem at all.

On the other side, if you want your code to be as light as possible, and let ATL handle the complexity, I'd recommend using `Track` instead.

**Comment by Zeugma440** [comment]
I've updated the [Code Snippets](https://github.com/Zeugma440/atldotnet/wiki/3.-Usage-_-Code-snippets#writing-chapters-in-a-tag) "Writing chapters in a tag" example with what you need, using `Track` instead of `AudioDataManager`.

Please tell me if it works as expected.

Cheers,

**Comment by tarrats** [comment]
So I've updated my code to using `Track `instead and not only does it work like a charm, but it's rather straightforward and super easy to use so thank you!

As for the picture embedding in specific chapters: WORKS LIKE A CHARM!!!

![04-02 at 10 18 10 AM](https://user-images.githubusercontent.com/36057367/55409807-b4b40a80-5530-11e9-94fc-13c28c0e9b28.jpeg)

**Comment by Zeugma440** [comment]
Awesome. I'm so glad to be able to beautify your podcasts :)
