### ISSUE TITLE
Bug in load file by filePath

### ISSUE THREAD

**Issue by Smiuv** [Zeugma440/atldotnet#280]
Hello,
This bug is when loading a file through a path,
I found the cause of this bug and fixed it temporarily.
The reason for the bug for me was that it didn't allow access to some files, and I load it with a (file stream) and give the necessary access to filestram and I don't have any more problems.

thank you.

**Comment by Zeugma440** [comment]
Most of the time, that kind of issue is caused by a credentials problem on your OS, or a syntax problem in the path itself.

Could you share the code you're using ?

**Comment by Smiuv** [comment]
I found this problem when loading a flac file via string. But this problem is only in **asp.net core** and I solved the problem by giving file stream and read and write access.

``` csharp
string filePath = @"........\medium.mp3";
Track track = new Track(filePath);
```
Loads all files reliably :
``` csharp
FileStream fileStream = new FileStream(filePath, FileMode.Open, FileAccess.ReadWrite);
Track track = new Track(fileStream);
```
> [!NOTE]
> This problem is only in asp.net core and flac files

**Comment by Zeugma440** [comment]
I have no idea what happens there. I'd tend to point an issue in the ASP environment.

When the problem happens, what kind of output do you get?

**Comment by Smiuv** [comment]
I got this problem a long time ago.
It really doesn't matter!
There was a problem with access to read the file.
