### ISSUE TITLE
Bug in mka file

### ISSUE THREAD

**Issue by Smiuv** [Zeugma440/atldotnet#283]
Hello ,I found another bug, but I'm not sure if it's a bug or not!
I have a file with the type Matroska / Opus, the file loads correctly, but when saving the changes, the file crashes and is no longer playable.

**Comment by Zeugma440** [comment]
That definitely looks like a bug, yeah 😅  Bring it on!

**Comment by Smiuv** [comment]
Check your email.

**Comment by Zeugma440** [comment]
First of all, that file's tagging isn't really spec-compliant (`Tag.Targets` is not set, weird `ALBUM` field that doesn't follow Matroska tagging logic). I've adjusted the reader to detect metadata even in that case.

The "unplayable file" issue has been solved as well. That was a nasty bug on my side.

**Comment by Zeugma440** [comment]
Fix is available in today's v6.05. Please close this issue if it works on your side~
