### ISSUE TITLE
composer in mp3

### ISSUE THREAD

**Issue by Miner-2021** [Zeugma440/atldotnet#285]
## The problem

The composer tag in the form of numbers is perceived as a genre.
Сomposer 123 becomes A capella

**Comment by Zeugma440** [comment]
That's _very_ surprising to hear.

- Could you tell me which tag system you're using (ID3v2.2-3-3 ? APE ?) ?
- Could you explain the steps to reproduce the issue ?

Thanks in advance~

**Comment by Miner-2021** [comment]
test ID3v2.4 only
![1](https://github.com/user-attachments/assets/1b44a211-41c5-4dfd-96fd-3646794ba79b)
foobar2000
![2](https://github.com/user-attachments/assets/60d7ab44-8c19-4648-abdb-b6ce39a67117)
file
[01 - title.zip](https://github.com/user-attachments/files/17491073/01.-.title.zip)

**Comment by Zeugma440** [comment]
Found it. Thanks for your feedback. The fix will be available on next release!

**Comment by sandreas** [comment]
@Zeugma440 Same goes for `copyright`, if you didn't fix this already. Maybe others, I'm currently checking all properties.

**Comment by Zeugma440** [comment]
@sandreas yep, the fix also prevents that issue from happening with `copyright` 👍

**Comment by Zeugma440** [comment]
Fix has been released with today's v6.07

Please close the issue if it works on your side~

**Comment by Miner-2021** [comment]
work. Thx.
