### ISSUE TITLE
Handling of completely tagless files

### ISSUE THREAD

**Issue by sandreas** [Zeugma440/atldotnet#286]
## The problem

Using a completely tagless file ([sample.zip](https://github.com/user-attachments/files/17595927/sample.zip)) results in a problem - there is no way to determine the FUTURE metadata format, that is going to be used, because it is determined automatically by internal code - even if the file is provided and exists.

Usually the following code works fine:

```c#
var dst = "sample.mp3"
var track = new MetadataTrack(dst);
switch (track.MetadataFormats.FirstOrDefault()?.Name)
{
    case "Native / MPEG-4":
        track.AdditionalFields["----:com.pilabor.tone:PART"] = "2.1";
        break;
    case "ID3v2.3":
    case "ID3v2.4":
        track.AdditionalFields["TXXX:PART"] = "2.1";
        break;
    default:
        // ????
        break;
}
```

So, how would I decide, which additional field to use, if the file metadata is completely empty?
Related issue: https://github.com/sandreas/tone/issues/46

## Possible solution (quick):
`Track` could have a nullable `DefaultMetadataFormat` property, which contains the future format, as soon as the file exists and is readable. This should go along with a `public` method `public Format LoadDefaultMetadataFormat(string filePath)` (possibly stream).

As an addition, I found it pretty hard to determine the metadata format by using a name string. Therefore I created an `MetadataSpecification` enum with an according "detection" Method (which is still incomplete):

```c#
public enum MetadataSpecification
{
    Undefined,
    Id3V1,
    Id3V23,
    Id3V24,
    Mp4,
    Matroska,
    WindowsMediaAsf,
    Ape,
    Vorbis,
    Aiff
}

    private static MetadataSpecification AtlFileFormatToMetadataFormat(Format format) => format.Name switch
    {
        "Native / MPEG-4" => MetadataSpecification.Mp4,
        "Native / AIFF" => MetadataSpecification.Aiff,
        "Native / Vorbis (OGG)" => MetadataSpecification.Vorbis,
        "ID3v1.1" => MetadataSpecification.Id3V1,
        "ID3v2.3" => MetadataSpecification.Id3V23,
        "ID3v2.4" => MetadataSpecification.Id3V24,
        "APEtag v2" => MetadataSpecification.Ape,
        _ => MetadataSpecification.Undefined
    };
```

## Possible solution (long term):

These problem could also be solved by the suggestion I made long time ago (https://github.com/Zeugma440/atldotnet/discussions/167#discussioncomment-3949396) where instead of having one `AdditionalFields` dictionary, this stuff would go into one dictionary per metadata format:

```c#
class Track {
    public string? Title
    {
        get => GetFieldValue<string?>();
        set => SetFieldValue(value);
    }

    public Specification MetadataDefaultKey = Specification.Id3v24;
    public IMetadata MetadataDefault => Metadata[MetadataDefaultKey];

    private T? GetFieldValue<T>([CallerMemberName] string key = "")
    {
        // key:Title => mappedKey:TALB
        return MetadataDefault.GetValue<T>(key);
    }
    private void SetFieldValue<T>(T? value, [CallerMemberName] string key = "")
    {
        return MetadataDefault.SetValue(key, value);
    }

    public void SetCustomFieldValue<T>(string key, T? value, Specification? spec=null)
    {
        if(spec == null) {
            MetadataDefault.SetValue(key, value);
        } else {
              Metadata[spec].SetValue(key, value);
        }
    }
}

// the following would be the same as 
// track.Title = "my value";
track.Metadata[Specification.Id3v24].Fields["TALB"] = "my value";

 // would now also give "my value" now
// no interference between `AdditionalFields` and `Title`
Console.WriteLine(track.Title);

```

**Comment by Zeugma440** [comment]
Hi @sandreas, it's been a while 😄 

`Settings.DefaultTagsWhenNoMetadata` exists for the use case you're describing.

Default value is `{ MetaDataIOFactory.TagType.RECOMMENDED }` (= the most compatible metadata formats according to the target audio format), but you can set it to one or many of these values :
* `MetaDataIOFactory.TagType.ID3V1`
* `MetaDataIOFactory.TagType.ID3V2`
* `MetaDataIOFactory.TagType.APE`
* `MetaDataIOFactory.TagType.NATIVE` (e.g. M4A/MP4 atoms, Vorbis for FLAC, MKA elements)

Last but not least, you can switch between ID3v2.3 and ID3v2.4 using `Settings.ID3v2_tagSubVersion` (default is 4).

Let me know if that works for you.

**Comment by sandreas** [comment]
> Hi @sandreas, it's been a while 😄

Yeah, having 2 kids is pretty much eating up all my time. Hope you're doing well and as always thanks for the quick support.

> Settings.DefaultTagsWhenNoMetadata

So you mean if I set this to the default value, then `track.MetadataFormats` will contain an item, even if the file does not contain any metadata? 

Example: lets say I have a file `sample.dat` which internally is an mp3 with no tags at all.  I use Track to load the file... How would I find out that `atldotnet` is going to write id3v24 and that keys for additional fields would need to be id3 ones?

**Comment by Zeugma440** [comment]
Oh, I think I see what you mean... When loading `sample.dat`, you'll be able to see which kind of audio data it is (using `Track.AudioFormat`) but you won't see any metadata as there's none (!)

The information saying which metadata formats are compatible to the loaded file isn't accessible using the `Track` class; here's how to get it :

```cs
using FileStream fs = new FileStream(filePath, FileMode.Open, FileAccess.Read, FileShare.Read, Settings.FileBufferSize, FileOptions.RandomAccess);
var audioData = AudioDataIOFactory.GetInstance().GetFromStream(fs);
audioData.GetSupportedMetas().ForEach(a => Console.WriteLine(a)); // Returns a list of MetaDataIOFactory.TagType
```

Knowing which formats are compatible, you'll be able to force the one to actually write according to your own rules, by setting `Settings.DefaultTagsWhenNoMetadata`.

Is that closer to what you were looking for?

**Comment by sandreas** [comment]
> Is that closer to what you were looking for?

Kind of, but still incomplete. To decide, which key I need for `AdditionalFields` I need the `TagType` AND `FileType`. `TagType.Native` could still have different meanings depending on the file type.

- On `m4a` it would be `----:com.pilabor.tone:PART`
- On `ogg` it would be `PARTNUMBER` 

In both cases `TagType.Native` is used. 

The `Format` class only contains a string, but is more specific (`MetadataSpecification` is an enum I created to overcome this problem, but it does not work, if `Track.MetadataFormats` is empty):

```c#
    private static MetadataSpecification AtlFileFormatToMetadataFormat(Format format) => format.Name switch
    {
        "Native / MPEG-4" => MetadataSpecification.Mp4,
        "Native / AIFF" => MetadataSpecification.Aiff,
        "Native / Vorbis (OGG)" => MetadataSpecification.Vorbis,
        "ID3v1.1" => MetadataSpecification.Id3V1,
        "ID3v2.3" => MetadataSpecification.Id3V23,
        "ID3v2.4" => MetadataSpecification.Id3V24,
        "APEtag v2" => MetadataSpecification.Ape,
        _ => MetadataSpecification.Undefined
    };
```

So what I would need is the `MetadataFormats` that are going to be written - what would mean that the `IMetadataIO` instances would have to add an item to the `MetadataFormats`, even if it did not contain metadata.

A better approach in my opinion would be to have an `enum` of all supported metadata specifications (see above) and just add a list property  `MetadataSpecifications` to `Track`. 

But this is a very difficult problem, I'm not sure, I could solve this in a pull request. The complexity of `atldotnet` is huge for a newbie ;)

**Comment by Zeugma440** [comment]
I'd take another approach

```cs
// Load the empty file
using FileStream fs = new FileStream(filePath, FileMode.Open, FileAccess.Read, FileShare.Read, Settings.FileBufferSize, FileOptions.RandomAccess);
var audioData = AudioDataIOFactory.GetInstance().GetFromStream(fs);

// See what it is
var format = audioData.AudioFormat;
// See what you can write inside
var supportedMetas = audioData.GetSupportedMetas();

// Populate MetadataSpecification
MetadataSpecification meta = MetadataSpecification.Undefined;
if (format.ID == AudioDataIOFactory.CID_MP4) meta = MetadataSpecification.Mp4;
else if (format.ID == AudioDataIOFactory.CID_AIFF) meta = MetadataSpecification.Aiff;
else if (format.ID == AudioDataIOFactory.CID_FLAC) meta = MetadataSpecification.Vorbis;
else if (format.ID == AudioDataIOFactory.CID_OGG) meta = MetadataSpecification.Vorbis;
else if (format.ID == AudioDataIOFactory.CID_WMA) meta = MetadataSpecification.Wma;
else
{
    // NB : Adjust priority order according to your own preferences
    if (supportedMetas.Contains(MetaDataIOFactory.TagType.APE)) meta = MetadataSpecification.Ape;
    else if (supportedMetas.Contains(MetaDataIOFactory.TagType.ID3V2)) meta = MetadataSpecification.Id3V24;
    else if (supportedMetas.Contains(MetaDataIOFactory.TagType.ID3V1)) meta = MetadataSpecification.Id3V1;
}

// Prepare ATL settings to write what you need
var atlMeta = MetaDataIOFactory.TagType.NATIVE;
byte id3v2Version = 4;
if (meta == MetadataSpecification.Ape) atlMeta = MetaDataIOFactory.TagType.APE;
else if (meta == MetadataSpecification.Id3V23)
{
    id3v2Version = 3;
    atlMeta = MetaDataIOFactory.TagType.ID3V2;
}
else if (meta == MetadataSpecification.Id3V24) atlMeta = MetaDataIOFactory.TagType.ID3V2;

Settings.ID3v2_tagSubVersion = id3v2Version;
Settings.DefaultTagsWhenNoMetadata = new MetaDataIOFactory.TagType[] { atlMeta };

// Last step : write your stuff ;-)
```

**Comment by sandreas** [comment]
> I'd take another approach

Thank you so much. As far as I understand, the ONLY thing missing in `Track` that prevents me from fully integrating this approach is a new protected or public property `Track.SupportedMetas`:

```c#
protected void Update(bool onlyReadEmbeddedPictures = false)
{

    //...

    this.SupportedMetas = this.fileIO.GetSupportedMetas()
}
```
This would reduce the number of file accesses, because `Track` is already doing everything required here. `AudioFormat` is already present and with the new `SupportedMetas` I could easily integrate the whole thing without extra file reads.

Would you consider adding this for the next release?

**Comment by sandreas** [comment]
@Zeugma440 

Here I implemented the workaround, you suggested:
https://github.com/sandreas/DotnetLibAudioMetadata/commit/fba806b264a1b5539c40c8b99a3cc43e29f252f9

Access to `SupportedMetas` would make my life easier, but at least it works. I'll leave this issue open in case you would like to add the `SupportedMetas` field - feel free to close this issue. Thank you again.

**Comment by Zeugma440** [comment]
Don't release that too soon, there's an issue about comparing `AudioFormat.ID` to IDs published by `AudioDataIOFactory` in some cases.

I'll work on it and let you know.

**Comment by sandreas** [comment]
> Don't release that too soon, there's an issue about comparing AudioFormat.ID to IDs published by AudioDataIOFactory in some cases.

Thanks for the hint. I'm waiting for the `composer` / `copyright` fix anyway, so no hurry.

**Comment by Zeugma440** [comment]
Problem was `Format.ID` was very inconsistent on container formats (e.g. MKA, CAF) and could vary according to what they contain (e.g. MP3, FLAC...).

Audio data format is now described by the [AudioFormat](https://github.com/Zeugma440/atldotnet/blob/main/ATL/Entities/AudioFormat.cs) class that contains _two_ IDs :
- `ContainerId` for the container format
- `DataFormat.ID` for the audio data

Above code snippet should now be written as follows (note `format.ID` should now be `format.ContainerId`) :

```cs
// Populate MetadataSpecification
MetadataSpecification meta = MetadataSpecification.Undefined;
if (format.ContainerId == AudioDataIOFactory.CID_MP4) meta = MetadataSpecification.Mp4;
else if (format.ContainerId == AudioDataIOFactory.CID_AIFF) meta = MetadataSpecification.Aiff;
else if (format.ContainerId == AudioDataIOFactory.CID_FLAC) meta = MetadataSpecification.Vorbis;
else if (format.ContainerId == AudioDataIOFactory.CID_OGG) meta = MetadataSpecification.Vorbis;
else if (format.ContainerId == AudioDataIOFactory.CID_WMA) meta = MetadataSpecification.Wma;
```

Next step is to publish `SupportedMetas` to `Track`

**Comment by Zeugma440** [comment]
Evrything has been delivered in today's v6.07.

Please close the issue if it works on your side~

**Comment by sandreas** [comment]
> Evrything has been delivered in today's v6.07.

Awesome work, thank you so much. I'm updating my code ASAP, but I'll go for closing the issue and reopening if it does not work (which I don't expect).
