### ISSUE TITLE
Title cannot be set empty / removed

### ISSUE THREAD

**Issue by sandreas** [Zeugma440/atldotnet#287]
I'm currently testing `tone` extensively due to some basic changes I made and noticed, that if I try to set `Title` to an empty value or remove it, it does not save the changes and keeps the existing title.

Sample code:
```c#
var track = new MetadataTrack(dst);
track.Title = ""; // null also does not work (as I would have expected)
await track.SaveAsync();
```

It's atldotnet 6.06 (latest) on linux, using a simple mp3 file:
[sample.zip](https://github.com/user-attachments/files/17597138/sample.zip)

**Comment by Zeugma440** [comment]
Does that happen on any kind of files, or certain formats specifically?

**Comment by sandreas** [comment]
> Does that happen on any kind of files, or certain formats specifically?

It happens on ANY kind of file. I double checked, it seems that title falls back to the filename, but I'm not totally sure about this.

So here is the piece of code I used to remove / check (raw `atldotnet`, no wrapper):

```c#
var files = new List<string>(["sample.flac", "sample.m4a", "sample.mp3"]);
foreach (var f in files)
{
    var full = "/home/andreas/projects/DotnetLibAudioMetadata/CliTester/tmp/" + f;
    var track = new Track(full);
    Console.WriteLine(track.Title);
    if (!string.IsNullOrEmpty(track.Title))
    {
        Console.WriteLine($"{f}: track.Title is not empty, although I removed it");
    }
    track.Title = "";
    await track.SaveAsync();
}
```

**Comment by sandreas** [comment]
> Did you set Settings.UseFileNameWhenNoTitle to false?

I didn't. Sorry for wasting your time... I will now go through every possible setting and look up the best possible values for my purpose. Thanks for helping out.
