### ISSUE TITLE
Unable to read or write Track fields SortAlbumArtist or SortArtist 

### ISSUE THREAD

**Issue by ohcrap1** [Zeugma440/atldotnet#291]
I am unable to read or write the SortAlbumArtist and SortArtist fields.  The dozen plus other fields I use read and write OK.

I can see sort info or populate it with a tool like the mp3tag Extended Tag fields function, but when I instantiate a track, those fields are blank (show as theTrack.SortAlbumArtist  = "" in visual studio debugger).  On the write side, I can populate the Track fields, and then Track save. The file is updated with other fields, but those fields remain blank upon inspection with another tool.

I'm working on W10 VS 19, .NET6.0, with flac files, and NuGet ATL 6.8.0.

**Comment by Zeugma440** [comment]
Hey there,

Thanks for your feedback. These two fields have indeed been overlooked when coding the VorbisTag mapping.

I've just added them. They'll be available on next release.

**Comment by Zeugma440** [comment]
Fix has been delivered in today's v6.09.

Please close the issue if it works on your side.

**Comment by Zeugma440** [comment]
No answer for one month -> Closed

Please open a new issue if needed
