### ISSUE TITLE
Virus Detected when downloading the project.

### ISSUE THREAD

**Issue by joshuapaulanderson** [Zeugma440/atldotnet#292]
## The problem

I get the following error when downloading the project zip file.

![image](https://github.com/user-attachments/assets/b6026497-c102-4842-96c1-493b53057b22)

## Environment

*Windows 11

**Comment by Zeugma440** [comment]
Hi there,

Hi have no idea why that happens. There's no executable nor any binary file inside the repo, only source code, images and audio files.

That ZIP file you downloaded is generated by GitHub. Maybe the problem is on GitHub's side.

**Comment by sandreas** [comment]
> There's no executable nor any binary file inside the repo

What about the sample files in `ATL.unit-test/Resources`? Did you actively check it? Maybe it's just a false positive, but these samples are binary.

**Comment by joshuapaulanderson** [comment]
Thank you for your response. Just making sure before I pulled it down.
Is there a way to add via NuGet?

________________________________

**Comment by Zeugma440** [comment]
> What about the sample files in ATL.unit-test/Resources? Did you actively check it? Maybe it's just a false positive, but these samples are binary.

By "binary" I meant "executable". And I just realized there's still `atomicParsley.exe` inside the MP4 resource folder.

Just removed it as it's not useful for the tests. It's a safe utility I used like 100 times.

> Is there a way to add via NuGet?

Certainly. The link to the NuGet location is on the main page : https://www.nuget.org/packages/z440.atl.core/

**Comment by sandreas** [comment]
> Just removed it as it's not useful for the tests. It's a safe utility I used like 100 times.

I'm not saying your repo contains infected files, but that it may be some (dumb) Antivirus software detects a binary signature in one of the samples as Malware. It's not your fault, but it would be interesting, which of the files it may be.

**Comment by Zeugma440** [comment]
Oh I see what you mean 😄  It's up to @joshuapaulanderson then

**Comment by joshuapaulanderson** [comment]
Thank you!

________________________________

**Comment by Zeugma440** [comment]
Looks like that issue's solved
