### ISSUE TITLE
Problem with the duration of a song

### ISSUE THREAD

**Issue by Smiuv** [Zeugma440/atldotnet#295]
Hello again, the problem is with the duration of a file, the real time is about 6.5 minutes and **ATL** displays it as 40 seconds.
I will email it to you.

**Comment by Zeugma440** [comment]
Thanks for your feedback.

That file is an enigma for most of the apps I have 😂 
- Windows Explorer thinks it lasts 06:09
- foobar2000 thinks it lasts 1:40:01
- MP3tag thinks it lasts 25:00
- Winamp and MusicBee think it lasts 100:01
- VLC thinks it lasts 06:11 but constantly recalculates that duration while playing
- PotPlayer thinks it lasts 06:10
- AIMP gets it right at 06:12

When reading it with ATL, it gives 05:00, with and without `Settings.MP3_parseExactDuration = true`

I'll give it a look and get back to you

**Comment by Smiuv** [comment]
I think it is 6:10 seconds. Because I converted it with ffmpeg.

**Comment by Zeugma440** [comment]
Got it. That file is a "freeform" VBR file without any formal VBR information (Xing, FhG).

I've corrected the code to handle that case properly ✅

**Comment by Zeugma440** [comment]
Fix is available in today's v6.10. Please close the issue if it works on your side~

NB : You need to enable `Settings.MP3_parseExactDuration = true`

**Comment by Smiuv** [comment]
Hi, I still have a problem.

```csharp
Settings.MP3_parseExactDuration = true;
FileStream fileTrack = new FileStream(destination, FileMode.Open, FileAccess.ReadWrite);
Track track = new Track(fileTrack);
```

**Comment by Zeugma440** [comment]
That's working code indeed. What is your problem exactly?

**Comment by Smiuv** [comment]
I don't know. I updated the package and enabled only the settings you mentioned, but it still shows the wrong time.

**Comment by Zeugma440** [comment]
Wrong time, like 40 seconds? Are you certain your e-mailed me the correct file?

**Comment by Smiuv** [comment]
Yes, I emailed the correct file.

**Comment by Zeugma440** [comment]
Looks like ATL detected the wrong audio format (AAC instead of MP3) when loading that file through a blind `Stream`. I didn't repro that until now as I've been loading your file directly from the file.

I'll take a look and get back to you.

**Comment by Smiuv** [comment]
If you remember, I once reported that there is a difference between loading a file via a stream and via a path.

Because I tried it in a **Asp.net core** and the Flac files were only loaded via a stream.

But I don't know if these issues are related or not! It was just a reminder.

**Comment by Zeugma440** [comment]
Got it. Should be good for next release

**Comment by Zeugma440** [comment]
Fix is available with today's v6.11.

Please close the issue if it works on your side.

**Comment by Smiuv** [comment]
Hello, thank you. It worked.

**Comment by orbittwz** [comment]
is this fix implemented in some way for .net framework latest version of this program 4.36 ?
also no MP3 settings available in this version 😢 

![Image](https://github.com/user-attachments/assets/4071c967-6a8c-4d07-bbc3-76dd108cac0c)

**Comment by Zeugma440** [comment]
It is available for all compatible.NET framework versions including the latest. And settings are available. Please look closer.

**Comment by orbittwz** [comment]
I'm not using the latest version as I mentioned, I'm using version 4.36.
Also, searched the whole source code of 4.36 and no option about "parseexact"

**Comment by Zeugma440** [comment]
My mistake, sorry about this. That setting has been added to 6.10. There's no retrocompatibiity patch.

I strongly advise upgrading to the latest version.

**Comment by orbittwz** [comment]
Wish I could, I use VS2019 and I cannot update my projects to NET6+ 😢

**Comment by Zeugma440** [comment]
Why is that? Are your clients under very specific constraints? Or are you coding for yourself on a very old PC?

**Comment by orbittwz** [comment]
No particular reason why I'm still on VS2019 and I could upgrade anytime I want.
It's just from habit and familiarity with this VS version.
I can check myself why ATL is doing this, and maybe do a workaround fix.
I noticed it's lowering the bitrate really low (mid 60's) thus upping the duration to 20 minutes each track.
Will update if I have something else to say 😉

**Comment by orbittwz** [comment]
yep found what is doing this.
seems like when there is LENGTH tag in tracks ATL counts that as the duration and not parsing the real time from the stream.

![Image](https://github.com/user-attachments/assets/cb6f6d7f-fa4a-4673-84de-486804f7b848)

in blue the corrupted times and bitrate, whereas in green the correct time and bitrate after removing the tag LENGTH in the tracks.
will adapt my programs to remove this tag when parsing tracks.
hope there isn't something else... 🙏

**Comment by orbittwz** [comment]
removing the field with ATL doesn't affect the data shown, I'm not saving the track though.
2025-02-21 11:43:52.323 +02:00 [INF] the bitrate is 32 and time is 1777
2025-02-21 11:43:52.325 +02:00 [INF] the bitrate is 48 and time is 1166
2025-02-21 11:43:52.326 +02:00 [INF] the bitrate is 96 and time is 540
still the wrong bitrate and time.

**Comment by Zeugma440** [comment]
I will not provide support for an older version of ATL.

Please udpate your project to support the latest version and post a _new_ GitHub issue if you still have problems.

I won't answer on that thread anymore.

**Comment by orbittwz** [comment]
Fair enough, you are right...
Thanks anyways!

**Comment by orbittwz** [comment]
never say never I say 😉 
for users who needs it and for you if you ever need to understand what I meant 💪 

![Image](https://github.com/user-attachments/assets/e3dc5637-ddc3-46ab-b069-88a24840497d)

it's working and the information is now matching whether you have LENGTH field or not.
take care!
