### ISSUE TITLE
Support for writing playlists?

### ISSUE THREAD

**Issue by Otiel** [Zeugma440/atldotnet#30]
I've only found references to `PlaylistReader` with a glance. Does it support creating playlists (m3u...) from a list of tracks?

**Comment by Otiel** [comment]
Thanks for the quick answer. At first I'm interested in writing playlists in the m3u format, but probably other popular formats as well eventually.

But in the meantime I've found https://github.com/tmk907/PlaylistsNET which seems to do it already. I'm gonna try using this for now.

I'd be interested to use ATL to replace TagLib# and PlaylistsNET and reduce my dependencies fingerprint though, if you add support for writing libraries in the future.

**Comment by Zeugma440** [comment]
Duly noted, I'll see what I can do !

**Comment by Zeugma440** [comment]
@Otiel Problem solved. The site has been un-flagged. You can now get the latest code and write playlists.

Please keep me updated :-)


Cheers,
~Z440

**Comment by Otiel** [comment]
Thanks, I'll try it as soon as I get the chance!

I didn't receive any notification for your previous messages, I guess it's because of the GitHub issue. What was the reason behind the flag of your GitHub account? Any code compromised?

**Comment by Zeugma440** [comment]
Nope, support said my account had been flagged automatically for manual review, without any other explanation. I guess it was because of the many audio files in the test resources. Anyway, all's back to normal.

**Comment by Zeugma440** [comment]
FYI, I has to fix a critical bug today and release a new version. The new playlist writing classes are now part of release v2.9 (NuGet package published)

The old playlist readers are still accessible but have been marked as deprecated / obsolete.

**Comment by Zeugma440** [comment]
I'm closing this topic as comprehensive tests are taking place in #33
