### ISSUE TITLE
Reading ID3v2.4 throwing System.IndexOutOfRangeException

### ISSUE THREAD

**Issue by evildigitalalien** [Zeugma440/atldotnet#31]
I am unable to read files in with preexisting ID3v2.4 tagging. 

I tried using the first code example just to make sure it wasn't my code and the problem still appears. 

I'm using ATL 2.8, Windows 10.
I used the exact first code example you provided I've only changed the filename. 
I also attached a screenshot and the file.  

![image](https://user-images.githubusercontent.com/25760153/56940773-703f6e80-6ade-11e9-8070-439e3bd3a584.png
Edit : File removed
)

**Comment by Zeugma440** [comment]
Hi @evildigitalalien 

Thanks for the report ! Your issue has been fixed in today's commit 7da0d6e3c0400c1bc1395fafb8160ca7f2b677b3

The problem was the tracknumber being "/" on the file you submitted. ATL had a malfunctioning edge case detection that has now been fixed.

**Comment by Zeugma440** [comment]
The fix has been released to new version 2.9 (NuGet package published)

**Comment by evildigitalalien** [comment]
Awesome works like a dream now, 
thank you so much.

**Comment by Zeugma440** [comment]
Pleasure's mine ;-)
