### ISSUE TITLE
Saving of .pls Playlist.  

### ISSUE THREAD

**Issue by DividedSE** [Zeugma440/atldotnet#32]
## The problem

If you save a playlist in ".pls" format atl can't Load it back.
There is a problem is saving code.
I already Fixed the issue by removing line 53 :- w.WriteLine(""); from PLSIO.cs

## Environment

* ATL 2.9
* Last ATL version that did not exhibit the issue (if applicable):
* Windows 10 1809, Visual Studio 2019, WPF dot.net 4.6.2 

## Details

Exception thrown: 'System.ArgumentOutOfRangeException' in mscorlib.dll
   at System.String.Substring(Int32 startIndex, Int32 length)
   at ATL.Playlist.IO.PLSIO.getFiles(FileStream fs, IList`1 result) in atldotnet-2.9\ATL\Playlist\IO\PLSIO.cs:line 23
   at ATL.Playlist.PlaylistIO.getFiles() in atldotnet-2.9\ATL\Playlist\PlaylistIO.cs:line 45

Don't forget to include ATL.Logging.Log and/or console output

## Code To Reproduce Issue [ Good To Have ]
private void LoadButton_Click(object sender, RoutedEventArgs e)
        {
            var openFile = new OpenFileDialog() { };
            if (openFile.ShowDialog() != true) return;            
            IPlaylistIO theReader = PlaylistIOFactory.GetInstance().GetPlaylistIO(openFile.FileName);
            foreach (string s in theReader.FilePaths)
            {            
                listbox.Items.Add(s);
            }
        }
        private void SaveButton_Click(object sender, RoutedEventArgs e)
        {
            IPlaylistIO pls = PlaylistIOFactory.GetInstance().GetPlaylistIO("G:/abc.pls");
            // Writing file paths
            IList<string> pathsToWrite = new List<string>();
             foreach (var item in listbox..Items)
            {
                pathsToWrite.Add(item.ToString());
            }
            pls.FilePaths = pathsToWrite;
        }

**Comment by Zeugma440** [comment]
Hello @DividedSE and thanks for the report.

I'm not sure I would fix that on the saving side; but rather on the loading side.

I'll publish a fix and a new version soon.


Best regards,
~Z440

**Comment by Zeugma440** [comment]
Fixed
