### ISSUE TITLE
Several Playlist Format can't be opened by other software.

### ISSUE THREAD

**Issue by DividedSE** [Zeugma440/atldotnet#33]
## The problem

I saved 5 songs using atl 2.9 in all the formats supported by atl 2.9 (asx,b4s,wax,wvx,m3u,m3u8,pls,xspf,smi,smil,wpl).
Only m3u,m3u8 & pls properly opened in vlc & musicbee.
Atl 2.9 can open all playlist files but the spaces in filepath's replaced by %20 so bass(by un4seen) cant find the address of the song.
Even if i manully replace %20 by space in other playlist's vlc & musicbee still cant load it.
note:- Playlist formats(in notepad) are totally different than the samples provided in atl.

## Environment

* ATL 2.9:
* Last ATL version that did not exhibit the issue (if applicable):
* Windows 10 1809, Visual Studio 2019, WPF .net4.6.2

## Details

If necessary, describe the problem you have been experiencing in more detail.

Don't forget to include ATL.Logging.Log and/or console output

## Code To Reproduce Issue [ Good To Have ]

private readonly string _playlistFilter = Properties.Resources.PFilter;
        private readonly string _savelistFilter = Properties.Resources.SFilter;
        #region Playlist
        private void LpMi_Click(object sender, RoutedEventArgs e)
        {
            var openFile = new OpenFileDialog()
            {
                Filter = _playlistFilter
            };
            if (openFile.ShowDialog() != true) return;
            var theReader = PlaylistIOFactory.GetInstance().GetPlaylistIO(openFile.FileName);
            foreach (var s in theReader.FilePaths)
            {
                LBoxSongPaths.Items.Add(s);
                LBoxSongNames.Items.Add(Path.GetFileNameWithoutExtension(s));
            }
        }

        private void SpMi_Click(object sender, RoutedEventArgs e)
        {
            var saveFile = new SaveFileDialog()
            {
                Filter = _savelistFilter
            };
            if (saveFile.ShowDialog() != true) return;
            var pls = PlaylistIOFactory.GetInstance().GetPlaylistIO(saveFile.FileName); //Example 1.asx
            IList<string> pathsToWrite = new List<string>();
            foreach (var item in LBoxSongPaths.Items)
            {
                pathsToWrite.Add(item.ToString());
            }
            pls.FilePaths = pathsToWrite;
        }

**Comment by DividedSE** [comment]
Note *.pls format may not work also in vlc. Mine working becaz i fixed my code as it mentioned in my previous bug report.

**Comment by Zeugma440** [comment]
Thanks for the report. 

I'll have to test exhaustively the generated files with commercial software to discover how far from the specs their implementation is (which I should have done from the beginning).

According to what you're saying, the issue happens mostly on XML-based formats. There might be a quirk I didn't activate to make the generated XML files more readable.

I'll let you know shortly.

**Comment by Zeugma440** [comment]
I've changed the layout of XML files and fixed a couple of issues.

Could you check again with the latest commit and tell me if there are remaining issues on your side ?

Best regards,
~Z440

**Comment by Zeugma440** [comment]
Thanks for the quick answer !

Regarding B4S, I actually tried fixing "B4S vs. VLC" with multiple variants, but nothing seems to work so far. I suspect their B4S parser to be broken.

Have you tried generating a legit B4S with Winamp and make it read by VLC ?

Which version of Winamp are you using, by the way ? B4S is a super old format that was created by Winamp itself and never documented...

**Comment by Zeugma440** [comment]
Maybe we should maintain a Google Spreadseet about that bug, this should be way easier than here in GitHub

https://docs.google.com/spreadsheets/d/1Wo9ifsKbBloofdWCsoXziAtaS-QVjqci5aavAV8dt2U/edit#gid=0

Could you complete the spreadhseet with your results ?

**Comment by Zeugma440** [comment]
Should be fine by now. I've made a whole lot of (retrocompatible) changes to create playlist I/O classes with the proper default settings while allowing to force other behaviours at creation-time.

Please refer to the Google Doc for the testing results. Some formats won't play properly on _all_ readers; I've made default settings the ones that work on _most_ readers with files that have exotic charsets.

**Comment by DividedSE** [comment]
I Completed the testing on Excel Sheet. Make it Private and Add its link to main page so general public can see it. Delete the last line on that file. Thanks for fixing as fast as you can. Hope it develop more in future,

**Comment by DividedSE** [comment]
Another think i want to say if u need some testing on tag management feature of ATL, I can also help on testing it. As i currently using another tag management library (that i dont want to say here publicly) which lack some format support but support better tag read/write of custom fields than atl. Maybe its my fault that i dont understanding how to use atl tag feature due to lack of examples. but atl is not working properly for my needs than that library last i test atl tag.

**Comment by Zeugma440** [comment]
I've changed edit rights on the Excel link. I'll read it thoroughly and give an official answer to this issue later.

Concerning your last suggestion, I'd be more than willing to continue discussing this matter in private. Since private messaging is disabled in GitHub, can you contact me on zeugma440@hotmail.com ?

Add a "thumbs up" reaction to this post so that I can remove my coordinates from this message. Thanks in advance.

**Comment by DividedSE** [comment]
I will contact you by email about tags in a week or two about it after some testing. You can remove ur email id & close this topic.

**Comment by Zeugma440** [comment]
Awesome. I'll pur current version to NuGet in the meanwhile.

FYI, custom fields can be manipulated using `IDictionary<string, string> Track.AdditionalFields`

Working example
```
Track theTrack = new Track(audioFilePath);

// Writing
theTrack.AdditionalFields["fancyField"] = "42";
theTrack.Save();

// Reading
String value = "";
if (theTrack.AdditionalFields.ContainsKey("fancyField")) value = theTrack.AdditionalFields["fancyField"];
```
