### ISSUE TITLE
Track.Save() slow in UWP for MP3 files

### ISSUE THREAD

**Issue by mattjopete** [Zeugma440/atldotnet#36]
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to ATL).
Tell us what you were trying to do and what happened instead.

When I call Track.Save() from my UWP application the process takes about 5 minutes for a 50 minute MP3 file with ID3v2 headers. Testing the same library via a unit test the same operation only takes a second or two.  While the file is saving the CPU and RAM are not being pushed but my disk usage is up at 80%.

## Environment

* ATL version (or git revision) that exhibits the issue: 2.11.0
* Last ATL version that did not exhibit the issue (if applicable): N/A It's been consistent for at least the last few months.  
* OS/version used to run ATL
Windows 10 1903.  Targeting Windows 1809 with Fall Creators update being the minimum version.  My audio file code is in a .Net Standard 2.1 library.  

## Details

If necessary, describe the problem you have been experiencing in more detail.

Don't forget to include ATL.Logging.Log and/or console output

## Code To Reproduce Issue [ Good To Have ]

```
public class ATLMetadataService : IMetadataService
    {
        private Track Track { get; set; }

        public Metadata Read(Stream fileStream, MimeType mimeType)
        {
            Track = new Track(fileStream, "audio/mp3");
            var useless = Track.EmbeddedPictures;
            return Track.ToMetadata();
        }

        public async Task<bool> Save(Metadata fileData)
        {
            try
            {
                Track.UpdateMetadata(fileData);
                await Task.Run(() => Track.Save());               
            }
            catch(Exception ex)
            {
                Console.WriteLine(ex);
                return false;
            }
            return true;
        } 
    }
```

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

**Comment by Zeugma440** [comment]
Hello @mattjopete 

I confirm that by design, ATL tends to use disk I/O much more than CPU or RAM. Recent optimizations have also been made (v2.11) to handle padding, so that adding 1 byte of metadata on a padded file does not move the entire file by 1 byte, and consume padding instead.

Let's consider you've already done all you can to optimize your UWP application and disk I/O is the one remaining thing that drags performance down.

I'm sure there are solutions where we can find the right tradeoff between disk I/O and RAM.

First question : does your app access files locally or over a network ?  Since your sample code is using a stream, it's not easy to tell...

**Comment by mattjopete** [comment]
My main concern isn't really that the disk IO exists but that it takes so long for the save to finish.  The file is a local file but converted to a stream.  Here is a simplified version of the code.  My repo is [https://github.com/mattjopete/chaptifier](here) if you want to see the code in it's entirety.
 
ViewModel.cs
```
public async Task OpenFile()
{
    IStorageFile file = await fileController.GetAudioFileAsync();
    IRandomAccessStream stream = await file.OpenAsync(FileAccessMode.ReadWrite);
    Metadata metadata = metadataService.Read(fileStream.AsStream(), MimeType.MP3);

//Reads properties from the metadata for the view
}

public void SaveFile()
{
    metadataService.Save(this.ToMetadata());
}
```

FileController.cs
```
public async Task<IStorageFile> GetAudioFileAsync()
{
    return await audioFilePickerAsync.PickAudioFileAsync().StorageFile;
}
```
AudioFilePickerAsync.cs
```
public async Task<FileModel> PickAudioFileAsync()
{
    var picker = new FileOpenPicker();
    picker.ViewMode = PickerViewMode.List;
    picker.SuggestedStartLocation = PickerLocationId.MusicLibrary;
    picker.FileTypeFilter.Add(".mp3");
          
    var file = await picker.PickSingleFileAsync();

    return new FileModel
    {
        StorageFile = file
    };
}
```
ViewModelExtensions.cs
```
public static Metadata ToMetadata(this OverviewPageViewModel viewModel)
{
    return new Metadata
    {
        Chapters = viewModel.Chapters.Select(c => c.ToChapter()),
        Title = viewModel.Title,
    };
}
```
ChapterExtensions.cs
```
public async static Task<BitmapImage> GetImageAsync(this Chapter chapter)
{
    if (chapter.PictureData == null)
        return null;
            
     return await chapter.PictureData.Image.ToBitmapImageAsync();
}

public static async Task<ChapterDetailsViewModel> ToChapterViewModelAsync(this Chapter chapter, IImageFilePickerAsync imageFilePicker)
{
    var chapterViewModel = new ChapterDetailsViewModel(imageFilePicker)
    {
        Title = chapter.Title,
        StartTime = chapter.StartTime.ToString(),
        EndTime = chapter.EndTime.ToString(),
    };

    if(chapter.PictureData != null)
    {
        chapterViewModel.Image.Filename = chapter.PictureData.FileName;
        chapterViewModel.Image.FilePath = chapter.PictureData.FilePath;
        await chapterViewModel.Image.SetImageData(chapter.PictureData.Image);
    }
    return chapterViewModel;
}
```

**Comment by Zeugma440** [comment]
@mattjopete There seems to be nothing wrong with that code. Plus using a local file _really_ shouldn't be that long.

I advise you to use a profiling tool such as http://www.getcodetrack.com/ to pinpoint the problem (in terms of "which calls / methods are lagging"). I'll work on optimizations according to these results.

**Comment by Zeugma440** [comment]
From where I stand, I feel there's something wrong with UWP.
I ran performance tests on a .NET Framework console app and had the same results as what you reported when using unit tests (i.e. couple seconds).

**Comment by mattjopete** [comment]
I'm finally getting a chance to look at this a bit more.  The slowness is mostly in StreamUtils.CopySameStream.  
```
s.Seek(offsetFrom + length - written - bufSize, SeekOrigin.Begin); //30% of execution
s.Read(data, 0, bufSize); //15% of execution
```

![image](https://user-images.githubusercontent.com/29406666/62414171-8842f480-b5dd-11e9-8a9d-384dc497258b.png)

**Comment by mattjopete** [comment]
Is there a reason that CopySameStream can't be simplified down to this?
```
public static void CopySameStream(Stream s, long offsetFrom, long offsetTo, int length, int bufferSize = BUFFERSIZE)
        {
            if (offsetFrom == offsetTo) return;

            byte[] data = new byte[length];

            //If length is longer than the rest of the stream this will break, but that's not new
            s.Seek(offsetFrom, SeekOrigin.Begin);
            s.Read(data, 0, length);
            s.Seek(offsetTo, SeekOrigin.Begin);
            s.Write(data, 0, length);
        }
```

**Comment by Zeugma440** [comment]
Hey and sorry for the late reply. I'm currently on vacations away from my development rig and experiencing the Terrible Laptop Experience (tm)

The version of `CopySameStream` you're suggesting is a specialized version that probably works fine for the very case you're testing, but is not appropriate for the library.

For instance, if the chunk to copy is 200MB long, the algorithm you posted will load 200MB in RAM, which is not the behaviour people expect from a library, especially if it is used in a platform where resources are limited (e.g. mobile) or as a tiny part of an app that needs memory to do something more important than tagging (e.g. signal processing, in an audio player). That's why I/O is buffered in ATL.

If your goal is to reduce the number of iterations, I can make it so that the default buffer size is editable with the `Settings` class. If your hypothesis is true (UWP checking for permission for every I/O operation), that should be a good start for reducing processing time.

**Comment by mattjopete** [comment]
Absolutely, I'm perfectly willing to try that out and see where it can take me.

**Comment by Zeugma440** [comment]
Alright, I'm back for good, and my other project just got released yesterday ;-)

Sorry for the delay; I'm taking time this week-end to work on ATL. Stay tuned !

**Comment by Zeugma440** [comment]
@mattjopete Commit f3650cbdc56e34e2b6a55ee86f8716b9873e8a5c allows you to control file buffer size using `Settings.FileBufferSize`.

You can now experiment with different buffer sizes and see if it helps you reducing processing time.

**Comment by mattjopete** [comment]
That looks like that will work for me.  I can't really test it in my code before it's published to nuget.   

I'm not sure why, but Track.Save() returns immediately without actually saving the file changes when I try to include ATL.Net as a project.  whereas it is fully functional from nuget.

**Comment by Zeugma440** [comment]
You can now use the new nuGet package (v2.13) that includes the adjustment I did for you.

**Comment by mattjopete** [comment]
Hey, Thank you.  I was just able to implement this in my project.  Save times went from 5+ minutes to  about a second by using this:
```
Settings.FileBufferSize = fileStream.Length > int.MaxValue
                ? int.MaxValue
                : (int)fileStream.Length;
```
