### ISSUE TITLE
Short ogg opus file not loaded correctly

### ISSUE THREAD

**Issue by mikeesouth** [Zeugma440/atldotnet#39]
## The problem

I'm using this library to load mp3 and ogg tracks. With ogg I need support for both vorbis and opus encoding. This seems to work great but **short ogg opus tracks doesn't load**. I'm using Google Cloud Text-to-Speech and for example the word "Hey" is 811 ms long (according to CSCore.Opus library) but this lib (atldotnet) gives 0 duration and the track isn't initialized. If I get the speech for the text "Hey Google" it works as expected (atldotnet gives a duration and the track loads). If I encode "Hey" with mp3 it works as expected even with atldotnet. Alot of shorter words (hey, of, and, in) does not load with ogg opus and atldotnet.

## Environment

* ATL version (or git revision) that exhibits the issue: 2.12
* Last ATL version that did not exhibit the issue (if applicable): N/A
* OS/version used to run ATL: Windows 10

## Code To Reproduce Issue

This code reproduces the problem:

            Track theTrack = new Track("C:\\temp\\hey-opus.ogg");
            var duration = theTrack.DurationMs; // Expected 811, got 0.

The file (hey-opus.ogg) is uploaded here: https://ufile.io/nsy5t80b

**Comment by Zeugma440** [comment]
Thanks for the detailed report and the sample. I'll come back to you in the next days.

**Comment by Zeugma440** [comment]
Alright, the issue was a certain part of the code never expected an OGG file to be _that_ small.

Could you please update `master` branch and tell me if latest commit fixes the issue ? (it definitely should)

Cheers,
-Z440

**Comment by mikeesouth** [comment]
Thanks for the quick response and handling of this bug, it works great! I've been out sick so I haven't had the chance to test it until now.

Can you create a new release with this fix?

**Comment by Zeugma440** [comment]
Sure thing 👍 

New version should be published to nuGet in the beginning of next week. I'm still waiting for confirmations for other fixes.

**Comment by Zeugma440** [comment]
New nuGet package published (v2.13) ! 

Have fun~
