### ISSUE TITLE
Exception when try parse a audio file. 

### ISSUE THREAD

**Issue by MikiraSora** [Zeugma440/atldotnet#40]
## The problem
![image](https://user-images.githubusercontent.com/7549173/64917816-3fc74b00-d7c7-11e9-8f91-9e1ff4c1ca2f.png)

## Environment

* ATL 2.12.0.0 from nuget
* from ATL 2.8.0.0 to latest

## Details

throw exceptions but it's still work for getting audio duration.

## Code To Reproduce Issue [ Good To Have ]

[Part code](https://github.com/OsuSync/OsuLiveStatusPanel/blob/audio_duration/OsuLiveStatusPanel/PPShow/InfoOutputter.cs#L78-L90)

**Comment by Zeugma440** [comment]
Welcome back @MikiraSora and thanks for the report !

The code you submitted is fine; I think the issue is a bug inside ATL.

Unfortunately, I can't reproduce it on my side. Could you upload one of the audio files that causes the issue ?


Thanks in advance,
-Z440

**Comment by MikiraSora** [comment]
I forget.
https://puu.sh/Ehqyq/0126008d21.mp3

**Comment by Zeugma440** [comment]
Thanks. 

The APE header and footer of that file are incorrect, as they record an invalid tag size. That's why ATL got confused.

I've written a few lines to handle that more gracefully. Now an error will be written to the ATL log, and the APE tag will be ignored.

=> Could you check the latest commit to `master` and confirm it works for you ?

Cheers,
-Z440

**Comment by MikiraSora** [comment]
it's still not work on same audio file . 
I just want a audio duration but it always return 0.
![](https://puu.sh/EhHmX/dc7f389497.png)
```C#
class Program
    {
        static void Main(string[] args)
        {
            var track = new Track(@"‪‪E:\2.mp3");

            Console.WriteLine(track.Duration * 1000);
        }
    }
```

**Comment by Zeugma440** [comment]
I can successfuly read the duration on my side. 

By looking closely, the exception you're now getting is something very different than before.
I can't read chinese, but it looks like an I/O credentials issue (file locked by another app that already opened it ?)

Could you try again while closing any other app that use the audio file ? 😄 

Last but not least, `Track` has a recent `DurationMs` field that displays the actual duration in milliseconds. You don't need to use `Duration * 1000` anymore.

**Comment by Zeugma440** [comment]
You can now use the new nuGet package (v2.13) that includes the fix I did for you.

Can you confirm it's okay on your side ?

**Comment by MikiraSora** [comment]
ok it fixed.
thx a lot for my problem :D
