### ISSUE TITLE
Bitrate is null for mp3-file

### ISSUE THREAD

**Issue by StefH** [Zeugma440/atldotnet#41]
## The problem
Bitrate is reported as 0 for specific mp3 file.

## Environment
* ATL version = 2.5.0.0
* OS/version = windows 10

## Details
Bitrate is reported as 0 for specific mp3 file.

[04 - Dolphins Cry.zip](https://github.com/Zeugma440/atldotnet/files/3879282/04.-.Dolphins.Cry.zip)

**Comment by Zeugma440** [comment]
Hi @StefH and thanks for the feedback.

The file you submitted has a badly formatted (not to say nightmarish) header frame.

I've updated ATL so that it gracefully fails when reading such frames. The update will be available on nuGet in a few moments.
