### ISSUE TITLE
Feature request please return duration in milliseconds, seconds is not precise enough for audiobooks

### ISSUE THREAD

**Issue by ElmoFuntz** [Zeugma440/atldotnet#44]
## The problem

I want to use this library for an audobook chapterizer but it only returns time in seconds which can significantly throw off chapter marks when encoding. I had this problem when passing only pulling seconds with ffprobe and passing chapter data to ffmpeg to encode. This was fixed (for the most part) changing to milliseconds.

Please provide an option for those of us who need a more precise time measurement.

**Comment by Zeugma440** [comment]
Please check out the `Track.DurationMs` field that should meet your needs 😉
