### ISSUE TITLE
ATL unable to read some M4A files

### ISSUE THREAD

**Issue by ElmoFuntz** [Zeugma440/atldotnet#45]
## The problem

I have a handful of audiobook files I've tested (and a ton i have not) that ATL is erroring when reading but they play and act (chapters work, etc) as expected in VLC, iTunes, and iOS devices.

The error I am getting is

d:/test.m4a | neither stco, not co64 atoms could not be found; aborting read [?=92155 ms]

I am not sure how these files are different please let me know what extra information (and how) i can extract and provide.

## Environment

* ATL version: 2.15
* Last ATL version: NA
* OS/version used to run ATL: VS2019, Win10, .net 4.8

## Details
See above. I may be able to provide sample data but the smallest file is 500MB. Comparing it to a working M4A with mediainfo did not show anything odd to me but i'm pretty new at doing all this so won't pretend to be an expert.

## Code To Reproduce Issue [ Good To Have ]

I am using your example code to read metadata

**Comment by Zeugma440** [comment]
Hi and thanks for your feedback !

The error message you're getting means the M4A parser is expecting a standard and essential element of the metadata structure, but did not find it.

As far as I know, ATL has been tested mostly against music and podcast files. I'm not sure many users have tried reading entire audiobooks with it. There might be specifics that I'm unaware of.

I'm sorry but I fear you'll have to provide either a link or file (through wetransfer, mega,...) for me to diagnose that issue. Contact me with a DM if you don't want to post that publicly.

**Comment by ElmoFuntz** [comment]
I'm not sure how to DM you but I can drop the file somewhere once I know how to privately share the link.

**Comment by Zeugma440** [comment]
Jeez, you're right, you actually can't on GitHub. It must be one of the few social places where you can't contact anyone privately 😆 

Just send a mail to [my github username][at]hotmail.com. I'll delete this post when I get your message.

**Comment by ElmoFuntz** [comment]
I'm uploading via wetransfer right now.

**Comment by Zeugma440** [comment]
Got it. Thanks for the file !

I'll take a look in the beginning of january, when I'm back from vacations.

**Comment by Zeugma440** [comment]
Just added support for M4B files.

Can you pull the latest commit from `master` and tell me if it works for you ?

**Comment by Zeugma440** [comment]
Turns out the library didn't handle a certain atom properly. It's fixed now. The metadata from the whole file, chapters included, can now be read.

Can you pull the latest commit from `master` and tell me if it works for you ?

**Comment by ElmoFuntz** [comment]
Awesome this update fixes the reported problem!
