### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by MikiraSora** [Zeugma440/atldotnet#5]
## The problem

Parse some audio file and throw expection,but other audio file is fine.

## Environment

* ATL version : v2.3.0.0 from Nuget
* VisualStudio2017 and .Net4.6.1
* OS/version Win10 1709

## Details

[audio file](https://puu.sh/zm5b8/29e15cf136.mp3)

![part of stack](https://puu.sh/zm5hk/08d4be7592.png)

## Code To Reproduce Issue [ Good To Have ]

[code from this](https://github.com/MikiraSora/LyricDisplayerPlugin/blob/master/LyricDisplayerPlugins.cs#L196)

```C#
private int GetDurationTime(string osu_file_path)
        {
            string parent = Directory.GetParent(osu_file_path).FullName;

            string audio_path =Path.Combine(parent,GetAudioFilePath(osu_file_path));

            if (audio_path==null)
            {
                return -1;
            }

            var track = new Track(audio_path);

            Utils.Debug("duration:" + track.Duration);

            return track.Duration * 1000;//convert to ms
        }
```

**Comment by Zeugma440** [comment]
Fixed in 5789e888c5777c1873e120589e0b1f4695178ac8

Thanks for pointing this out @MikiraSora !
