### ISSUE TITLE
Possible to remove specific tags?

### ISSUE THREAD

**Issue by ElmoFuntz** [Zeugma440/atldotnet#50]
Is there a way to remove a single (or set of) tags? I saw the Remove function in Track.cs but i'm unsure how this works it shows tagtype = 99 in intellisense which makes me think its to remove them all?

**Comment by Zeugma440** [comment]
Remove is indeed to remove an entire tag type (e.g. ID3v2 or APE) from a file

If you want to remove a field, just assign an empty value `""` to it
