### ISSUE TITLE
Feature request ATL.Version

### ISSUE THREAD

**Issue by ElmoFuntz** [Zeugma440/atldotnet#51]
Would it be possible to create an ATL.Version function that returns a text string of the version of the DLL? I know at a minimum i'd like to use it for my about box for credit but it also helps to be sure i'm using the right version in testing.

**Comment by Zeugma440** [comment]
A new `Version.getVersion` method will be added in next version

**Comment by ElmoFuntz** [comment]
This works great. Thanks!
