### ISSUE TITLE
Unable to read lyrics from m4a

### ISSUE THREAD

**Issue by action0jackson** [Zeugma440/atldotnet#52]
I am using this library to read the lyrics from mp3 and m4a files.  I have used MusicBee to embed lyrics into my m4a files and when using this library to retrieve the lyrics it is showing no lyrics available.  It will display the lyrics of the mp3 file fine, but not the m4a files.

* ATL version 2.16.0 (Using nuget package):
* Windows 10 Pro
* Using nuget package through LINQPad.

Code I am using:
```csharp
var track = new Track(PathToFile);  
var lyrics = track.Lyrics.UnsynchronizedLyrics;
```

Track.Lyrics is empty for both Synchronized and UnsynchronizedLyrics.

**Comment by Zeugma440** [comment]
Hello and thanks for your feedback.

The answer is super simple : so far, the library only works with ID3v2 lyrics. MP4/M4A lyrics have not been implemented.

However, as I'm currently working _a lot_ on this format, adding lyrics support should be feasible.

I'm gonna do some tests with MusicBee and keep you informed.

**Comment by action0jackson** [comment]
I appreciate your efforts. I just want to say how much more user-friendly and simple your library is than a few others I tried.

Let me know if there is any way I can help.

**Comment by Zeugma440** [comment]
Support for unsynchronized lyrics in MP4/M4A will be available on next release~

Stay tuned !

**Comment by action0jackson** [comment]
Awesome!  What do your release cycles typically look like?

**Comment by Zeugma440** [comment]
The library is not in active development; I work on it whenever users report issues or ask for new features.

Next release should be out as soon as current open issues are solved.
I'd say between 2 days and 2 weeks if that's acceptable for you.

**Comment by action0jackson** [comment]
Oh, I'm in no hurry, don't stress.  I was just curious.  I'm just using it in a pet project anyway.  ;)

**Comment by Zeugma440** [comment]
Will be published in today's release
