### ISSUE TITLE
M4A/MP4 - Support for editing QT chapters

### ISSUE THREAD

**Issue by Zeugma440** [Zeugma440/atldotnet#53]

**Comment by ElmoFuntz** [comment]
Any updates on how is progress going?

**Comment by Zeugma440** [comment]
As of today, unit testing of QT chapters edition and creation is working like a charm on simple files.

I'm now testing the new features against real-life files and there are still adjustments to be made. I'll reply to this issue as soon as everything works.

**Comment by Zeugma440** [comment]
Alright, all my tests are all passing now. Please give it a try @ElmoFuntz !

[ATL-20200208.zip](https://github.com/Zeugma440/atldotnet/files/4173936/ATL-20200208.zip)

_Important notes_
1/ Support for quicktime chapters interleaved with audio data is not there yet, since it requires new mechanisms to edit. When encountering such files, **ATL will log a warning message and ignore Quicktime chapters**. Please tell me if you find such files in your collection.

2/ The "strip MP4 tags" option of MP3tag is super lazy, as it just removes a tiny part of the header instead of cleaning all chapter-related data. It sometimes makes the file unreadable by iTunes (for instance the one you sent me). ATL cannot fix this.

**Comment by ElmoFuntz** [comment]
Awesome will give it a try tomorrow probably. I understand ATL can't fix chapters broken by removing via mp4tag but is it possible to clear all chapter data using ATL since mp3tag doesn't seem the best choice?

**Comment by Zeugma440** [comment]
ATL should work fine to clear/remove all chapters properly, except :
- On files improperly "stripped" by mp3tag
- On files with interleaved Quicktime chapters

**Comment by ElmoFuntz** [comment]
Sorry that took so long to test. Had to patch servers all weekend.. So at first glance its working much better. Chapters ARE showing up in iTunes now and on the iPhone but you are doing them different than i have seen before and I suspect that is why on the first save it's taking a very very long time to save. It also wiped out all the chapters I had previously embedded. This behavior is new, it was just inserting them in addition before.

This is your new save according to MediaInfo

```
Menu #1
ID                                       : 2
Codec ID                                 : text
Duration                                 : 131 h
Encoded date                             : UTC 2020-02-10 22:07:11
Tagged date                              : UTC 2020-02-10 22:07:11
Menu For                                 : 1
Source duration                          : 178164
Source_Duration_FirstFrame               : -77481
Source_Duration_LastFrame                : -14355
Source frame count                       : 3
Source stream size                       : 66
Frame count                              : 5270
mdhd_Duration                            : 36027592
00:00:00.000                             : malarky1
00:00:12.518                             : malarky2
00:01:42.518                             : malarky3
Bit rate mode                            : CBR

Menu #2
00:00:00.000                             : malarky1
00:00:12.519                             : malarky2
00:01:42.519                             : malarky3
```

This is what it looked like before saving only those 3 test chapters.

```
Menu #1
ID                                       : 2
Codec ID                                 : text
Duration                                 : 18 h 1 min
Language                                 : English
Menu For                                 : 1
00:00:00.000                             : Chapter 1
00:25:46.402                             : Chapter 2
00:43:07.631                             : Chapter 3
00:58:12.233                             : Chapter 4
01:22:57.706                             : Chapter 5
01:43:26.041                             : Chapter 6
02:17:11.889                             : Chapter 7
02:36:30.425                             : Chapter 8
02:56:43.296                             : Chapter 9
03:24:37.222                             : Chapter 10
03:47:49.862                             : Chapter 11
04:15:04.453                             : Chapter 12
04:34:12.772                             : Chapter 13
04:55:31.123                             : Chapter 14
05:13:54.395                             : Chapter 15
05:33:40.423                             : Chapter 16
05:50:12.518                             : Chapter 17
06:06:28.824                             : Chapter 18
06:31:47.409                             : Chapter 19
06:52:59.073                             : Chapter 20
07:18:18.819                             : Chapter 21
07:39:31.922                             : Chapter 22
08:03:46.234                             : Chapter 23
08:26:23.161                             : Chapter 24
08:51:32.504                             : Chapter 25
09:11:54.663                             : Chapter 26
09:29:28.245                             : Chapter 27
09:54:09.399                             : Chapter 28
10:09:53.754                             : Chapter 29
10:32:29.381                             : Chapter 30
10:52:47.174                             : Chapter 31
11:26:42.310                             : Chapter 32
11:56:45.850                             : Chapter 33
12:11:31.830                             : Chapter 34
12:30:44.654                             : Chapter 35
12:55:31.892                             : Chapter 36
13:18:40.073                             : Chapter 37
13:47:23.643                             : Chapter 38
14:01:11.387                             : Chapter 39
14:19:44.830                             : Chapter 40
14:49:19.345                             : Chapter 41
15:17:10.252                             : Chapter 42
15:37:22.519                             : Chapter 43
16:02:21.134                             : Chapter 44
16:28:14.131                             : Chapter 45
16:52:43.582                             : Chapter 46
17:14:54.224                             : Chapter 47
17:38:03.241                             : Chapter 48
17:55:07.473                             : Chapter 49
Bit rate mode                            : VBR

Menu #2
00:00:00.000                             : Chapter 1
00:25:46.402                             : Chapter 2
00:43:07.631                             : Chapter 3
00:58:12.233                             : Chapter 4
01:22:57.706                             : Chapter 5
01:43:26.041                             : Chapter 6
02:17:11.889                             : Chapter 7
02:36:30.425                             : Chapter 8
02:56:43.296                             : Chapter 9
03:24:37.222                             : Chapter 10
03:47:49.862                             : Chapter 11
04:15:04.453                             : Chapter 12
04:34:12.772                             : Chapter 13
04:55:31.123                             : Chapter 14
05:13:54.395                             : Chapter 15
05:33:40.423                             : Chapter 16
05:50:12.518                             : Chapter 17
06:06:28.824                             : Chapter 18
06:31:47.409                             : Chapter 19
06:52:59.073                             : Chapter 20
07:18:18.819                             : Chapter 21
07:39:31.922                             : Chapter 22
08:03:46.234                             : Chapter 23
08:26:23.161                             : Chapter 24
08:51:32.504                             : Chapter 25
09:11:54.663                             : Chapter 26
09:29:28.245                             : Chapter 27
09:54:09.399                             : Chapter 28
10:09:53.754                             : Chapter 29
10:32:29.381                             : Chapter 30
10:52:47.174                             : Chapter 31
11:26:42.310                             : Chapter 32
11:56:45.850                             : Chapter 33
12:11:31.830                             : Chapter 34
12:30:44.654                             : Chapter 35
12:55:31.892                             : Chapter 36
13:18:40.073                             : Chapter 37
13:47:23.643                             : Chapter 38
14:01:11.387                             : Chapter 39
14:19:44.830                             : Chapter 40
14:49:19.345                             : Chapter 41
15:17:10.252                             : Chapter 42
15:37:22.519                             : Chapter 43
16:02:21.134                             : Chapter 44
16:28:14.131                             : Chapter 45
16:52:43.582                             : Chapter 46
17:14:54.224                             : Chapter 47
17:38:03.241                             : Chapter 48
17:55:07.473                             : Chapter 49

```

This is the code I used. I'm not currently doing anything with the actual existing chapters while we test this so I've hard coded some to insert.

```
         private void btnSave_Click(object sender, EventArgs e)
        {
            // Adapt this to whatever your file path needs to be
            string fileName = "d:/test.m4b";

            IProgress<float> progress = new Progress<float>(displayProgress);
            // Load audio file information into memory
            Track theTrack = new Track(fileName, progress);

            // Modify metadata
            theTrack.Artist = "Hey ho";
            theTrack.Composer = "Oscar Wilde";
            theTrack.Album = "Fake album starts here and is longer than the original one";

            if (theTrack.EmbeddedPictures.Count > 0 && picAlbumArt.Image != null)
            {
                theTrack.EmbeddedPictures.Clear();
                ImageConverter converter = new ImageConverter();
                byte[] data = (byte[])converter.ConvertTo(picAlbumArt.Image, typeof(byte[]));
                PictureInfo newPicture = PictureInfo.fromBinaryData(data, PictureInfo.PIC_TYPE.Front);
                theTrack.EmbeddedPictures.Add(newPicture);
            }

            //Settings.ID3v2_tagSubVersion = 3;
            //Settings.ID3v2_forceUnsynchronization = true;
            theTrack.Chapters = new System.Collections.Generic.List<ChapterInfo>();

            ChapterInfo ch = new ChapterInfo();
            ch.StartTime = 0;
            ch.StartOffset = 0;
            ch.EndTime = 12519;
            ch.EndOffset = 12519;
            ch.UniqueID = "";
            ch.Title = "malarky1";
            ch.Subtitle = "bobs your uncle now";
            theTrack.Chapters.Add(ch);

            ch = new ChapterInfo();
            ch.StartTime = 12519;
            ch.StartOffset = 12519;
            ch.EndTime = 102519;
            ch.EndOffset = 102519;
            ch.UniqueID = "";
            ch.Title = "malarky2";
            ch.Subtitle = "bobs your uncle now";
            theTrack.Chapters.Add(ch);


            ch = new ChapterInfo();
            ch.StartTime = 102519;
            ch.StartOffset = 102519;
            ch.EndTime = 3002519;
            ch.EndOffset = 3002519;
            ch.UniqueID = "";
            ch.Title = "malarky3";
            ch.Subtitle = "bobs your uncle now";
            theTrack.Chapters.Add(ch);


            // Save modifications on the disc

            theTrack.Save();
        }
```

**Comment by Zeugma440** [comment]
No problem man ! To each his own priorities 😉 

> It also wiped out all the chapters I had previously embedded. This behavior is new, it was just inserting them in addition before.

If you'd like to just add chapters to the existing list, you should comment out the following line that resets the list.
```csharp
theTrack.Chapters = new System.Collections.Generic.List<ChapterInfo>();
```

> on the first save it's taking a very very long time to save.

QT chapters require much heavier modifications on the file, so the editing takes longer than the previous version I gave you.

Could you elaborate on what you call "very very long" ? On my machine (mid-tier desktop PC), editing a 356 MB file with the code you posted takes 4-5 secs.

I'd be happy to help you optimize that.

**Comment by ElmoFuntz** [comment]
Oh did I miss something I added in that overwrites them all? Oops. I didn't think i had added that. See what happens when you (I) don't work on something for a week or so. :) 

As for the saves I'm pretty sure my machine just likes to mess with me.. The first save converting from the old "format" shown in the previous post above took over 60 seconds but other saves after it (that made no changes though) take 19 seconds. This isn't horrible but it does take a bit... Now I just retested the "first save" thing again (where it had all the original tags from ffmpeg) and this time it was more like 30 seconds.

Other than that first save thing it's looking good so far. I am curious about why the format looks so different than what ffmpeg writes. Mostly wondering how other editors might see/handle it.

**Comment by Zeugma440** [comment]
> As for the saves I'm pretty sure my machine just likes to mess with me.. The first save converting from the old "format" shown in the previous post above took over 60 seconds but other saves after it (that made no changes though) take 19 seconds. This isn't horrible but it does take a bit... Now I just retested the "first save" thing again (where it had all the original tags from ffmpeg) and this time it was more like 30 seconds.

Wow, 30 seconds is still a lot of time. Have you tried adjusting file buffer size using `Settings.FileBufferSize` ? Kranking it a little (e.g. 4096) should lower the number of I/O operations.

> Other than that first save thing it's looking good so far. I am curious about why the format looks so different than what ffmpeg writes. Mostly wondering how other editors might see/handle it.

I'm assuming menu #2 are the Nero chapters. Now for menu #1 

`Duration                                 : 131 h` -> that one's weird. I don't know why it comes up like this

`Encoded date                             : UTC 2020-02-10 22:07:11
Tagged date                              : UTC 2020-02-10 22:07:11` -> these are fields I set to the date of the editing. I guess FFMpeg did not set those

`Source duration                          : 178164
Source_Duration_FirstFrame               : -77481
Source_Duration_LastFrame                : -14355
Source frame count                       : 3
Source stream size                       : 66
Frame count                              : 5270
mdhd_Duration                            : 36027592
Bit rate mode                            : CBR` -> I'm using the simplest way to write the chapter track (CBR mode, compared to FFmpeg's VBR mode). My best guess is all those extra fields are specific to CBR mode. To be certain, one needs to look at MediaInfo's sources...

Is that a real problem to you ?

**Comment by ElmoFuntz** [comment]
This might be a bit rambling :) OK holy moly I wish I had known about the Settings.FileBufferSize earlier that made a WORLD of difference at 4096. Dropped first save to 8 seconds and later saves to 4. I don't even care about the progress indicator with that. Now I do need to test how over 100 chapters works and that might make a difference.

Re it being a problem. Not really, my major concern is compatibility with other apps (such as mp3tag) since at some point i'd like to share this if I can make a decent working app.

One thing I noticed and it probably has zero to do with ATL is if I resave (say for example I add album art in) in mp3tag is is rewriting menu #2 and i'm not sure why.

With ATL

```
Menu #1
ID                                       : 2
Codec ID                                 : text
Duration                                 : 131 h
Encoded date                             : UTC 2020-02-12 23:55:11
Tagged date                              : UTC 2020-02-12 23:55:11
Menu For                                 : 1
Source duration                          : 178164
Source_Duration_FirstFrame               : -77481
Source_Duration_LastFrame                : -14355
Source frame count                       : 3
Source stream size                       : 66
Frame count                              : 5270
mdhd_Duration                            : 36027592
00:00:00.000                             : malarky1
00:00:12.518                             : malarky2
00:01:42.518                             : malarky3
Bit rate mode                            : CBR

Menu #2
00:00:00.000                             : malarky1
00:00:12.519                             : malarky2
00:01:42.519                             : malarky3
```

Saved with no changes in mp3tag

```
Menu #1
ID                                       : 2
Codec ID                                 : text
Duration                                 : 131 h
Encoded date                             : UTC 2020-02-12 23:55:11
Tagged date                              : UTC 2020-02-12 23:55:11
Menu For                                 : 1
Source duration                          : 178164
Source_Duration_FirstFrame               : -77481
Source_Duration_LastFrame                : -14355
Source frame count                       : 3
Source stream size                       : 66
Frame count                              : 5270
mdhd_Duration                            : 36027592
00:00:00.000                             : malarky1
00:00:12.518                             : malarky2
00:01:42.518                             : malarky3
Bit rate mode                            : CBR

Menu #2
00:00:00.000                             : The Dragon and the Fair Maid of Kent (Unabridged)
00:00:12.519                             : The Dragon and the Fair Maid of Kent (Unabridged)
00:01:42.519                             : The Dragon and the Fair Maid of Kent (Unabridged)
```

It seems to be pulling it from the below settings but i'm not sure why since I've saved other files that have not done this with mp3tag. It could be some flag is not getting set by ATL maybe? I was able to test this just now and it (mp3tag) did not rewrite the 2nd menu with another file.

```
General
Complete name                            : D:\test.m4b
Format                                   : MPEG-4
Format profile                           : Base Media
Codec ID                                 : isom (isom/iso2/mp41)
File size                                : 491 MiB
Duration                                 : 131 h
Overall bit rate mode                    : Variable
Overall bit rate                         : 8 688 b/s
Album                                    : Fake album starts here and is longer than the original one
Track name                               : The Dragon and the Fair Maid of Kent (Unabridged)
```

As for the weird 131 hours something with the way ATL is writing it is confusing MediaInfo for sure but thats probably (?) a mediainfo thing. The original file reports 18 hours the resaved file 131. I'm not sure this is an issue since ffprobe is reporting it correctly.

```
PS D:\> ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 -sexagesimal .\test.m4b
18:01:38.799000
```

Again this is major progress and i'm happy with the format your using as long as the "popular" editors don't barf themselves over it. So far only the one weird oddity is with mp3tag.

Note: I can tell you for a fact now that iTunes doesn't look at the nero tags. The file I listed above with menu 2 different from menu 1 lists the menu 1 information in iTunes and the Menu 2 information in VLC and foobar.

**Comment by Zeugma440** [comment]
> This might be a bit rambling :) OK holy moly I wish I had known about the Settings.FileBufferSize earlier that made a WORLD of difference at 4096. Dropped first save to 8 seconds and later saves to 4. I don't even care about the progress indicator with that.

Glad to hear that 😉 

> One thing I noticed and it probably has zero to do with ATL is if I resave (say for example I add album art in) in mp3tag is is rewriting menu #2 and i'm not sure why.

Judging from how MP4tag handles the "strip MP4 chapters" feature improperly, I'd be tempted to say the chapters name issue you just saw is yet another problem on their side. I'll give it a test.

In case I can't reproduce that problem with my own test files, could you please send me the one you tested with ?

I'll also take a look at the 131h thing and see if it is related to the duration of the last chapter. That's the only possible source of problem I can think about, since last chapter duration is calculated differently than the others.

**Comment by ElmoFuntz** [comment]
So i just double checked my original test file because I was pretty sure that those new chapter names were not the same as the original ones and I was correct. The original chapters in menu 2 are chapter1, chapter2, etc and a simple save turns them into the book name. So mp3tag is seeing some reason to convert those that it is not seeing in other files. I am guessing its some "flag" or setting in the tags maybe? The same thing happens with the ATL written file or I would not even mention it and blame it all on mp3tag.  I am sending you the test file I have now.

**Comment by Zeugma440** [comment]
> One thing I noticed and it probably has zero to do with ATL is if I resave (say for example I add album art in) in mp3tag is is rewriting menu #2 and i'm not sure why.

I'm reproducing it too, without even using ATL : 
1. Open the original test file in MP3tag _without_ using ATL
2. Save
3. Nero tags are rewritten with the title of the track instead of chapter names

I honestly don't know what's going on inside MP3tag. Since it is not open source, I don't want to lose my time guessing by trial and error. Please contact the MP3tag staff about that one.

**Comment by Zeugma440** [comment]
Just fixed the 131h problem. There was indeed a calculation issue while writing the track's duration. 

It now appears correctly when using MediaInfo.

Can we consider this issue solved ?  If so, please close it and I'll publish the library to NuGet (the version your currently have + the "131h fix")

**Comment by ElmoFuntz** [comment]
Nice on the 131h thing. As for the weird chapter thing my only concern was it does not do it with every file so I wanted ot be sure some extra "flag" was not missed that causes this. One thing I did forget to mention was that last test file i sent was not chapterized by me and i'm unsure what was used to do it. I suspect not ffmpeg. If you think that is not the case by all means please publish. I still have more testing I hope to get started next week and can open a new issue if anything else comes up.

**Comment by Zeugma440** [comment]
Aright. From my side it still looks like an issue on MP3tag's side. I'm closing the issue and you're welcome to open another if needed.

**Comment by Zeugma440** [comment]
Thanks for your time and patience anyway 😉

**Comment by ElmoFuntz** [comment]
After our testing you should update your chapter specs document to indicate
that iTunes and the built in iOS audiobook player ignore nero chapters as
well as the now obsolete Quicktime player..
