### ISSUE TITLE
Unable to Update Popularity Field

### ISSUE THREAD

**Issue by buckmanc** [Zeugma440/atldotnet#54]
## The problem

Writes to popularity field are not preserved after saving the tag. Hoping I'm not just doing something stupid here.

## Environment

* ATL version: 3.0.0
* Last ATL version: NA
* OS/version used to run ATL: Windows 10 Home version 1903, .Net Core 2.2, VS2019

## Code To Reproduce Issue [ Good To Have ]

        static void Main(string[] args)
        {

            // Adapt this to whatever your file path needs to be
            string fileName = "test1.mp3";

            // Load audio file information into memory
            ATL.Track theTrack = new ATL.Track(fileName);

            // Modify metadata
            Console.WriteLine("Popularity pre update: " + theTrack.Popularity);
            theTrack.Popularity = 5;
            Console.WriteLine("Popularity post update: " + theTrack.Popularity);
            theTrack.Save();
            Console.WriteLine("Popularity post save: " + theTrack.Popularity);

        }

Popularity pre update: 0
Popularity post update: 5
Popularity post save: 0

**Comment by Zeugma440** [comment]
**On my side**
You are right, there's been a bug in yesterday's update. Fixing it right now.

**On your side**
Be aware that the `Popularity` field works as a %. For example :
- 1/5 (0.2) is one star
- 2/5 (0.4) is two stars
- 2.5/5 (0.5) is two stars and a half

=> You should set `<number of stars>/5` in your code

**Comment by Zeugma440** [comment]
Fix published on v3.01

**Comment by buckmanc** [comment]
Thanks for the prompt fix and the pointer on how the field works.
