### ISSUE TITLE
XML Docs not packaged with Nuget

### ISSUE THREAD

**Issue by TheMinefighter** [Zeugma440/atldotnet#56]
## The problem
The current nuget package does only contain the dlls for the different frameworks, but not the xml file containing the documentation comments of the whole project. This is a big downside to the UX.

## Environment
Current nuget version (3.2)

## Details

The `DocumentationFile` tag in the csproj must be defined to be a path (e.g. `.\bin\ATL.xml`) to create a xml package of all documentation comments, to be used by IDEs (i.a. for Tooltips when hovering over a method name). This is currently not the case. This file must then be included in the nupkg, in the folders of the respective frameworks.

I can fix that, but the nuget packaging script is currently not included in the package (which might have to be changed for this, maybe send it to me with the access token removed).

**Comment by Zeugma440** [comment]
I can certainly fix that. Thanks a lot for bringing this issue.

**Comment by Zeugma440** [comment]
That's done !  Please check out the latest NuGet (3.03)

**Comment by TheMinefighter** [comment]
Thanks for your work; I can confirm the fix
