### ISSUE TITLE
Loop Points Support

### ISSUE THREAD

**Issue by jackyyang09** [Zeugma440/atldotnet#58]
## The problem

I'd love to see ATL support the reading of loop points. Apparently it's a lesser known field in an audio file's metadata that niche programs can read and write to. I'm working on a music tool and being able to import loop points set in applications like Wavosaur, GoldWave etc will help a lot!

**Comment by Zeugma440** [comment]
Heya @jackyyang09 and thanks for your question.

Could you tell me more about them? Is there are spec or technical description I can refer to?

**Comment by jackyyang09** [comment]
All I personally know is that various niche applications all share an idea of how to save/load loop points in various different audio formats and there are some created for that sole purpose. However, popular applications like Audacity and SoundForge don't use them at all. I've also seen them used in game engines like Source.

In all of my research I've only come across two resources on how they're stored in wav files, but I know they can also be set in oggs and such as well. I can't make sense of them myself with my limited knowledge of file reading but maybe it'll help.

https://sites.google.com/site/musicgapi/technical-documents/wav-file-format#smpl

https://web.archive.org/web/20141217014452/http://www.sonicspot.com/guide/wavefiles.html#cue

Loop Auditioneer is an open source tool dedicated to setting loop points, maybe in the worst case scenario you can crack it open and see how it does things.
http://loopauditioneer.sourceforge.net/

**Comment by Zeugma440** [comment]
Awesome, thanks man. This should be enough to start with the WAV format.

Concerning OGG and other formats, have you checked if the softwares you're using are creating custom metadata to store that ?  That's what I would do if I had to.

**Comment by jackyyang09** [comment]
Oh disregard what I said about OGGs, the loop point standard seems to only exist for WAV files, further proven by how every loop point tool I've come across works exclusively with WAVs. I guess I got thrown off by forums posts on communities concerning very specific engines where users would manually write custom metadata fields. 

In any case, thanks a bunch!

**Comment by Zeugma440** [comment]
I've some up with an implementation but I have no sample to test it against.

Could you provide me with a small WAV file with these data so that I can validate the code ?

You can either add a ZIP file here, or transfer it through dropbox/mega/... to zeugma440 /at/ hotmail.com

**Comment by jackyyang09** [comment]
Sure, here's a short WAV with a starting point set at 47104 samples in and the end point set at the 375808 sample mark
https://mega.nz/file/Ac1HkJTR#1RS2akDTIGR3GSZc-gaaiYYI-R2CjhU8myg5oSVz9VE

**Comment by Zeugma440** [comment]
Looks like these fields have been parsed properly.

Does this looks good to you ?
![sampleValues](https://user-images.githubusercontent.com/29414549/81004749-286bc980-8e4d-11ea-812e-a2a3ff14c430.png)

If nothing's missing, I can publish the update on NuGet soon. Keep me informed !

**Comment by jackyyang09** [comment]
Admittedly the WAV I sent in wasn't well populated at all beyond the loop point fields, but their numbers do seem to check out. Things will be fine and dandy for my use case at least.
In any case thanks a bunch, I look forward to working with it soon!

**Comment by Zeugma440** [comment]
Version 3.04 is out. Have fun !

I've put some examples here : https://github.com/Zeugma440/atldotnet/wiki/3.-Usage-_-Code-snippets#waveSample

**Comment by Zeugma440** [comment]
Whoops, `NumSampleLoops` was not read properly in 3.04. Here's a quick fix in 3.04.1 !
