### ISSUE TITLE
No way to iterate through all tags of track

### ISSUE THREAD

**Issue by IanHot** [Zeugma440/atldotnet#59]
I am currently in the process of trans-coding my tracks. I wish to copy across the track info at the same time. I would like to be able to iterate through all the tags using a foreach loop. 
Have I missed something? 
## Environment

* ATL version (or git revision) that exhibits the issue: 3.4.1
* Last ATL version that did not exhibit the issue (if applicable):
* OS/version used to run ATL Windows 10-64 bit

## Code To Reproduce Issue [ Good To Have ]
using ATL;
using System.Collections.Generic;

            Track srcTrack = new Track(Src.FullName);
            Track dstTrack = new Track(DestFileName);

            foreach(KeyValuePair<string, string> kvp in srcTrack.Tags())
            {
                dstTrack[kvp.Key] = kvp.Value;
            }

**Comment by Zeugma440** [comment]
Hello Ian,

Thanks for your feedback !

Providing big string maps isn't exactly the spirit of the library - except when it comes to custom metadata, but that's not the point here.

To best answer your needs, I could create a new `Track.copyTo(Track)` method that would transfer all metadata from one given `Track` to another. What would you think about that ?

**Comment by Zeugma440** [comment]
No reply from the OP in 27 days

**Comment by Zeugma440** [comment]
@Agagamand That feature is now available on today's v5.13
