### ISSUE TITLE
Popularity is zero for .m4a files even though Windows Explorer stores it in the file

### ISSUE THREAD

**Issue by jnm2** [Zeugma440/atldotnet#63]
## The problem

The Popularity field is always zero for .m4a files. All other expected fields are not empty. I'm not sure how Windows Explorer stores the rating, but it does rewrite the .m4a file each time you change the rating.

## Environment

* ATL version (or git revision) that exhibits the issue: **3.5.0**
* OS/version used to run ATL: **Windows 10.0.19041, x64**

## Details

> Don't forget to include ATL.Logging.Log and/or console output

Full log output for the code in the following section:

```
[DEBUG] C:\Users\Joseph\OneDrive\Music\Infected Mushroom\2018 Head of NASA and the 2 Amish Boys\07. Lost In Space.m4a | total tracks found : 1 [δ=58 ms]
```

## Code To Reproduce Issue [ Good To Have ]

```cs
new ConsoleLogger();
var track new Track(@"C:\Users\Joseph\OneDrive\Music\Infected Mushroom\2018 Head of NASA and the 2 Amish Boys\07. Lost In Space.m4a", load: true);
Console.WriteLine(track.Popularity); // 0
```

**Comment by Zeugma440** [comment]
Heya and thanks for the report !

Turns out Windows being a very special snowflake, doesn't use the standard MP4 tagging atoms to record the rating, but inserts its very own WMA-inspired tag to do it.

I'll be sure to adapt the library so that it can read these tags. However, ATL being attached to standards, I'm not certain it's a good idea to systematically write that horrible Windows tag when writing new ratings to M4A files.

**Comment by Zeugma440** [comment]
To make it even, better, Windows can stack other metadata (e.g. publisher, conductor) into that atom, and does a terrible job at updating its headers when doing so 🙄

**Comment by jnm2** [comment]
Ugh, somehow that doesn't surprise me! If it helps, I'm not currently planning to write to .m4a files. I don't even need the Track.Popularity property to pick it up as long as there's a way to access and manually parse the Windows tag. The only thing I saw that was exposed by ATL that looked hopeful was the AdditionalTags entry with ID `----:com.apple.iTunes:iTunSMPB`. Is that where Windows is putting the rating?

**Comment by Zeugma440** [comment]
> I'm not currently planning to write to .m4a files. I don't even need the Track.Popularity property to pick it up as long as there's a way to access and manually parse the Windows tag.

Sounds fine to me !  

> The only thing I saw that was exposed by ATL that looked hopeful was the AdditionalTags entry with ID ----:com.apple.iTunes:iTunSMPB. Is that where Windows is putting the rating?

Nope, that field is something else. The one we're interested in has been invisible from the library until now.

**Comment by Zeugma440** [comment]
The issue should be fixed by version 3.06. Please check it out and tell me if it works on your side.

**Comment by jnm2** [comment]
@Zeugma440 You're fast! Sure enough, it's working for me. Thank you!

**Comment by Zeugma440** [comment]
You're very welcome. Don't hesitate to spread the word about ATL if you like using it !

**Comment by jnm2** [comment]
Already have and will! It looked like a well-managed library right off the bat.
