### ISSUE TITLE
there's a typo in your very first Usage_Code_Snippet

### ISSUE THREAD

**Issue by daviddennisei** [Zeugma440/atldotnet#64]
## The problem
snippet shows:
```
  using ATL.AudioData;
  Track theTrack = new Track(fileName);

```
should be :
```

  using ATL;
  Track theTrack = new Track(fileName);

```
## Environment

z440.atl.core (3.5.0)
Windows 10 Pro x64
Visual Studio 2019
.NET Core 3.0

## Details
ATL.AudioData; doesn't have a Track class. I had to download the ATL source and search for Track.cs to figure out how to get stated. Kind of a discouraging start.

**Comment by Zeugma440** [comment]
Oops, that's fixed now. Thanks a lot for your feedback !
