### ISSUE TITLE
Write «Toms' losslesss Audio Kompressor» (.tak) not work

### ISSUE THREAD

**Issue by Agagamand** [Zeugma440/atldotnet#65]
## The problem

z440.atl.core can read .tak tags, but canot write.

## Environment

z440.atl.core 3.6.0
Win10 x64.
.net Core 3.1

**Comment by Zeugma440** [comment]
I'm sorry but we can't get very far with that little information :
- Could you post the code you are using ?
- Does your TAK file have tags already or is it empty of metadata ?
- If it already has tags, which are these ?
- Could you possibly send the file (mega / google drive link would be fine) ?

Thanks in advance~

**Comment by Agagamand** [comment]
`        public void TransferAllTags(string origFile, string destFile)
        {
            Track file1 = new Track(origFile);
            Track file2 = new Track(destFile)
            {
                Title = file1.Title,
                Album = file1.Album,
                Artist = file1.Artist,
                AlbumArtist = file1.AlbumArtist,
                Genre = file1.Genre,
                Year = file1.Year,
                TrackNumber = file1.TrackNumber,
                //TrackTotal = file1.TrackTotal,
                Lyrics = file1.Lyrics,
                OriginalAlbum = file1.OriginalAlbum,
                OriginalArtist = file1.OriginalArtist,
                Publisher = file1.Publisher,
                Popularity = file1.Popularity,
                DiscTotal = file1.DiscTotal,
                DiscNumber = file1.DiscNumber,
                Date = file1.Date,
                Copyright = file1.Copyright,
                Conductor = file1.Conductor,
                Composer = file1.Composer,
                Comment = file1.Comment,
                ChaptersTableDescription = file1.ChaptersTableDescription,
                Chapters = file1.Chapters,
                AdditionalFields = file1.AdditionalFields
            };

            foreach (PictureInfo pic in file1.EmbeddedPictures)
                file2.EmbeddedPictures.Add(pic);

            file2.Save();
        }`

I use TAK v2.3.1 Beta 1. 
.tak is empty of metadata when i start using
https://workupload.com/file/9m3H7A4dBQn

**Comment by Zeugma440** [comment]
Okay, so there were two issues on that one :
1/ I set the TAK file format to be compatible with ID3v2 while it apparently isn't
2/ The default settings of the library prevent writing APE tags... and that's the only thing that the TAK file format supports
=> Now if none of the selected metadata formats allow writing, the library falls back to the first supported metadata format of the selected file

That should be it for your case 😀  Do you want to test with the new source or would you rather have a new library published to NuGet ?

**Comment by Agagamand** [comment]
I want new library published to NuGet.

**Comment by Zeugma440** [comment]
v3.07 published ! The new NuGet package will be available shortly. Enjoy~~
