### ISSUE TITLE
Quicktime audio chapters again

### ISSUE THREAD

**Issue by audiamus** [Zeugma440/atldotnet#67]
## The problem

Quicktime chapters, added with ATL.NET, appear to have incorrect times. Nero chapters, on the other hand, are OK.

## Environment

* ATL.NET v3.8
* .Net framework 4.7.1 application, with some .Net Standard 2.0 assemblies.
* Win7

## Details

Until now, I used FFmpeg to add chapter meta data to my MPEG4 audiobooks (.m4a/.m4b). However, this sometimes corrupted the audio stream. Now I have tried ATL.NET. 

I toggled 
` ATL.Settings.MP4_createNeroChapters = false;
ATL.Settings.MP4_createQuicktimeChapters = true;`
to be able to clearly identify the output. While "Nero" comes out correctly, "Quicktime" dramatically compressed all times.

*This is the MediaInfo view for "Nero":*
![info-nero](https://user-images.githubusercontent.com/47717419/92263240-96e49500-eedc-11ea-811e-af35af096678.png)

*And this is the MediaInfo view for "Quicktime", same book, same chapter info:*
![info-quicktime](https://user-images.githubusercontent.com/47717419/92263254-9ba94900-eedc-11ea-9586-fb0ff0caa9ca.png)

*And that's the way the "Quicktime" chapter marks look in VLC:*
![vlc-quicktime](https://user-images.githubusercontent.com/47717419/92263260-9ea43980-eedc-11ea-9f9b-aa218829b320.png)
*(With "Nero" the chapter marks would be correct and fill the whole bar.)*

## Code To Reproduce Issue

```
        tagFile.Chapters.Clear ();

        foreach (var ch in _part.Chapters) {
          var chi = new ATL.ChapterInfo {
            StartTime = (uint)ch.Time.Begin.TotalMilliseconds,
            EndTime = (uint)ch.Time.End.TotalMilliseconds,
            Title = ch.Name
          };
          tagFile.Chapters.Add (chi);
        }

        tagFile.Save ();
```

**Comment by Zeugma440** [comment]
Hi and thanks for your feedback

Could you upload the corresponding file so that I can test with it? MP4 is a complex format, I need to have the exact same setup as you.

**Comment by audiamus** [comment]
> Could you upload the corresponding file

That's difficult because it's copyrighted material. But I will find a public domain work and recording and try to reproduce the effect with that. I am somewhat optimistic here because I noticed the Quicktime chapter issue with all books in MP4 format so far.

**Comment by audiamus** [comment]
So, here we go. Apparently, there is a 10 MB upload limit, which is tight but just enough for this example.

`huck_finn_part.m4b` is our audiobokk, well, the beginning of it.
`huck_finn_part.txt` is raw chapter meta data for this bit, created with Audacity.
 
Then we have a little test program, that is able to read this meta data and create chapters from it. The program will create both the Nero and the Quicktime variants. It's simplistic, without any sort of error checking. You will have to adjust the settings in App.config. 

[TestQuicktime.zip](https://github.com/Zeugma440/atldotnet/files/5178314/TestQuicktime.zip)

The meta data defines 5 chapters. All will be OK for Nero and and the first 4 for Quicktime as well. But number 5, with title "Chapter 2" will be incorrect in Quicktime. It should start at 00:08:47.877 but says to begin much earlier at 00:02:18.310. The same would occur with all subsequent chapters.

*If you need a longer sample with more chapters, I could reduce the bitrate and try again.*

**Comment by Zeugma440** [comment]
Roger that, I'll check it out and keep you informed. Thanks for your explanations.

**Comment by Zeugma440** [comment]
Looks like I got it  - the code in charge of writing MP4 Quicktime chapter durations was manipulating `uint` variables but needed to use `long` instead.

The fix is available on NuGet (version 3.09). Thanks again for submitting this issue 👍

**Comment by audiamus** [comment]
Excellent. Thanks a lot.

**Comment by Zeugma440** [comment]
I've just seen your repo btw. Would you be interested if ATL could support audible files (i.e. read their specs, duration and metadata) ?

**Comment by audiamus** [comment]
> Would you be interested if ATL could support audible files (i.e. read their specs, duration and metadata) ?

That would be great. At the moment I am using TagLibSharp for reading the non-chapter metadata (and FFmpeg for chapters). The two formats my tool supports are .AAX and .AA. AAX is basically MP4, with an encrypted AAC stream. FFmpeg has the code to decrypt it. AA, or more precisely, "Format 4", has now officially been retired but quite a few people still have lots of books in this format. That's basically MP3, so I think the meta data is ID3V2. 

TagLibSharp can read the meta data for both, but there are a few custom tags. With the help of Reflection, I can access the internal classes and methods to retrieve those custom tags. So I don't think there is much to do for you. I was already about to test ATL.net with Audible files. I guess I can override the file type if I provide the mime argument. But support out of the box would be more convenient, of course.  

I could then eventually abandon TagLibSharp altogether, which would make the code cleaner.

Thanks again for your offer.

**Comment by Zeugma440** [comment]
tbh I've been wanting to do that for a while but I needed a good reason to, because I'm involved into other coding projects. Now I found it 😉 

You may follow that new issue : https://github.com/Zeugma440/atldotnet/issues/68

**Comment by Zeugma440** [comment]
@audiamus FYI, Audible support (.AA and .AAX) is out today in v1.10. Enjoy~

**Comment by audiamus** [comment]
Great, thank you very much. I will test it. But I have to be a bit careful switching over completely at this time, see #70.
