### ISSUE TITLE
OutOfMemoryException

### ISSUE THREAD

**Issue by audiamus** [Zeugma440/atldotnet#71]
## The problem

Writing chapter data to my .m4a/.m4b file triggers an OutOfMemory exception in 
`ATL.AudioData.IO.FileSurgeon.RewriteZonesBuffered ()`, line 245

## Environment

* ATL version 3.11 (local clone)
* OS/version Win7, .Net 4.7.1

## Details

I was just about to publish the next version of AAX Audio Converter with ATL.net now in charge of all chapter meta data. I was running my final tests, only to find out that no chapters were present for a monolithic book of 521 MB (546.601.176 bytes).

I tracked it down for this to happen only in the release build, not in the debug build. For some initial debugging I built ATL.net myself again, based on your latest release. 

While this memory allocation at line 245 goes through in debug mode without protest, it fires the exception in release mode. Don't ask me why. The exception is caught by ATL.net internally and not forwarded to the caller, hence I couldn't see any reason at first.

What confuses me is that the amount of memory asked for is almost the entire file, 546.601.152 bytes. And this is a rather short book.

![oom-issue](https://user-images.githubusercontent.com/47717419/96347110-a8a28600-109f-11eb-9b6f-404e04ee292e.png)

## Code To Reproduce Issue [ Good To Have ]

Will probably happen with any larger file.

**Comment by Zeugma440** [comment]
Working on it - there's clearly some optimization to be done. I'll keep you informed soon !

**Comment by Zeugma440** [comment]
File I/O tends to load anything potentially rewritable into memory to speed up processing. However, figures go overboard with MP4s. For this format, adjustments can indeed happen over most of the file, but the part that actually needs to be loaded in memory for performance reasons isn't that big.

I just pushed some fine-tuning code to `master` that should definitely help. On my test audiobook file, it lowered memory load from 500MB to 25MB.

However, keep in mind that the consequence of this change is that the operation takes more time to finalize, as bytes have to be moved around on your disk.

To speed that up, you might be interested in fiddling with `Settings.FileBufferSize` (default value = 512 bytes) to find a proper middle ground between memory and performance (e.g. 2MB or 5MB).

Tell me how it goes, I'll release the fix to NuGet when you're happy with it.

PS : So glad to have helped supporting all chapter metadata on AAX Audio Converter !

**Comment by audiamus** [comment]
Thank you for the update. However, we are not quite there, I'm afraid.

Firstly, I have found the reason why it throws in release mode and not in debug mode. My release build was still "prefer 32bit". That wasn't the intention, but quite helpful here as the program had never hit the 32 bit addressing limit until now.

So, the exception no longer thrown, but I still observe that ATL.net is writing the entire file into a memory stream. To illustrate it, I have disabled the initial memory allocation in the MemoryStream ctor, line 325 in FileSurgeon.cs. (Now invoked by `RewriteZonesHybrid()`, not by `RewriteZonesBuffered()` as before.) Then I have taken a memory snapshot before and after `StreamUtils.CopyStream();` and you can clearly see how and where memory usage grows.

Before, btw, with the exception still thrown, the program would never get as far as to even look at `ATL.Settings.FileBufferSize`.

I also attach the call stack.

![oom-issue2a](https://user-images.githubusercontent.com/47717419/96362924-337f9100-1131-11eb-87c6-3c7f352dc8ad.png)
![oom-issue3](https://user-images.githubusercontent.com/47717419/96362931-41351680-1131-11eb-9536-b5330664a712.png)
[oom-issue-callstack.txt](https://github.com/Zeugma440/atldotnet/files/5397256/oom-issue-callstack.txt)

**Comment by Zeugma440** [comment]
Jesus, 1GB... That's the kind of stuff that couldn't be detected with unit tests.

Rather than communicating through screenshots, is there a way you could upload the file you're testing with through a mega / dropbox / any other sharing platform ? I guess you still have my e-mail 😄 

Thanks in advance~

**Comment by Zeugma440** [comment]
Another way of solving it would be to switch to disk-only operations.

1/ Replace the `FileSurgeon` method with that one
```csharp
public bool RewriteZones(
            BinaryWriter w,
            WriteDelegate write,
            ICollection<Zone> zones,
            TagData dataToWrite,
            bool tagExists)
        {
            return RewriteZonesDirect(w, null, write, zones, dataToWrite, tagExists);
        }
```

2/ Before your call to `Track.Save`, set up `Settings.FileBufferSize` to 2MB or 5MB


That would prevent any processing to happen in-memory but would be quite intensive on disk I/O, as a temporary workaround.

**Comment by audiamus** [comment]
> Another way of solving it would be to switch to disk-only operations.

I did that now, with a 2MB buffer, and it appears to be even faster than with the MemoryStream, 300 ms vs 1600 ms for my example. Looks good. :smile:

So, are there any disadvantages using the "direct to disk" method? You do not need random access? If there aren't any drawbacks here, I would like to go for this mode. But it's not yet selectable in ATL.Settings, I presume? 

Quite s a few users of my tool are running it on small laptops with not much memory. But many will have SSDs, so disk I/O shouldn't be the limiting factor. It's processor power or the lack of it, that slows it down, but ATL.net doesn't need much, I guess, as it's all I/O bound?

> I guess you still have my e-mail

I'm afraid I don't. Are you on Reddit.com? I'm "audiamus" there as well.

**Comment by Zeugma440** [comment]
You're right, what ATL does either takes up RAM or disk I/O but overall is very light on CPU (worst that can happen is hashing data or decoding/encoding strings ^^).

The "direct to disk" method moves bytes around on disk as many times as there are zones to edit within the file. For MP4s with chapters, these zones can be quite numerous, depending on the structure of the file (the MP4 format is very versatile, it's hard to come up with "average" figures).

If the file to be processed in located on an SSD drive, there should be indeed nothing to fear. However, if it is located on a low-end SD card (mobile app) or even worse, on a network drive, performance is drastically lower than with buffered / hybrid mode.

That being said, here's what I suggest :
- Release a v3.12 with the old direct vs. buffered modes + a new `Settings.forceDiskIO` option to force "direct to disk"
- Once I have the file you're testing with, I'll fine-tune hybrid mode to lower its memory usage

Is that okay to you ?

**Comment by Zeugma440** [comment]
PS : I just sent you a message on Reddit. My account has a different name - it's not a scam, don't worry 😋

**Comment by audiamus** [comment]
> Is that okay to you ?

Yes, that's great.

**Comment by audiamus** [comment]
> Once I have the file you're testing with, I'll fine-tune hybrid mode to lower its memory usage

The sample file represents the final result, including the chapters. The scenario is this: 
1.  FFmpeg transcoding, during which original meta data, including chapters, is stripped off (with the respective FFmpeg parameters), and cover image (the video stream) discarded.
2.  Setting the customized non-chapter meta data and cover image, currently still with TagLibSharp. (To be replaced with ATL.net in the future) 
3. Setting the chapter meta data with ATL.net

To recreate the starting point for step 3 with the sample file, you can extract the chapter data from it and remove the chapter meta.

**Comment by Zeugma440** [comment]
Thanks for these precisions

> To recreate the starting point for step 3 with the sample file, you can extract the chapter data from it and remove the chapter meta.

What are you using to remove chapter meta ? ATL or an external tool ?

**Comment by audiamus** [comment]
> What are you using to remove chapter meta ? ATL or an external tool ?

FFmpeg, Something like this:
`FFmpeg -hide_banner -i infile.m4b -map_chapters -1 -vn -c:a copy outfile.m4b`

**Comment by Zeugma440** [comment]
v3.12 has been uploaded to NuGet. You can now use `Settings.ForceDiskIO`

**Comment by audiamus** [comment]
> You can now use Settings.ForceDiskIO

Very good, thanks a lot. Will do that. And then running my tests again ...  :relieved:

**Comment by Zeugma440** [comment]
Small update on the topic : I'm still in the process of optimizing RAM usage for the hybrid I/O mode.

There are still a couple unit tests where results are not satisfying. Expect a pre-release somewhen between this week-end and next week.


I hope your tests with v3.12 are conclusive so far 😁  

PS : I don't see any unit tests in your github repo. Are you using some ?  Obviously, it's a pain to set them up initially, but it's definitely worth the time !

**Comment by audiamus** [comment]
> Expect a pre-release somewhen between this week-end and next week.

I plan to release AAX Audio Converter 1.15 next weekend now and am quite happy with the current direct disk mode for that version. Please do not feel under any pressure. There will also be a version 1.16 and I still want to completely replace TagLibSharp for the remaining meta data.

> PS : I don't see any unit tests in your github repo. Are you using some ? Obviously, it's a pain to set them up initially, but it's definitely worth the time !

_In my professional work, I create unit tests all over the place for all our fundamental libraries. Otherwise, we wouldn't be able to maintain those._

_But I always regarded AAX Audio Converter as a leisure project, a pastime. So, not all the professional conventions will apply. And unit tests for this application aren't simple. While there is a clear project separation between the GUI and the executing lib, unit testing would still need a mock-up for the GUI. And asserts aren't easy either, as they most often will require audio file analysis. Then there is some other software I am doing as a hobby, (closed source, payware, written in C++, in a totally different sector) which requires attention, too, as it has been neglected for too long._

_On the other hand, I didn't expect over 30,000 downloads until now. We'll see..._

**Comment by Zeugma440** [comment]
New optimized hybrid mode is now on the main branch. It buffers data with lowered RAM usage when "direct to disk" is disabled.

Under the hood, instead of working in one single block as they did before , buffers now work in _regions_ of overlapping or adjacent editable zones. As a consequence, file with distinct editables zones located at their beginning and their end stop being buffered entirely (your sample was precisely in that case 😁 ).

Please keep me informed so that we can close this issue. Thanks in advance~~

**Comment by audiamus** [comment]
Very good. I'll try it in the coming days.

> Under the hood, instead of working in one single block as they did before , buffers now work in regions of overlapping or adjacent editable zones. 

Sounds very reasonable to me.

**Comment by audiamus** [comment]
Checked with our sample book. Entire aax file: 238,495,612 bytes

The 2nd time it gets to the critical point (1st one is for 8 bytes):
ATL.AudioData.IO.FileSurgeon in line 183: `int initialBufferSize = region.Size;`
`initialBufferSize` is 170,475,399
But this does not lead to a MemoryStream, as region.IsBufferable is false

call stack:
```
ATL.AudioData.IO.FileSurgeon.RewriteZones(fullScopeWriter, write, zones, dataToWrite, tagExists, useBuffer) Line 184
ATL.AudioData.IO.FileSurgeon.RewriteZones(w, write, zones, dataToWrite, tagExists) Line 138
ATL.AudioData.IO.MetaDataIO.Write(r, w, tag, writeProgress) Line 713
ATL.AudioData.AudioDataManager.UpdateTagInFile(theTag, tagType) Line 253
ATL.AudioData.AudioFileIO.Save(data) Line 106
ATL.Track.Save() Line 459
```

A memory stream is created the 3rd time, with a smaller buffer size:
ATL.AudioData.IO.FileSurgeon in line 191: `buffer = new MemoryStream(initialBufferSize);`
`initialBufferSize` is 1,907,538
This is not my 2 MB buffer I asked for in the ATL.Settings, I presume.

The call stack is the same.

And memory appears to grow by that amount, basically the MemoryStream.


If that's the expected behavior then I should think it is OK.

**Comment by Zeugma440** [comment]
Looks fine 👍 As you saw, the 2nd call does not allocate anything as the region is marked as non-bufferable. Calls 1 and 3 allocate just what they need.

You may enable debug logging in the standard output for a detailed recap of `FileSurgeon`'s I/O operations, just by calling `ConsoleLogger log = new ConsoleLogger();` before saving / updating your file.

***

> This is not my 2 MB buffer I asked for in the ATL.Settings, I presume.

There's a slight misunderstanding here : the 2MB buffer you set up is the one used for basic low-level I/O operations called everywhere in the library (namely, `StreamUtils.CopyStream`, `StreamUtils.CopySameStream`, `StreamUtils.ShortenStream`, `StreamUtils.LengthenStream`...).

The buffers created by `FileSurgeon` do not depend on `Settings` as they must have the same size as the editable zones of the file you're updating. They allow the app to resize them in memory rather than by moving bytes on the disk.

e.g. if zone 1 has to be shortened of -20 bytes and adjacent zone 2 lengthened of +40 bytes :
  - Direct-to-disk mode will perform two successive disk operations, removing 20 bytes and then inserting 40 bytes
  - Hybrid buffered mode will do the operations above _inside a buffer_ and eventually do one single disk operation, inserting 20 bytes

***

If you're okay with all this, I'm ready to publish a new binary on NuGet and close the issue. Keep me informed~~

**Comment by audiamus** [comment]
> There's a slight misunderstanding here : the 2MB buffer you set up is the one used for basic low-level I/O operations called everywhere in the library (namely, StreamUtils.CopyStream

Not a misunderstanding really, I just wanted confirmation. I noticed that the buffer setting gets used in the `StreamUtils.CopyStream` method.

> If you're okay with all this, I'm ready to publish a new binary on NuGet and close the issue. 

Yes, that's fine with me.

**Comment by Zeugma440** [comment]
v3.13 has just been published on NuGet. Enjoy !
