### ISSUE TITLE
Strange phenomenon with MP3/ID3v2 chapters

### ISSUE THREAD

**Issue by audiamus** [Zeugma440/atldotnet#73]
## The problem

ID3v2 chapters for MP3, written by ATL.net and FFmpeg, show different behavior with VLC. With chapters written by FFmpeg, VLC shows correct track duration, while this information appears to missing, if chapters are written with ATL.net.     

## Environment

* ATL version: 3.12
* OS/version Win7, .Net 4.7.1

## Details

Media players VLC and MPC-HC:

VLC does not understand ID3v2 chapters but it seems to grasp some information from the meta data that reveals total track duration, spanning all chapters. This information seems to be present if the chapters have been written with FFmpeg, but missing, if written with ATL.net. In that case, VLC estimates the duration presumably from codec parameters and file size, an iteration taking a few seconds to settle to a final value.

MPC-HC, on the other hand, has no problems with either chapter data source.

Any idea what FFmpeg might do in addition to ATL.net?

I will upload two MP3 samples for you. 

## Code To Reproduce Issue [ Good To Have ]

No code, but reproducible with every MP3 file.

**Comment by Zeugma440** [comment]
Thanks for the feedback and thanks in advance for samples.

Before we go further, did you notice that there are two different ways to define chapter boundaries in ID3v2 ?
 - `ChapterInfo.StartTime` / `ChapterInfo.EndTime` (when `ChapterInfo.UseOffset` is set to `false`, which is the default value) - value is in milliseconds
 - `ChapterInfo.StartOffset` / `ChapterInfo.EndOffset` (when `ChapterInfo.UseOffset` is set to `true`) - value is in bytes

**Comment by audiamus** [comment]
> Before we go further, did you notice that there are two different ways to define chapter boundaries in ID3v2

I'm using the default with start/end milliseconds. That's identical to the start/end milliseconds I feed into the FFmpeg meta data file.

**Comment by Zeugma440** [comment]
I don't have an answer yet but interesting observations.  I tried to start from scratch by removing all metadata from the sample files you sent. Turns out the strange phenomenon you're observing _still happens_ when playing metadata-free files with raw audio data only.

By looking closer, I found out that both files aren't encoded the same way : 
 - `sample_atl_chapters` has 118 682 405 samples and has encoder-specific information that appear when opening the file in foobar2000

![image](https://user-images.githubusercontent.com/29414549/97145728-f8034900-1766-11eb-9861-a4b31541c591.png)


 - `sample_ffmpeg_chapters` has 118 683 119 samples and just one of the above properties

![image](https://user-images.githubusercontent.com/29414549/97145672-e15cf200-1766-11eb-9db0-5b3acc98b653.png)

From where I stand, I'd say the problem does not come from metadata but from the encoding parameters you used.
If you're convinced metadata is the problem, please send new samples with identical audio data.

**Comment by audiamus** [comment]
> I'd say the problem does not come from metadata but from the encoding parameters you used.

The audio should only differ by a few milliseconds of silence, a waveform analysis should reveal that. 

The relevant workflow in both variants is currently as follows: 

ATL.net chapters:

1. Transcode in FFmpeg with one audio m4a input file, discarding meta data (-1), discarding chapter data (-1), discarding video (cover image)
2. Add non-chapter meta data with TagLibSharp (plus cover image)
3. Add chapter meta data with ATL.net 

FFmpeg chapters:

1. Transcode in FFmpeg with two input files: m4a audio and meta data in FFmpeg text format, containing chapters only. Discarding other meta data (-1), discarding video (cover image)
2. Add non-chapter meta data with TagLibSharp


So the only difference in the FFmpeg parameters is the presence or absence of the second input file with the chapter meta, and the chapter meta parameter, which is either -1 for discarding or 1, standing for zero based input file index.

Earlier versions of AAX Audio Converter (before 1.12, May 2020) did not add meta data chapters to MP3 at all. I didn't even know about their existence, particularly with VLC as my standard test player wouldn't have recognized them. But I had always noticed that VLC couldn't come up with the correct track duration when loading the file. It was more of a side effect that adding meta chapters with FFmpeg suddenly solved the duration problem with VLC. 

Hence I thought that adding ID3v2 chapters would automatically insert the necessary data to provide track duration. It left me somewhat confused when I found out that this assumption was incorrect. But you always learn new things here...

Anyway, it's not a big deal, just two lines of code to invoke either of the two chapter variants.

**Comment by Zeugma440** [comment]
Thanks for the detailed explanation - I see what you mean regarding the woarkaround you found with FFmpeg and chapters, even though its actual effects are still quite obscure.

I might have some knowledge about metadata but I still don't know much about audio signal compression and encoding. I fear I can't help you there, unfortunately.

Would you mind if I closed this issue ?

**Comment by audiamus** [comment]
> Would you mind if I closed this issue ?

No problem. As I said, two lines of code, to revert to FFmpeg for MP3 chapters. (After some modifications yesterday to prepare the sample data.)

_Will check MP4 chapters with your changes later today._
