### ISSUE TITLE
MP4 chapters, next one

### ISSUE THREAD

**Issue by audiamus** [Zeugma440/atldotnet#75]
## The problem

With the latest version of ATL.net we seem to have incomplete chapters for MP4 (M4A/M4B). It only affects the Quicktime variant. 

## Environment

* ATL version: 3.13
* Last ATL version that did not exhibit the issue (if applicable): 3.12
* OS/version used to run ATL: Win7, .Net 4.7.1

## Details

This is presumably related to the previous work on these issues:  #67 and #71. The new buffered mode, introduced with 3.13, may not yet work as intended. 3.12 with `ATL.Settings.ForceDiskIO = true` does not have the problem.

This is the original issue in the AAX Audio Converter project: https://github.com/audiamus/AaxAudioConverter/issues/37 

Same settings as for the previous issues I reported. 

Here is my example with the results shown by MediaInfo:

- ATL.net 3.13 with `ATL.Settings.ForceDiskIO` `false` or `true`:

![info-quicktime-missing](https://user-images.githubusercontent.com/47717419/99107298-e682c380-25e5-11eb-9f70-561a93910571.png)

No Quicktime chapters. Nero chapters are there.
FFmpeg/FFprobe report the chapters, basically all of them, all with timing, but many without title. MediaInfo does not show a single one.  

- ATL.net 3.12 with `ATL.Settings.ForceDiskIO = true;`  

![info-quicktime-present](https://user-images.githubusercontent.com/47717419/99107365-06b28280-25e6-11eb-9bc9-6af5e5385d53.png)

Both Quicktime and Nero chapters are present. No issue here.

## Code To Reproduce Issue [ Good To Have ]

Can be reproduced with the M4B sample I uploaded for #71.

Extract the chapters, strip off the the meta (see https://github.com/Zeugma440/atldotnet/issues/71#issuecomment-712013118) and add the chapters again with 3.12 and 3.13.

**Comment by Zeugma440** [comment]
Alright, I'll take a look and set up a proper unit test for that case.
This might take a little longer than usual as I'm in the process of releasing another project...

**Comment by Zeugma440** [comment]
Looks like I found where that regression comes from. Damn myself for not documenting some tricky parts.

I'm gonna do a few more tests and post the fix.

**Comment by Zeugma440** [comment]
Alright, today's batch of changes should do it !

Long story short, I've been trying for the next few months to handle a certain slippery case in one pass, without success. I've abandoned this idea and switched to a 2nd pass instead, which is way simpler to code and to debug.

As a bonus :
- Also fixed the fact that ATL couldn't properly write non-western characters in Quicktime menu titles
- Added a new `Settings.MP4_readChaptersExclusive` to have more control over which kind of chapters you read from the file (Quicktime or Nero)

Please let me know if it's good on your side too.

**Comment by Zeugma440** [comment]
Last but not least, I've made it so every chapter starts at the end of the one before it, whatever value you give to `EndTime`.

That allows to quickly write chapter addition code with only giving `StartTime` and `Title`, e.g.
```csharp
            theTrack.Chapters.Add(new ChapterInfo(0, "Prologue: Mei"));
            theTrack.Chapters.Add(new ChapterInfo(790 * 1000, "Chapter One: Bobbie"));
            theTrack.Chapters.Add(new ChapterInfo(2214 * 1000, "Chapter Three: Prax"));
```

Please tell me if you need to add "gaps" between your chapters, because ATL can't do that anymore.

**Comment by audiamus** [comment]
I have now tested it with your latest sources this morning, books long and short, and checked the results with MediaInfo and FFmpeg. MediaInfo shows both "menus" with complete chapter data and FFmpeg shows all chapter titles.

So it looks OK to me. 

Have there been any changes to memory allocation during the process? I only took a few memory snapshots "before" and "after" and couldn't see anything suspicious.

**Comment by Zeugma440** [comment]
That's very good news, thanks for checking !

The updated process is still very close to the old one, and has a minimal impact on performance, along the lines of :
- Even less RAM allocation on certain file layouts
- A slightly longer processing time (<1 sec), as there is now a post-processing pass that rewrites 4 bytes directly to the file

I'm gonna publish the changes to NuGet. Keep me informed if you need anything else 😄
