### ISSUE TITLE
mp3 metadata updates not being saved

### ISSUE THREAD

**Issue by Arrow-b** [Zeugma440/atldotnet#77]
## The problem

metadata updates for mp3 files are not being saved.

## Environment

* ATL version (or git revision) that exhibits the issue: 3.13.0
* Last ATL version that did not exhibit the issue (if applicable):
* OS/version used to run ATL Windows10

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Code To Reproduce Issue [ Good To Have ]

        Dim IData As New IMeta.Track(argFileNam)

        If updateFlac Then
            If Me.orgAlbum <> "" Then IData.Album = Me.orgAlbum
            If Me.orgContributingArtist <> "" Then IData.Artist = " "
            If Me.orgGenre <> "" Then IData.Genre = Me.orgGenre
            If Me.orgTitle <> "" Then IData.Title = Me.orgTitle
            If Me.orgTrackNum <> "" Then IData.TrackNumber = Me.orgTrackNum
            If Me.orgDate <> "" Then IData.Comment = Me.orgDate
            If Me.orgAlbumArtist <> "" Then IData.AlbumArtist = Me.orgAlbumArtist
            If Me.orgComposer <> "" Then IData.Composer = Me.orgComposer
            If Me.orgDiskNum <> "" Then IData.DiscNumber = Me.orgDiskNum
            If Me.orgDisk_Total <> "" Then IData.DiscTotal = Me.orgDisk_Total
            If Me.orgTackTotal <> "" Then IData.TrackTotal = Me.orgTackTotal

            IData.Save()

**Comment by Zeugma440** [comment]
There's nothing wrong with that code at first sight, but I notice that you don't directly use `ATL.Track` but something called `IMeta.Track`. Could I have a look at that class too ?

**Comment by Zeugma440** [comment]
Plus you wanna be sure the bug comes from ATL and not from your UI or anything else. 

There's so much that can go wrong in the code you posted (`updateFlac` not having the correct value, ` Me.orgxxx` values not being updated, `IMeta.Track` having issues on its own...)

Please try with minimalistic code to isolate the issue.

**Comment by Arrow-b** [comment]
Forgot  to mention Imports IMeta = ATL and Dim IData As New IMeta.Track(argFileNam)

 

Have tried minimal code.   Some files it works fine other files the save fails.

 

You mentioned incorrect data, so if I am updating only one value and the metadata contains incorrect value.  Would that cause the save fail.

**Comment by Zeugma440** [comment]
I can't do much on my side with what you're telling me. There's no known issue regarding MP3s.

If we want to progress here, I'd need :
1/ one of the files that don't work for you (you may send through wetransfer, mega or any other file transfer tool to zeugma440@hotmail.com)
2/ a piece of code to run on this file to trigger the bug you're experiencing

Thanks in advance

**Comment by Zeugma440** [comment]
Closing the issue because no answer after one entire month.

Please reopen it if you still need help.
