### ISSUE TITLE
Question: can this library also be used to just write the header from an opus file?

### ISSUE THREAD

**Issue by StefH** [Zeugma440/atldotnet#79]
I tried this code:
``` c#
var theTrack = new Track("new-file.opus", false);
theTrack.AudioFormat = new Format(1, "OGG : Vorbis, Opus", "OGG");
theTrack.SampleRate = 48000;
theTrack.Chapters = new List<ChapterInfo>();
theTrack.ChaptersTableDescription = "";
theTrack.AdditionalFields = new Dictionary<string, string>();

theTrack.Save();
```

However this throws exception.

Is this supported?

**Comment by Zeugma440** [comment]
Hello and thanks for your feedback.

I'm not sure I really understand what you're trying to do here. Do you want to modify the file's sample rate ?

Having the copy / screenshot of the stacktrace would help too 😉

**Comment by StefH** [comment]
Hello @Zeugma440,

I want to create a new opus file using this project, so just by using this code:
``` c#
var theTrack = new Track("new-file.opus", false);
theTrack.AudioFormat = new Format(1, "OGG : Vorbis, Opus", "OGG");
theTrack.SampleRate = 48000;
theTrack.Chapters = new List<ChapterInfo>();
theTrack.ChaptersTableDescription = "";
theTrack.AdditionalFields = new Dictionary<string, string>();

theTrack.Save();
```

I want to be able to save a file which is a valid Opus File. But I'm not sure if this is possible?

The exception is like:
```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at ATL.Track.toTagData()
   at ATL.Track.Save()
```

**Comment by Zeugma440** [comment]
> I want to create a new opus file using this project, so just by using this code

Unfortunately, ATL can't be used to create audio files from scratch. The library can only handle metadata, and does not know how to set up the rest of the file (namely, audio data).

I'd suggest you use `ffmpeg` or `opusenc` to do that.
