### ISSUE TITLE
Parse Exception

### ISSUE THREAD

**Issue by MikiraSora** [Zeugma440/atldotnet#8]
## The problem
It's always throw exception when ATL is try to load some audio file.other audio files is fine.

## Environment

2.4.0 at Nuget ,2.3.0 same

Win10 1709 
.Net framework 4.6.1
vs2017

## Details

![](https://puu.sh/AHvSv/300a059c3d.png)
[problem audio file](https://puu.sh/AHvSO/63771711c9.mp3)

## Code To Reproduce Issue [ Good To Have ]

[Code](https://github.com/OsuSync/LyricDisplayerPlugin/blob/master/LyricDisplayerPlugins.cs#L282-L298)

**Comment by Zeugma440** [comment]
Hey there,


Thanks for the report !

I cannot access the sample file you send. The link you provided does not work (it displays a "That puush could not be found." page).

Could you try sending the file again please ?


Thanks in advance,

Cheers,

-Z440

**Comment by MikiraSora** [comment]
[dl](http://mikirasora.moe/dl/fge.mp3)

**Comment by Zeugma440** [comment]
Great, got it. I'll look into it and keep you informed.

**Comment by Zeugma440** [comment]
Looks like disc number is "69070A09", which was kinda unexpected. That's no excuse for a crash, though.

I'll post a fix soon (in that case : disc number = 0)

**Comment by Zeugma440** [comment]
Fixed with b738824aa87b77540fb2bc66b84ba8ae2bd2f3e4

**Comment by MikiraSora** [comment]
good job,thx 😄
