### ISSUE TITLE
When updating a WAV file fails, it writes directly to Console, but it does not inform the calling code about the failure (Exception is swallowed)

### ISSUE THREAD

**Issue by darzid** [Zeugma440/atldotnet#82]
## The problem

When something fails while updating the metadata of an audio file, the ATL library writes that exception directly to Console.
This happens in the method _AudioDataManager.UpdateTagInFile_. That method **does** return false when an exception occurs, however, the calling code in my case (_AudioFileIO.Save_) does not check the returned boolean value, and since it's a void method on it's own, it does not inform the calling code **(my code)**.

My suggestion:

The current code in AudioFileIO.Save:
_foreach (int meta in availableMetas)
{
  audioManager.UpdateTagInFile(data, meta);
  if (writeProgress != null) writeProgress.Report(written++ / availableMetas.Count);
}_

The proposed code:
_bool errorWhileUpdating = false;
foreach (int meta in availableMetas)
{
  if (!audioManager.UpdateTagInFile(data, meta))
    errorWhileUpdating = true;
  if (writeProgress != null) writeProgress.Report(written++ / availableMetas.Count);
}_

return errorWhileUpdating;_

Of course, this requires the return type of the Save method to change from void to bool.
With this approach, the calling code knows that something fails while writing the metadata.

## Environment

* ATL version (or git revision) that exhibits the issue: Latest from master
* Last ATL version that did not exhibit the issue (if applicable): N/A
* OS/version used to run ATL: Windows 10

**Comment by Zeugma440** [comment]
Indeed, I'm even surprised nobody complained until now.

The exception swallowing had been done on purpose, but there should definitely be a return value not to keep calling code in the dark.

**Comment by Zeugma440** [comment]
Done - the change will be part of next update 😁

**Comment by darzid** [comment]
Thanks! That was quick again 😃
"Unfortunately" you fixed the other issue, so I can't test it anymore with those files. Hahaha.

Good stuff!

Mvg, Steven

________________________________

**Comment by Zeugma440** [comment]
You're very welcome.

By the way, I think you can test it by trying to write over files locked with read-only.

**Comment by Zeugma440** [comment]
Included in today's v3.16
