### ISSUE TITLE
Track Save() : When adding new additional field, Track is not updated when it contains only a ID3v1 tag

### ISSUE THREAD

**Issue by angular-prj** [Zeugma440/atldotnet#83]
I noticed that the Track.Save() or Update() doesn't work if there's only a ID3v1 tag present in the track,
when adding additional / custom fields.
Workaround that I used: Use another tool (mp3tag) to create the ID3v2.3 tag first
Another workaround is to remove the ID3v1 tag first.

**Comment by Zeugma440** [comment]
~~is ID3v1 still a thing in 2021 ?~~

Thanks for the feedback ! Reproduced on my side as well.

I'm gonna add a new setting to consider a file tagged with ID3v1 only as untagged, allowing ATL to add tag formats defined in `Settings.DefaultTagsWhenNoMetadata`.

This setting will be `true` by default. People who want to edit ID3v1 exclusively will have the possibility to switch it back to `false`.

**Comment by Zeugma440** [comment]
New setting `Settings.EnrichID3v1` added.

This will be available in next update.

**Comment by Zeugma440** [comment]
Included in today's v3.16
