### ISSUE TITLE
Can I use with AVAssets on iOS?

### ISSUE THREAD

**Issue by Hackmodford** [Zeugma440/atldotnet#87]
## The problem

The library only accepts a stream or a file path.

## Environment

iOS

## Details

This is more of a general question or feature request than a bug.
Would it be possible to use an AVAsset object when creating a track?
I tried passing in the path of the AVAsset but that doesn't work (as I suspected).

**Comment by Zeugma440** [comment]
Hi and thanks for your feedback.

I'm not really sure I understand what is your need here : encapsulate the public properties of AVAsset into a Track, or access the underlying multimedia resource to read its raw data ?

**Comment by Hackmodford** [comment]
I was hoping I could use this library to get the embedded chapters of a AVAsset in a Xamarin.iOS project I'm working on. It doesn't work because iOS doesn't give me access to the actual file.

I don't know if this request is really in scope for this project. There is an objective-c library that does this. [MNAVChapters](https://github.com/michaelnisi/MNAVChapters)

I did create a [binding](https://github.com/Hackmodford/MNAVChapters-ios-binding) for the library.

**Comment by Zeugma440** [comment]
Thanks for the link, that's much clearer like that 😉 

I think AVAsset features can indeed be encapsulated into the ATL API by porting what MNAVChapters does to C#.

The only problem here is I'm on a Windows machine, without access to any iOS machine. And if I'm not mistaken, the AVFoundation Namespace is specific to the iOS Xamarin SDK...

Maybe we should work on that one together ?

**Comment by Hackmodford** [comment]
I tried porting it first before I just made a binding for it.

I'm pretty sure I got the mp4 path all done, but the id3 path got into a bunch of low level byte manipulation that I wasn't really comfortable doing. If you'd like I can share what I have so far.

**Comment by Zeugma440** [comment]
Sure; I'll do my best to answer the questions you might have

**Comment by Hackmodford** [comment]
Well... I don't seem to have it anymore. 
In any case, [this](https://github.com/michaelnisi/MNAVChapters/blob/38c2205d9e599b1ee07a5686acd8fd63c1cd4297/MNAVChapters/MNAVChapterReader.m#L456) was the part I wasn't sure on.

**Comment by Hackmodford** [comment]
False alarm! I found it hidden on my hard drive.

https://gist.github.com/Hackmodford/9bfd7144d51fc9dc7f74087d7d07f0e4

**Comment by Zeugma440** [comment]
I've added a few comments below. Do you mind if we continue the conversation there ?
