### ISSUE TITLE
Multiple artists, etc.

### ISSUE THREAD

**Issue by Royce551** [Zeugma440/atldotnet#89]
## The problem
Hi! I use ATL for my audio player, and I couldn't find any way to display all of the artists for tracks with multiple artist tags. Did I miss something? If not, can support for this be added?
## Details
Track.Artist appears to just return the first artist.

**Comment by Zeugma440** [comment]
Hi and thanks for your interest in ATL.net :)

I'm not certain on how to answer as it depends on how these files have been tagged. Would it be possible to send one of them through wetransfer, mega or any other file sharing platform to zeugma440@hotmail.com ?

**Comment by Royce551** [comment]
https://drive.google.com/drive/folders/1A1YFHmGJiMbZROqxfYWY31N2c638nXBW?usp=sharing
When I was looking for a mp3 to share, I found out that mp3s do show the artists correctly, it's just flacs, from what I've seen.

**Comment by Zeugma440** [comment]
The reading part is done on my side - FLAC and OGG tracks with multiple artists will be read with the following data
`artist1;artist2;artist3`, with `;` being a customizable value (see `Settings.DisplayValueSeparator`)

Before publishing the code, I have a question for you : do you plan to update these fields, or just read them ?

**Comment by Royce551** [comment]
Reading only is cool, however being able to update the fields as well would be nice, especially since my app has a tag editor.

**Comment by Zeugma440** [comment]
A fix is available on today's v1.19

- Vorbis-tag : Fields with multiple values are now properly detected

e.g. `ARTIST=aaa  ARTIST=bbb` will be displayed as `aaa;bbb` when `Settings.DisplayValueSeparator` is `;` (customizable)

- Vorbis-tag : The `Artist` field is now saved as a multiple value tag, using `Settings.DisplayValueSeparator` as separator

e.g. `aaa;bbb` will be saved as `ARTIST=aaa  ARTIST=bbb` when `Settings.DisplayValueSeparator` is `;` (customizable)


Can you confirm it works for you ?

**Comment by Royce551** [comment]
Thank you! I can confirm that everything works as expected.
