### ISSUE TITLE
Is there a way to access a track's picture original path ?

### ISSUE THREAD

**Issue by ComradeDracose** [Zeugma440/atldotnet#93]
Hi,
I'm currently attempting to serialize some of the data in an ATL track, however serializing a byte array (as the format of an image) is very costly in information.
Is there a way for me to find the original path of a track's embedded picture ? I would only need to serialize this and save myself the hassle.
Or, if there is no way, can anyone suggest a different route to take ?

Best Regards

_Originally posted by @ComradeDracose in https://github.com/Zeugma440/atldotnet/discussions/92_
PS : I wanted to delete the discussion post I have made and upload this question as an issue, but it seems I am not able to delete it. Sorry for the trouble.

**Comment by Zeugma440** [comment]
Hi and thanks for your interest in ATL.net !

Why would you want to serialize the embedded picture in the first place ?  What is your use case ?

Unfortunately, no format saves the original path of its embedded pictures. Maybe you can simply save the picture's data (byte array) into a separate file that you create yourself, and save that file's path into your container ?

PS : I've deleted the discussion post

**Comment by ComradeDracose** [comment]
Hi,

My use case is making a music library application. When booting the app, it should look in the appdata (that I've saved) for any info to retrieve and display the songs a user has added to their library. This includes the artwork.

I think what you're proposing would still mean writing redundant data to the disk, which is what I want to avoid.

If there really is no other option, I thought of a way, which is to load the Artwork from a track's filepath (which i save), as I deserialize it :). So no biggie. 

PS : Thanks :)

**Comment by Zeugma440** [comment]
You're welcome !
