### ISSUE TITLE
Can't create instance of Track if TrackNumber is wrongly formatted

### ISSUE THREAD

**Issue by ComradeDracose** [Zeugma440/atldotnet#94]
Hi,
I tried creating a `Track track = new Track(filePath)`, but it seems to break on precisely one of my songs. The error returned was System.FormatException: 'Input string was not in a correct format.' (image) :
![image](https://user-images.githubusercontent.com/72915180/115972769-4348b980-a548-11eb-89d3-53fb2d4e670c.png)

I eventually figured out that the particular song's Track Number was wrongly formatted : Instead of being 'TrackNumber/TrackTotal', it was 'TrackNumber//TrackTotal'.

I had never noticed this because iTunes (what I usually use) always parsed this correctly.

I'm bringing this to your attention, you're the judge on whether this is worthy of a fix or not :)

**Comment by Zeugma440** [comment]
That's a good one :)

I've added a specific unit test and fixed your issue (and other similar issues). Thanks !

**Comment by Zeugma440** [comment]
Fix published in today's release (v3.21)
