### ISSUE TITLE
Wrong duration on some of my tracks

### ISSUE THREAD

**Issue by ComradeDracose** [Zeugma440/atldotnet#96]
Hi,
I think I have spotted a bug, I'm not sure why it is happening, however one of the tracks I'm trying to work with has an incorrect duration on ATL.Track.

Attached are the actual length :

![2021_05_24_15_26_01_Propriétés_de_1_I_like_it_like_thatmp3](https://user-images.githubusercontent.com/72915180/119362412-924b5100-bca4-11eb-979a-4285e4db7f4f.png)

And the length which is given to me when I open an instance of Track using the filepath that points to that particular track :

![image](https://user-images.githubusercontent.com/72915180/119361742-e73a9780-bca3-11eb-933e-66b62b3e6cb5.png)

This comes up to about 40-something minutes, instead of 4 something. And it's not like it's x10 either, I checked.

I'll also link the track in question so you can hopefully reproduce this bug :
[Broken Duration Song.zip](https://github.com/Zeugma440/atldotnet/files/6533039/1.I.like.it.like.that.zip)

**Comment by Zeugma440** [comment]
Thanks for your feedback.

It looks like the audio part of that file has been somewhat truncated, which makes finding its header a little tricky. I'll investigate a little more and leep you informed.

**Comment by ComradeDracose** [comment]
Thanks for letting me know.

**Comment by Zeugma440** [comment]
I found a way to do more precise tests in order to filter out false positives while detecting headers.

The fix will be published on the next update (still one issue to resolve before that).

**Comment by Zeugma440** [comment]
Fix published in today's release (v3.21)
