### ISSUE TITLE
Unable to edit out a Disc from a track

### ISSUE THREAD

**Issue by ComradeDracose** [Zeugma440/atldotnet#97]
Hi,
I'm trying to write over some of my tracks' details. 
In this particular instance, I want to take out the disc number.

This is a screenshot of the instance of Track, after I use the constructor with a file path :
![image](https://user-images.githubusercontent.com/72915180/119696690-5c929d80-be47-11eb-8925-f06c066e4ecc.png)

As you can see, it has DiscNumber as disc 1 and a total of 1 discs.

I edit this information in the instance of Track and before calling track.Save(), I have this :
![image](https://user-images.githubusercontent.com/72915180/119696508-2ce39580-be47-11eb-99af-54875b9d6137.png)

So far so good, but after I call track.Save(), track returns this :
![image](https://user-images.githubusercontent.com/72915180/119696765-6916f600-be47-11eb-9b2e-427021dfce15.png)

And when I inspect the file in file explorer, it still has the old number of discs :
![image](https://user-images.githubusercontent.com/72915180/119697469-1ee24480-be48-11eb-854b-0f7416b4b939.png)

Is there something I am missing ? Am I using Track.Save() appropriately ?

**Comment by Zeugma440** [comment]
Hello again Comrade 😉 

I'd like to do some tests on my end to reproduce your issue.
Could you please tell me which format you're testing with (e.g. mp3, mp4, ogg...) ?

Thanks in advance~

**Comment by ComradeDracose** [comment]
Hello again

No problem, I'm currently working with mp3. 
I'll make sure to mention the format I'm working on when I have another issue to submit ! 

Comradely ;)

**Comment by Zeugma440** [comment]
Believe it or not, but that use case had never been tested... and had a bug 😒 

The fix is available on today's v3.22 release.
